"""Niche, notation, broadcast, and extended coverage catalog."""

def _p(n,s,d,c,pr,pt,desc,url,r,rc):
    return {"name":n,"slug":s,"developer":d,"category":c,"price":pr,"priceType":pt,
            "description":desc,"url":url,"rating":float(r),"ratingCount":int(rc)}

PRODUCTS = [
    # ─── NOTATION SOFTWARE ────────────────────────────────────────────────────
    _p("Sibelius Ultimate","sibelius-ultimate","Avid","midi","Subscription","subscription","Industry-standard music notation software for professional composers and arrangers.","https://www.avid.com/sibelius",4.7,934),
    _p("Sibelius First","sibelius-first","Avid","midi","$9","subscription","Entry-level Sibelius for students and hobbyist composers.","https://www.avid.com/sibelius",4.5,534),
    _p("Finale 27","finale-27","MakeMusic","midi","$600","paid","Professional music notation software with advanced engraving tools.","https://www.finalemusic.com/",4.6,712),
    _p("Finale PrintMusic","finale-printmusic","MakeMusic","midi","$119","paid","Accessible notation software for students and hobbyist musicians.","https://www.finalemusic.com/",4.4,312),
    _p("Dorico Pro 5","dorico-pro-5","Steinberg","midi","$579","paid","Modern music notation application with audio playback and DAW integration.","https://www.steinberg.net/dorico/",4.8,534),
    _p("Dorico Elements 5","dorico-elements-5","Steinberg","midi","$99","paid","Mid-tier Dorico for composers and music educators.","https://www.steinberg.net/dorico/",4.7,345),
    _p("Dorico SE","dorico-se","Steinberg","midi","Free","free","Free version of Dorico notation software for beginners.","https://www.steinberg.net/dorico/",4.5,712),
    _p("MuseScore 4","musescore-4","MuseScore","midi","Free","free","Free open-source music notation software and sheet music community.","https://musescore.org/",4.7,1456),
    _p("Notion 6","notion-6","PreSonus","midi","$149","paid","Music notation and composition software with studio-quality playback.","https://www.presonus.com/products/Notion",4.5,345),
    _p("Flat","flat-notation","Tutteo","midi","Free","free","Cloud-based music notation editor with real-time collaboration.","https://flat.io/",4.4,423),
    _p("Guitar Pro 8","guitar-pro-8","Arobas Music","midi","$69","paid","Tablature and notation editor for guitar, bass, and stringed instruments.","https://www.guitar-pro.com/",4.7,1234),
    _p("TuxGuitar","tuxguitar","TuxGuitar","midi","Free","free","Free open-source guitar tablature editor and player.","https://tuxguitar.app/",4.3,534),

    # ─── CHORD / THEORY TOOLS ────────────────────────────────────────────────
    _p("Hooktheory","hooktheory","Hooktheory","midi","$44","paid","Music theory learning platform with interactive chord analysis tools.","https://www.hooktheory.com/",4.7,712),
    _p("Progressions","progressions-app","Notion","midi","$9","paid","Chord progression composer and MIDI generator for iOS.","https://apps.apple.com/",4.5,312),
    _p("Chord! Pro","chord-pro-app","Chord! Pro","midi","$4","paid","Comprehensive guitar chord finder and library app for iOS.","https://apps.apple.com/us/app/chord/id912394374",4.6,534),
    _p("Capo","capo-app","SuperMegaUltraGroovy","midi","$19","paid","Song learning app for Mac that detects chords and slows down music.","https://supermegaultragroovy.com/products/capo/",4.5,312),
    _p("Transcribe!","transcribe-app","Seventh String","midi","$39","paid","Software tool to help musicians learn music by ear with slow-down and loop.","https://www.seventhstring.com/xscribe/overview.html",4.5,423),
    _p("Amazing Slow Downer","amazing-slow-downer","Risebird","midi","$49","paid","Audio slow-downer for practicing music with pitch preservation.","https://www.risebird.com/",4.5,312),

    # ─── STEM SEPARATION / AI TOOLS ──────────────────────────────────────────
    _p("Spleeter","spleeter-deezer","Deezer","utility","Free","free","Open-source AI audio source separation tool for splitting stems.","https://github.com/deezer/spleeter",4.5,923),
    _p("Moises App","moises-app","Moises AI","utility","Subscription","subscription","AI-powered music practice app with stem separation and pitch detection.","https://moises.ai/",4.6,712),
    _p("lalal.ai","lalal-ai","LALAL.AI","utility","Subscription","subscription","AI stem splitter for separating vocals, drums, bass, and instruments.","https://www.lalal.ai/",4.5,534),
    _p("Demucs","demucs-meta","Meta AI Research","utility","Free","free","Open-source music source separation model from Meta AI Research.","https://github.com/facebookresearch/demucs",4.6,534),
    _p("Splitter.ai","splitter-ai","Splitter.ai","utility","Subscription","subscription","Web-based stem splitter using neural network separation technology.","https://www.splitter.ai/",4.4,345),
    _p("LANDR AI Mastering","landr-ai-mastering","LANDR","mastering","Subscription","subscription","Online AI-powered mastering service with instant delivery.","https://www.landr.com/",4.4,712),
    _p("CloudBounce","cloudbounce","CloudBounce","mastering","Subscription","subscription","Automated online mastering service using machine learning.","https://cloudbounce.com/",4.3,312),
    _p("eMastered","emastered","eMastered","mastering","Subscription","subscription","Grammy-winning engineer-trained AI mastering platform.","https://emastered.com/",4.4,345),
    _p("Bandlab Mastering","bandlab-mastering","BandLab","mastering","Free","free","Free cloud-based mastering tool built into the BandLab platform.","https://www.bandlab.com/mastering",4.2,534),

    # ─── RECORDING / INTERFACE SOFTWARE ──────────────────────────────────────
    _p("Universal Control","ua-universal-control","Universal Audio","utility","Free","free","Free driver and control software for Universal Audio Apollo interfaces.","https://www.uaudio.com/universal-audio-software/universal-control.html",4.5,712),
    _p("Apollo Console","ua-apollo-console","Universal Audio","utility","Free","free","Free real-time UAD plugin monitoring for Apollo audio interfaces.","https://www.uaudio.com/",4.7,534),
    _p("Focusrite Control","focusrite-control","Focusrite","utility","Free","free","Free mixing and routing software for Focusrite Scarlett and Clarett interfaces.","https://focusrite.com/downloads/focusrite-control",4.5,823),
    _p("PreSonus UC Surface","presonus-uc-surface","PreSonus","utility","Free","free","Free touch-optimized control surface software for PreSonus StudioLive mixers.","https://www.presonus.com/learn/technical-articles/UC-Surface",4.5,312),
    _p("MOTU AVB Discovery","motu-avb-discovery","MOTU","utility","Free","free","Free network audio routing software for MOTU AVB interfaces.","https://motu.com/",4.4,189),
    _p("RME TotalMix FX","rme-totalmix-fx","RME","utility","Free","free","Free professional DSP mixer software bundled with RME audio interfaces.","https://www.rme-audio.de/totalmix-fx.html",4.8,534),
    _p("Audient EVO Control","audient-evo-control","Audient","utility","Free","free","Free control software for Audient EVO audio interfaces.","https://evo.audio/",4.5,267),
    _p("Apogee Control 2","apogee-control-2","Apogee Electronics","utility","Free","free","Free hardware control software for Apogee Symphony and Element interfaces.","https://apogeedigital.com/",4.5,312),
    _p("Native Access","native-access","Native Instruments","utility","Free","free","Free plugin management and installation software for NI products.","https://www.native-instruments.com/en/specials/native-access/",4.4,1234),
    _p("iLok License Manager","ilok-license-manager","PACE Anti-Piracy","utility","Free","free","Free license management software for iLok-protected plugins.","https://www.ilok.com/",4.2,1567),
    _p("Waves Central","waves-central","Waves","utility","Free","free","Free plugin management and installation hub for all Waves products.","https://www.waves.com/downloads/central",4.3,712),
    _p("Plugin Boutique Scaler 2 Free Trial","scaler-2-free","Plugin Boutique","midi","Free","free","Free trial version of Scaler 2 with limited functionality for evaluation.","https://www.pluginboutique.com/products/6439",4.5,345),

    # ─── STREAMING / DISTRIBUTION TOOLS ──────────────────────────────────────
    _p("Distrokid","distrokid","DistroKid","utility","Subscription","subscription","Music distribution platform for releasing to Spotify, Apple Music, and more.","https://distrokid.com/",4.5,1234),
    _p("TuneCore","tunecore","TuneCore","utility","Subscription","subscription","Digital music distribution service for independent artists.","https://www.tunecore.com/",4.4,834),
    _p("CD Baby","cd-baby","CD Baby","utility","$9","paid","Per-release music distribution to all major streaming platforms.","https://cdbaby.com/",4.3,712),
    _p("Amuse","amuse-distribution","Amuse","utility","Free","free","Free music distribution platform for independent artists.","https://amuse.io/",4.3,456),
    _p("UnitedMasters","unitedmasters","UnitedMasters","utility","Subscription","subscription","Music distribution with data insights for independent artists.","https://unitedmasters.com/",4.4,345),
    _p("Bandcamp","bandcamp","Bandcamp","utility","Free","free","Artist platform for selling music directly to fans with flexible pricing.","https://bandcamp.com/",4.7,1789),
    _p("SoundCloud Pro","soundcloud-pro","SoundCloud","utility","Subscription","subscription","Artist platform and streaming service with advanced analytics.","https://soundcloud.com/",4.3,1567),
    _p("Splice Studio","splice-studio","Splice","utility","Subscription","subscription","Cloud collaboration and version control platform for music producers.","https://splice.com/",4.5,923),

    # ─── AUDIO ANALYSIS / MASTERING UTILITIES ────────────────────────────────
    _p("MAnalyzer Spectrum Analyzer","manalyzer-melda","MeldaProduction","utility","Free","free","Free professional spectrum analyzer with peak and average display.","https://www.meldaproduction.com/MAnalyzer",4.6,456),
    _p("PSOLA","psola-plugin","Ircam","vocal","$99","paid","Advanced pitch and time manipulation using PSOLA algorithm for realism.","https://www.ircam.fr/",4.5,189),
    _p("iZotope Metering Pack","izotope-metering-pack","iZotope","utility","Free","free","Free loudness and true peak metering plugin from iZotope.","https://www.izotope.com/en/products/metering-pack.html",4.6,423),
    _p("TB EBU Loudness","tb-ebu-loudness","ToneBoosters","utility","$25","paid","Comprehensive EBU R128 loudness metering and correction plugin.","https://www.toneboosters.com/",4.7,312),
    _p("ToneBoosters EQ 4","toneboosters-eq-4","ToneBoosters","effects","$14","paid","Versatile parametric equalizer with spectrum analyzer and presets.","https://www.toneboosters.com/",4.6,345),
    _p("ToneBoosters Ferox","toneboosters-ferox","ToneBoosters","effects","$14","paid","Tape machine emulation with hysteresis, print-through, and saturation.","https://www.toneboosters.com/",4.6,289),
    _p("ToneBoosters Barricade 4","toneboosters-barricade-4","ToneBoosters","mastering","$25","paid","Professional brick-wall limiter with transparent processing.","https://www.toneboosters.com/",4.6,312),
    _p("ToneBoosters Reelbus 4","toneboosters-reelbus-4","ToneBoosters","effects","$14","paid","Tape recorder emulation with speed, saturation, and noise controls.","https://www.toneboosters.com/",4.5,267),
    _p("ToneBoosters Compressor 4","toneboosters-compressor-4","ToneBoosters","effects","$14","paid","Versatile compressor with vintage mode and visual feedback.","https://www.toneboosters.com/",4.5,289),
    _p("ToneBoosters Reverb 4","toneboosters-reverb-4","ToneBoosters","effects","$25","paid","High-quality algorithmic reverb with room, hall, and plate algorithms.","https://www.toneboosters.com/",4.6,312),
    _p("ToneBoosters Deficiency","toneboosters-deficiency","ToneBoosters","effects","$14","paid","Bitcrusher and sample rate reducer for vintage digital character.","https://www.toneboosters.com/",4.4,189),
    _p("ToneBoosters Siibilant","toneboosters-siibilant","ToneBoosters","vocal","$14","paid","Natural-sounding de-esser with split and wideband modes.","https://www.toneboosters.com/",4.5,234),

    # ─── WAVE EDITORS / AUDIO TOOLS ──────────────────thinking──────────────────────
    _p("iZotope RX Post Production Suite","izotope-rx-post-suite","iZotope","utility","$1999","paid","Complete post-production suite with RX, IRIS, Neutron, and more.","https://www.izotope.com/en/products/rx-post-production-suite.html",4.8,312),
    _p("Adobe Audition","adobe-audition","Adobe","daw","Subscription","subscription","Professional audio workstation for editing, mixing, and restoration.","https://www.adobe.com/products/audition.html",4.6,923),
    _p("Sound Forge Pro 16","sound-forge-pro-16","Magix","utility","$299","paid","Professional audio editing and mastering software for Windows.","https://www.magix.com/us/music-editing/sound-forge/sound-forge-pro/",4.5,445),
    _p("WaveLab Elements 12","wavelab-elements-12","Steinberg","mastering","$99","paid","Entry-level WaveLab for podcast editing and music mastering.","https://www.steinberg.net/wavelab/",4.6,312),
    _p("Fission","rogue-amoeba-fission","Rogue Amoeba","utility","$39","paid","Non-destructive audio editing for Mac with quick encode and trim tools.","https://rogueamoeba.com/fission/",4.5,345),
    _p("Hindenburg Journalist Pro","hindenburg-journalist-pro","Hindenburg Systems","utility","$375","paid","Professional audio editor for podcasters and radio journalists.","https://hindenburg.com/",4.6,234),
    _p("Descript","descript-app","Descript","utility","Subscription","subscription","AI-powered audio/video editor that edits media by editing transcript.","https://www.descript.com/",4.6,712),
    _p("Otter.ai","otter-ai","Otter.ai","utility","Subscription","subscription","AI meeting transcription and note-taking service for podcasters.","https://otter.ai/",4.3,534),

    # ─── PODCAST TOOLS ────────────────────────────────────────────────────────
    _p("Auphonic","auphonic","Auphonic","mastering","Subscription","subscription","Automatic audio post-production and podcast mastering service.","https://auphonic.com/",4.6,534),
    _p("Cleanfeed","cleanfeed","Cleanfeed","utility","Subscription","subscription","Browser-based studio-quality remote recording for podcasts and radio.","https://cleanfeed.net/",4.6,312),
    _p("Riverside.fm","riverside-fm","Riverside.fm","utility","Subscription","subscription","High-quality remote podcast and video recording with local files.","https://riverside.fm/",4.6,423),
    _p("Squadcast","squadcast","Squadcast","utility","Subscription","subscription","Remote podcast recording platform with cloud backup.","https://squadcast.fm/",4.5,312),
    _p("Zencastr","zencastr","Zencastr","utility","Subscription","subscription","Remote recording platform for podcasts with local audio capture.","https://zencastr.com/",4.4,267),
    _p("Buzzsprout","buzzsprout","Buzzsprout","utility","Subscription","subscription","Podcast hosting platform with analytics and distribution.","https://www.buzzsprout.com/",4.5,456),
    _p("Capsho","capsho","Capsho","utility","Subscription","subscription","AI-powered podcast content repurposing and show note generator.","https://www.capsho.com/",4.3,189),

    # ─── HARDWARE SYNTHS COMPANION SOFTWARE ───────────────────────────────────
    _p("Moog Sound Studio","moog-sound-studio","Moog","utility","Free","free","Free companion software for Mother-32 and DFAM hardware synthesizers.","https://www.moogmusic.com/",4.4,234),
    _p("Nord Sound Manager","nord-sound-manager","Nord","utility","Free","free","Free preset manager and firmware updater for Nord hardware instruments.","https://www.nordkeyboards.com/software-tools/nord-sound-manager",4.5,423),
    _p("Korg Kontrol Editor","korg-kontrol-editor","Korg","utility","Free","free","Free MIDI controller editor for Korg nanoSERIES controllers.","https://www.korg.com/",4.3,312),
    _p("Arturia MIDI Control Center","arturia-midi-control-center","Arturia","utility","Free","free","Free editor and firmware manager for Arturia hardware controllers.","https://www.arturia.com/products/software/midicontrolcenter",4.5,534),
    _p("Native Instruments Komplete Kontrol","ni-komplete-kontrol","Native Instruments","utility","Free","free","Free plugin browsing and hardware keyboard integration software.","https://www.native-instruments.com/en/products/komplete/keyboards/komplete-kontrol-s61-mk2/",4.6,634),
    _p("Ableton Link","ableton-link","Ableton","utility","Free","free","Free protocol for synchronizing music software over a local network.","https://www.ableton.com/en/link/",4.7,712),
    _p("TouchOSC","touchosc","Hexler","midi","$19","paid","Custom control surface builder for iOS, Android, and desktop with OSC/MIDI.","https://hexler.net/touchosc",4.7,712),
    _p("Lemur","lemur-liine","Liine","midi","$49","paid","Advanced multi-touch MIDI and OSC controller builder for iPad.","https://liine.net/en/products/lemur/",4.6,423),

    # ─── MIXING / COLLAB ──────────────────────────────────────────────────────
    _p("Splice Bridge","splice-bridge","Splice","utility","Subscription","subscription","Cloud-based DAW sync and backup for Ableton, FL Studio, and more.","https://splice.com/studio",4.4,345),
    _p("Blend","blend-music","Blend.io","utility","Free","free","Cloud collaboration platform for music producers to share projects.","https://blend.io/",4.3,234),
    _p("Tracklib","tracklib","Tracklib","sampler","Subscription","subscription","Sample licensing platform with original recordings from major labels.","https://www.tracklib.com/",4.6,534),
    _p("WhoSampled","whosampled","WhoSampled","utility","Free","free","Music sample discovery database tracing samples across generations.","https://www.whosampled.com/",4.5,712),
    _p("Crate Digger","crate-digger","N/A","utility","Free","free","Community database for tracking music samples and influences.","https://www.whosampled.com/",4.4,312),

    # ─── EXTRA GUITAR TOOLS ───────────────────────────────────────────────────
    _p("Amplitube Jimi Hendrix","ik-amplitube-hendrix","IK Multimedia","guitar","$99","paid","Official Jimi Hendrix gear collection with authorized amp and pedal models.","https://www.ikmultimedia.com/products/amphendrix/",4.7,423),
    _p("AmpliTube Leslie","ik-amplitube-leslie","IK Multimedia","guitar","$79","paid","Official Hammond Leslie cabinet simulation plugin with rotary speaker modeling.","https://www.ikmultimedia.com/products/atleslie/",4.7,312),
    _p("AmpliTube Orange","ik-amplitube-orange","IK Multimedia","guitar","$79","paid","Official Orange Amplification collection with Thunderverb and Rockerverb models.","https://www.ikmultimedia.com/products/atorange/",4.7,345),
    _p("AmpliTube Mesa/Boogie","ik-amplitube-mesa","IK Multimedia","guitar","$99","paid","Official Mesa/Boogie collection including Mark V, Dual Rectifier, and more.","https://www.ikmultimedia.com/products/atmesaboogie/",4.8,534),
    _p("Neural DSP Archetype Cory Wong","ndsp-archetype-cory-wong-v2","Neural DSP","guitar","$99","paid","Extended clean and funky guitar rig from Cory Wong with new amp models.","https://neuraldsp.com/plugins/archetype-cory-wong",4.7,345),
    _p("Bogren Digital KPA Capture","bogren-kpa-capture","Bogren Digital","guitar","$49","paid","Kemper-compatible amp profile importer for use in DAW environments.","https://bogrendigital.com/",4.5,234),
    _p("STL ToneHub","stl-tonehub","STL Tones","guitar","Subscription","subscription","High-quality amp sim subscription with profiles from top touring bands.","https://stltones.com/",4.7,534),
    _p("STL NadIR","stl-nadir","STL Tones","guitar","Free","free","Free dual impulse response loader for guitar cabinet simulation.","https://stltones.com/",4.6,712),
    _p("ML Sound Lab Mega Bundle","ml-sound-lab-mega","ML Sound Lab","guitar","$99","paid","Hundreds of guitar cabinet impulse responses from vintage and modern cabs.","https://mlsoundlab.com/",4.7,423),
    _p("OH! Guitar","oh-guitar-plugin","ML Sound Lab","guitar","$79","paid","Guitar amp sim with advanced DI, tone, and cab simulation.","https://mlsoundlab.com/",4.6,312),
    _p("Deplike Guitar Amp","deplike-guitar-amp","Deplike","guitar","Subscription","subscription","Mobile-focused guitar amp simulator for iOS and Android.","https://deplike.com/",4.4,345),
    _p("GuitarTuna","guitartuna","Yousician","utility","Free","free","Popular free guitar tuner app with chord library for iOS and Android.","https://yousician.com/guitartuna",4.6,2000),
    _p("Fender Tone","fender-tone-app","Fender","guitar","Free","free","Free app companion for Fender Mustang GTX and Tone Master Pro amplifiers.","https://www.fender.com/en-US/fender-tone/",4.4,534),
    _p("Boss Tone Studio","boss-tone-studio","Boss","guitar","Free","free","Free editor software for Boss GT and Katana amplifiers.","https://www.boss.info/global/products/gt-1000/",4.5,423),

    # ─── BASS TOOLS ───────────────────────────────────────────────────────────
    _p("Ampeg SVX","ampeg-svx","IK Multimedia","guitar","$49","paid","Ampeg bass amplifier and cabinet simulator plugin with 7 classic amps.","https://www.ikmultimedia.com/products/ampeg/",4.6,423),
    _p("Tech 21 SansAmp Plug-In","tech21-sansamp-plugin","Tech 21","guitar","$49","paid","SansAmp bass DI and preamp simulation plugin for authentic studio bass tones.","https://www.tech21nyc.com/",4.6,312),
    _p("Darkglass Suite","darkglass-suite","Darkglass Electronics","guitar","$79","paid","Darkglass bass overdrive, preamp, and cabinet simulation suite.","https://www.darkglass.com/",4.7,423),
    _p("EBS MultiComp Blue Label","ebs-multicomp-blue","EBS","guitar","$49","paid","3-mode bass compressor plugin modeled on EBS classic hardware.","https://ebssweden.com/",4.5,267),

    # ─── MORE DRUMS / PERCUSSION ──────────────────────────────────────────────
    _p("DrumBrute Impact","arturia-drumbrute-impact-sw","Arturia","drums","$49","paid","Analog drum machine plugin inspired by the Arturia DrumBrute Impact hardware.","https://www.arturia.com/products/hardware-synths/drumbrute-impact/overview",4.6,312),
    _p("Arturia Spark 2","arturia-spark-2","Arturia","drums","$99","paid","Virtual drum machine plugin with analog modeling and step sequencer.","https://www.arturia.com/products/software-instruments/spark-2/overview",4.5,345),
    _p("Groove Agent 5","steinberg-groove-agent-5","Steinberg","drums","$149","paid","Beat production plugin with acoustic and electronic drum kits and patterns.","https://www.steinberg.net/groove-agent/",4.7,534),
    _p("Addictive Drums 2 Complete","addictive-drums-2-complete","XLN Audio","drums","$399","paid","Full bundle of Addictive Drums 2 with all expansion packs included.","https://www.xlnaudio.com/products/addictive_drums_2",4.8,712),
    _p("EZX Pop Rock","ezx-pop-rock-2","Toontrack","drums","$49","paid","Pop rock drum expansion with clean, punchy sounds for mainstream music.","https://www.toontrack.com/product/pop-rock-ezx/",4.6,312),
    _p("EZX Country","ezx-country","Toontrack","drums","$49","paid","Country and Americana drum expansion with shuffles and brushwork.","https://www.toontrack.com/product/country-ezx/",4.6,267),
    _p("EZX Roots No 1","ezx-roots-no-1","Toontrack","drums","$49","paid","Blues, rock, and country roots drum expansion with vintage character.","https://www.toontrack.com/product/roots-no-1-ezx/",4.6,289),
    _p("EZX Dream Pop","ezx-dream-pop","Toontrack","drums","$49","paid","Modern indie and dream pop drum expansion with washy cymbals and reverb.","https://www.toontrack.com/product/dream-pop-ezx/",4.6,312),
    _p("EZX Studio Rock","ezx-studio-rock","Toontrack","drums","$49","paid","Classic studio rock drum sounds with aggressive punch and room character.","https://www.toontrack.com/product/studio-rock-ezx/",4.7,345),
    _p("Toontrack Drum Essentials","toontrack-drum-essentials","Toontrack","drums","$49","paid","Versatile cross-genre drum expansion covering rock, pop, and R&B.","https://www.toontrack.com/",4.6,289),
    _p("GetGood Drums P4 Bundle","ggd-p4-bundle","GetGood Drums","drums","$149","paid","Complete GetGood Drums bundle with all expansion packs.","https://www.getgooddrums.com/",4.7,423),
    _p("Room Sound Vintage Snares","room-sound-vintage-snares","Room Sound","drums","$49","paid","Classic vintage snare drum samples from 1950s through 1980s recording eras.","https://www.roomsound.com/",4.5,234),
    _p("Sampled! Vintage Drums","sampled-vintage-drums","Sampled!","drums","$49","paid","Vintage 1960s and 1970s drum kit samples with authentic room character.","https://www.sampledreal.com/",4.5,245),
    _p("Drumforge DF-One","drumforge-df-one","Drumforge","drums","$49","paid","Modern metal and rock drum library with multiple mic positions.","https://www.drumforge.com/",4.6,312),
    _p("Slate Digital ANA 2","slate-digital-ana-2","Slate Digital","synth","$99","paid","Modern polyphonic synthesizer with wavetable, sample, and analog oscillators.","https://slatedigital.com/ana-2/",4.6,423),

    # ─── MODULAR / EURORACK ───────────────────────────────────────────────────
    _p("VCV Rack 2 Pro","vcv-rack-2-pro","VCV","synth","$99","paid","Virtual Eurorack modular synthesizer with VST/AU plugin hosting.","https://vcvrack.com/",4.8,923),
    _p("VCV Rack 2 Free","vcv-rack-2-free","VCV","synth","Free","free","Free open-source virtual Eurorack modular synthesizer platform.","https://vcvrack.com/",4.8,1456),
    _p("Softube Modular","softube-modular","Softube","synth","$99","paid","Virtual modular synthesizer featuring official Doepfer module emulations.","https://www.softube.com/modular",4.7,534),
    _p("Vcvrack Befaco Bundle","vcvrack-befaco","Befaco","synth","Free","free","Free official Befaco hardware module emulations for VCV Rack.","https://library.vcvrack.com/",4.6,345),
    _p("Reaktor Blocks","reaktor-blocks","Native Instruments","synth","Included with Reaktor 6","paid","Pre-built modular blocks for rapid patch creation in Reaktor 6.","https://www.native-instruments.com/en/products/komplete/synths/reaktor-6/",4.7,423),
    _p("Cardinal","cardinal-vst","DISTRHO","synth","Free","free","Free open-source virtual modular synthesizer based on VCV Rack engine.","https://github.com/DISTRHO/Cardinal",4.6,312),

    # ─── BROADCAST / LIVE SOUND ──────────────────────────────────────────────
    _p("dbx DriveRack","dbx-driverack","dbx Professional","utility","$99","paid","Speaker management and loudspeaker optimization software.","https://dbxpro.com/en-US/products/driverack-pa2",4.5,234),
    _p("Lectrosonics Remote","lectrosonics-remote","Lectrosonics","utility","Free","free","Free wireless system control software for Lectrosonics transmitters.","https://www.lectrosonics.com/",4.4,156),
    _p("Dante Virtual Soundcard","dante-virtual-soundcard","Audinate","utility","$99","paid","Dante protocol audio networking software for studio and live use.","https://www.audinate.com/products/software/dante-virtual-soundcard",4.7,312),
    _p("Dante Controller","dante-controller","Audinate","utility","Free","free","Free software for routing Dante audio across network-connected devices.","https://www.audinate.com/products/software/dante-controller",4.6,423),
    _p("REAPER SWS Extension","reaper-sws","SWS Team","utility","Free","free","Free REAPER extension pack with hundreds of additional features.","https://www.sws-extension.org/",4.8,712),
    _p("Studio One Remote","studio-one-remote","PreSonus","utility","Free","free","Free iPad remote control app for PreSonus Studio One DAW.","https://www.presonus.com/products/Studio-One-Remote",4.5,312),
    _p("Logic Remote","logic-remote","Apple","utility","Free","free","Free iPad/iPhone control surface for Logic Pro and GarageBand.","https://apps.apple.com/us/app/logic-remote/id638394624",4.6,712),
    _p("Pro Tools Carbon","pro-tools-carbon","Avid","utility","$2999","paid","Hybrid audio interface with built-in DSP for Pro Tools HDX workflow.","https://www.avid.com/interfaces/pro-tools-carbon",4.7,189),

    # ─── EXTRA EFFECTS PLUGINS ────────────────────────────────────────────────
    _p("Arturia EFX FRAGMENTS","arturia-efx-fragments-2","Arturia","experimental","$99","paid","Granular delay and spectral fragmentation plugin for unique sound design.","https://www.arturia.com/products/software-effects/efx-fragments/overview",4.6,234),
    _p("Strymon BigSky Plugin","strymon-bigsky-plugin","Strymon","effects","$149","paid","Software version of the legendary Strymon BigSky reverb pedal.","https://www.strymon.net/",4.8,534),
    _p("Strymon Timeline Plugin","strymon-timeline-plugin","Strymon","effects","$149","paid","Software version of the Strymon Timeline delay with 12 delay types.","https://www.strymon.net/",4.8,456),
    _p("Empress Reverb Plugin","empress-reverb-plugin","Empress Effects","effects","$79","paid","Software version of the Empress Reverb with 12 reverb modes.","https://empresseffects.com/",4.6,267),
    _p("Chase Bliss Mood","chase-bliss-mood-plugin","Chase Bliss Audio","experimental","$49","paid","Software companion to the Chase Bliss Mood micro-looper pedal.","https://www.chaseblissaudio.com/",4.5,234),
    _p("EarthQuaker Afterneath Enhanced","earthquaker-afterneath","EarthQuaker Devices","effects","$79","paid","Other-worldly reverb plugin based on the EQD Afterneath pedal.","https://www.earthquakerdevices.com/",4.7,345),
    _p("UAFX Capitol Chambers","uafx-capitol-chambers","Universal Audio","effects","$199","paid","Hardware/software hybrid echo chambers inspired by Capitol Studios.","https://www.uaudio.com/",4.8,312),
    _p("Eventide H3000 Band Delays","eventide-h3000-band-delays","Eventide","effects","$99","paid","Classic H3000 band delay algorithm recreating the signature Eventide effect.","https://www.eventideaudio.com/",4.7,312),
    _p("Eventide UltraTap","eventide-ultratap","Eventide","effects","$99","paid","Multi-tap delay plugin with up to 64 taps and tape-style manipulation.","https://www.eventideaudio.com/signal-processing/ultratap/",4.7,345),
    _p("Echoboy Jr.","soundtoys-echoboy-jr","SoundToys","effects","$49","paid","Simplified version of EchoBoy with 3 delay styles and core controls.","https://www.soundtoys.com/product/echoboy-jr/",4.6,423),
    _p("Soundtoys Effectrix","soundtoys-effectrix","SoundToys","effects","$99","paid","Step-based effects sequencer with 14 effect types in a rhythmic grid.","https://www.soundtoys.com/product/soundtoys-5/",4.7,534),
    _p("Valhalla VintageVerb (Free Trial)","valhalla-vintageverb-trial","Valhalla DSP","effects","Free","free","Free 30-day trial of the classic Valhalla VintageVerb reverb plugin.","https://valhalladsp.com/",4.8,423),
    _p("Kush Audio UBK Fatso Jr","kush-fatso-jr","Kush Audio","effects","$149","paid","Tape saturation and harmonic enhancer plugin for warmth and glue.","https://www.kush.audio/",4.7,267),
    _p("Kush Clariphonic Parallel EQ","kush-clariphonic","Kush Audio","effects","$149","paid","Parallel high-frequency shelving EQ for air and shimmer enhancement.","https://www.kush.audio/products/clariphonic",4.7,345),
    _p("Crane Song Phoenix II","crane-song-phoenix-ii","Crane Song","effects","$99","paid","Tape saturation plugin with 5 modes from subtle warmth to extreme color.","https://www.cranesong.com/",4.7,312),
    _p("Empirical Labs Lil FrEQ","empirical-labs-lil-freq","Empirical Labs","effects","$149","paid","Classic EQ plugin emulating the Lil' FreQ hardware unit.","https://www.empiricallabs.com/",4.6,267),
    _p("Dream Suite by Pete Townshend","waves-pete-townshend","Waves","effects","$49","paid","Guitar effects suite designed with The Who's Pete Townshend.","https://www.waves.com/plugins",4.4,189),
    _p("Purple Audio MC77","purple-audio-mc77","Purple Audio","effects","$49","paid","1176-style FET compressor emulation from Purple Audio.","https://purpleaudio.com/",4.6,234),
    _p("Shadow Hills Mastering Comp Class A","shadow-hills-class-a","Shadow Hills","mastering","$299","paid","Class A mode of the Shadow Hills mastering compressor for warm processing.","https://shadowhillsindustries.com/",4.8,312),

    # ─── MORE SYNTHS ──────────────────────────────────────────────────────────
    _p("Pigments 5","arturia-pigments-5","Arturia","synth","$199","paid","Latest Arturia Pigments with updated wavetable, sampling, and granular engines.","https://www.arturia.com/products/software-instruments/pigments/overview",4.9,712),
    _p("Xfer Cthulhu","xfer-cthulhu","Xfer Records","midi","$40","paid","Chord and arpeggio generator for transforming single notes into rich patterns.","https://xferrecords.com/products/cthulhu",4.7,923),
    _p("Surge XT FX","surge-xt-fx","Surge Synth Team","effects","Free","free","Free standalone effects processor using Surge XT's modulation and FX engine.","https://surge-synthesizer.github.io/",4.7,534),
    _p("Vital Plus","vital-plus","Vital Audio","synth","$25","paid","Extended Vital subscription with expanded wavetable library and Patreon content.","https://vital.audio/",4.8,712),
    _p("Podolski 2","podolski-2","u-he","synth","Free","free","Updated free version of Podolski with improved oscillator and filter quality.","https://u-he.com/products/podolski/",4.5,423),
    _p("Helm Plus","helm-plus","Matt Tytel","synth","$15","paid","Expanded Helm with extra presets and updated oscillator algorithms.","https://tytel.org/helm/",4.6,312),
    _p("Amsynth","amsynth","Nick Dowell","synth","Free","free","Free open-source analog synthesizer for Linux and macOS.","https://amsynth.github.io/",4.2,234),
    _p("ZynAddSubFX","zynaddsubfx","Mark McCurry","synth","Free","free","Free open-source additive/subtractive synthesizer with complex modulation.","https://zynaddsubfx.sourceforge.io/",4.3,456),
    _p("Hive 2.2","u-he-hive-2-2","u-he","synth","$149","paid","Updated Hive 2 with additional wavetables and improved modulation system.","https://u-he.com/products/hive/",4.7,534),
    _p("Rob Papen GO2","rob-papen-go2","Rob Papen","synth","$39","paid","Simple and immediate synthesizer perfect for quick sound design.","https://www.robpapen.com/go2.html",4.5,267),
    _p("Rob Papen Quad","rob-papen-quad","Rob Papen","synth","$99","paid","4-part multitimbral synthesizer with sequencer and complex modulation.","https://www.robpapen.com/quad.html",4.5,289),
    _p("GForce impOSCar2","gforce-imposcar2","GForce Software","synth","$99","paid","OSCar synthesizer emulation with authentic dual-oscillator character.","https://www.gforcesoftware.com/products/imposcar2/",4.7,345),
    _p("GForce Oberheim SEM","gforce-oberheim-sem","GForce Software","synth","$99","paid","Authentic Oberheim SEM synthesizer emulation from GForce.","https://www.gforcesoftware.com/products/oberheim-sem/",4.7,312),
    _p("GForce Minimonsta 2","gforce-minimonsta-2","GForce Software","synth","$99","paid","Minimoog Model D synthesizer emulation with extended modulation.","https://www.gforcesoftware.com/products/minimonsta/",4.7,289),
    _p("GForce Virtual String Machine","gforce-virtual-string-machine","GForce Software","synth","$49","paid","Classic string machine emulation covering Solina and Eminent organs.","https://www.gforcesoftware.com/products/vsm/",4.6,267),
    _p("GForce M-Tron Pro","gforce-m-tron-pro","GForce Software","sampler","$99","paid","Definitive Mellotron emulation with extensive tape library.","https://www.gforcesoftware.com/products/m-tron-pro/",4.7,423),
    _p("Sampleson Analog Rack","sampleson-analog-rack","Sampleson","synth","$49","paid","Virtual analog synthesizer with physical modeling oscillators.","https://sampleson.com/",4.5,189),
    _p("AudioThing Wires","audiothing-wires","AudioThing","experimental","$39","paid","Vintage wire recorder emulation with warble, distortion, and hiss.","https://www.audiothing.net/effects/wires/",4.6,312),
    _p("AudioThing Valves","audiothing-valves","AudioThing","effects","$39","paid","Tube preamp emulation inspired by vintage valve hardware.","https://www.audiothing.net/effects/valves/",4.5,267),
    _p("AudioThing Outer Space","audiothing-outer-space","AudioThing","effects","$49","paid","Roland RE-201 Space Echo emulation with spring reverb simulation.","https://www.audiothing.net/effects/outer-space/",4.7,423),
    _p("AudioThing Springs","audiothing-springs","AudioThing","effects","$39","paid","Spring reverb emulation modeled on three vintage tank reverb units.","https://www.audiothing.net/effects/springs/",4.6,345),
    _p("AudioThing Frostbite 2","audiothing-frostbite-2","AudioThing","experimental","$39","paid","Granular freeze and texture creation plugin for ambient processing.","https://www.audiothing.net/effects/frostbite-2/",4.6,289),
    _p("AudioThing Fog Convolver","audiothing-fog-convolver","AudioThing","effects","$39","paid","Convolution processor with creative impulse response manipulation.","https://www.audiothing.net/effects/fog-convolver/",4.5,234),

    # ─── MORE VOCAL TOOLS ─────────────────────────────────────────────────────
    _p("Synchro Arts RePitch","synchro-arts-repitch","Synchro Arts","vocal","$299","paid","ARA-integrated pitch editor for natural-sounding vocal pitch correction.","https://www.synchroarts.com/products/repitch/overview",4.7,312),
    _p("Celemony Melodyne 5 Bundle","celemony-melodyne-5-bundle","Celemony","vocal","$999","paid","Complete Melodyne bundle with all features including polyphonic DNA.","https://www.celemony.com/en/melodyne/editions",4.9,534),
    _p("Auto-Tune Unlimited","antares-auto-tune-unlimited","Antares Audio","vocal","Subscription","subscription","All-access Antares subscription with Auto-Tune Pro and all vocal tools.","https://www.antarestech.com/product/auto-tune-unlimited/",4.7,423),
    _p("Nectar 4 Advanced","izotope-nectar-4-advanced","iZotope","vocal","$399","paid","Full iZotope vocal production suite with AI Vocal Assistant and stem separation.","https://www.izotope.com/en/products/nectar.html",4.8,345),
    _p("Waves Vocal Bundle","waves-vocal-bundle","Waves","vocal","$99","paid","Collection of Waves vocal plugins including Tune, Rider, and OVox.","https://www.waves.com/bundles/vocal-bundle",4.6,423),
    _p("Zynaptiq Wormhole","zynaptiq-wormhole","Zynaptiq","experimental","$149","paid","Neural convolution reverb creating unique, organic-sounding spaces.","https://www.zynaptiq.com/wormhole/",4.7,267),
    _p("Zynaptiq Orange Vocoder III","zynaptiq-orange-vocoder","Zynaptiq","vocal","$99","paid","Classic vocoder emulation with 3 carrier modes and modern improvements.","https://www.zynaptiq.com/orangevocoder/",4.6,234),
]
