PRODUCTS = [
    # --- Toontrack ---
    {
        "name": "Superior Drummer 3",
        "slug": "superior-drummer-3",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$399",
        "priceType": "paid",
        "description": "Industry-leading drum production software with over 230 GB of samples recorded at Spotify Studios NYC. Features a powerful mixing environment and macro controls for fast sound shaping.",
        "url": "https://www.toontrack.com/product/superior-drummer-3/",
        "rating": 4.9,
        "ratingCount": 1850,
    },
    {
        "name": "EZdrummer 3",
        "slug": "ezdrummer-3",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$179",
        "priceType": "paid",
        "description": "Toontrack's third-generation entry-level drum plugin with a built-in song creator, smart browser, and an expressive mixer. Ideal for songwriters who want fast, professional drum tracks.",
        "url": "https://www.toontrack.com/product/ezdrummer-3/",
        "rating": 4.8,
        "ratingCount": 1620,
    },
    {
        "name": "EZdrummer 2",
        "slug": "ezdrummer-2",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "The predecessor to EZdrummer 3, offering an intuitive drag-and-drop MIDI groove library and an easy-to-use mixer. Still widely used by home producers for quick drum production.",
        "url": "https://www.toontrack.com/product/ezdrummer-2/",
        "rating": 4.7,
        "ratingCount": 1480,
    },
    {
        "name": "EZbass",
        "slug": "ezbass",
        "developer": "Toontrack",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A dedicated bass instrument plugin from Toontrack featuring authentic bass guitar samples and a smart MIDI library. Integrates seamlessly with EZdrummer 3 for complete rhythm-section production.",
        "url": "https://www.toontrack.com/product/ezbass/",
        "rating": 4.6,
        "ratingCount": 870,
    },
    {
        "name": "EZkeys",
        "slug": "ezkeys",
        "developer": "Toontrack",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A piano and keyboard instrument plugin with a built-in chord and song generator. Includes a comprehensive MIDI library organized by genre and mood.",
        "url": "https://www.toontrack.com/product/ezkeys/",
        "rating": 4.6,
        "ratingCount": 790,
    },
    {
        "name": "EZmix 2",
        "slug": "ezmix-2",
        "developer": "Toontrack",
        "category": "effects",
        "price": "$99",
        "priceType": "paid",
        "description": "A signal processing plugin with hundreds of presets for guitars, bass, drums, and vocals. Designed for fast, professional mixing without deep technical knowledge.",
        "url": "https://www.toontrack.com/product/ezmix-2/",
        "rating": 4.4,
        "ratingCount": 640,
    },
    {
        "name": "EZmix Grand Piano",
        "slug": "ezmix-grand-piano",
        "developer": "Toontrack",
        "category": "effects",
        "price": "$29",
        "priceType": "paid",
        "description": "An EZmix 2 expansion pack delivering a curated set of mixing chains tailored specifically for grand piano recordings. Quickly adds warmth and presence to any piano track.",
        "url": "https://www.toontrack.com/product/ezmix-grand-piano/",
        "rating": 4.3,
        "ratingCount": 220,
    },
    {
        "name": "Metal Machine SDX",
        "slug": "metal-machine-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion capturing aggressive metal drum tones recorded at Cove City Sound Studios. Includes multiple velocity layers and mix-ready presets for heavy music.",
        "url": "https://www.toontrack.com/product/metal-machine-sdx/",
        "rating": 4.7,
        "ratingCount": 540,
    },
    {
        "name": "The Metal Foundry SDX",
        "slug": "the-metal-foundry-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A landmark Superior Drummer expansion recorded specifically for extreme metal production with multiple room configurations and cymbal variations. Essential for modern metal producers.",
        "url": "https://www.toontrack.com/product/the-metal-foundry-sdx/",
        "rating": 4.8,
        "ratingCount": 610,
    },
    {
        "name": "The Rock Warehouse SDX",
        "slug": "the-rock-warehouse-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion recorded in a massive warehouse space to capture massive rock drum sounds with natural ambience. Includes multiple kit configurations.",
        "url": "https://www.toontrack.com/product/the-rock-warehouse-sdx/",
        "rating": 4.6,
        "ratingCount": 390,
    },
    {
        "name": "Nashville SDX",
        "slug": "nashville-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion recorded at the legendary Sound Emporium Studios in Nashville. Delivers the warm, polished drum sounds characteristic of country and Americana production.",
        "url": "https://www.toontrack.com/product/nashville-sdx/",
        "rating": 4.5,
        "ratingCount": 310,
    },
    {
        "name": "New York Studios Legacy SDX",
        "slug": "new-york-studios-legacy-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "Captures the sound of legendary New York recording studios with four distinct room environments. A Superior Drummer 3 expansion beloved for its versatile rock and pop drum tones.",
        "url": "https://www.toontrack.com/product/new-york-studios-legacy-sdx/",
        "rating": 4.7,
        "ratingCount": 430,
    },
    {
        "name": "The Classic SDX",
        "slug": "the-classic-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion paying homage to vintage recording techniques with four classic drum kits and multiple microphone perspectives. Perfect for retro and classic rock production.",
        "url": "https://www.toontrack.com/product/the-classic-sdx/",
        "rating": 4.6,
        "ratingCount": 360,
    },
    {
        "name": "Roots SDX",
        "slug": "roots-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion focused on organic, roots-music drum sounds including brushes, rods, and mallets. Ideal for folk, Americana, and acoustic productions.",
        "url": "https://www.toontrack.com/product/roots-sdx/",
        "rating": 4.5,
        "ratingCount": 280,
    },
    {
        "name": "Jazz Noir SDX",
        "slug": "jazz-noir-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion capturing the intimate, moody sound of jazz drumming with brushes, rods, and specialty mallets. Recorded in a purpose-built jazz studio environment.",
        "url": "https://www.toontrack.com/product/jazz-noir-sdx/",
        "rating": 4.6,
        "ratingCount": 260,
    },
    {
        "name": "Death & Darkness SDX",
        "slug": "death-and-darkness-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion designed for death metal and black metal production with extreme low-end kick sounds and razor-sharp snare transients. Recorded with genre-specialist engineers.",
        "url": "https://www.toontrack.com/product/death-and-darkness-sdx/",
        "rating": 4.7,
        "ratingCount": 480,
    },
    {
        "name": "Rooms of Hansa SDX",
        "slug": "rooms-of-hansa-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "Recorded at the legendary Hansa Studios in Berlin, this Superior Drummer 3 expansion captures the iconic large-room drum sounds heard on countless classic rock records.",
        "url": "https://www.toontrack.com/product/rooms-of-hansa-sdx/",
        "rating": 4.8,
        "ratingCount": 520,
    },
    {
        "name": "Hitmaker SDX",
        "slug": "hitmaker-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion recorded at Sunset Sound in Los Angeles featuring classic studio drum kits favored by top session musicians. Delivers polished, commercial-ready tones.",
        "url": "https://www.toontrack.com/product/hitmaker-sdx/",
        "rating": 4.6,
        "ratingCount": 370,
    },
    {
        "name": "Mad Hatter Studio SDX",
        "slug": "mad-hatter-studio-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion recorded at Dave Grohl's 606 Studios, offering eclectic drum sounds suited to alternative, rock, and experimental production.",
        "url": "https://www.toontrack.com/product/mad-hatter-studio-sdx/",
        "rating": 4.6,
        "ratingCount": 410,
    },
    {
        "name": "Avatar SDX",
        "slug": "avatar-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "Recorded at Avatar Studios (now Power Station) in New York, this Superior Drummer 3 expansion captures world-class studio drum tones across multiple kit configurations.",
        "url": "https://www.toontrack.com/product/avatar-sdx/",
        "rating": 4.7,
        "ratingCount": 440,
    },
    {
        "name": "Decades SDX",
        "slug": "decades-sdx",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A Superior Drummer 3 expansion spanning six decades of drum kit history, from the 1950s to the 2000s. Perfect for period-accurate productions or unique vintage blends.",
        "url": "https://www.toontrack.com/product/decades-sdx/",
        "rating": 4.7,
        "ratingCount": 490,
    },
    {
        "name": "EZX Blues",
        "slug": "ezx-blues",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion delivering authentic blues drum sounds recorded with vintage gear and classic microphone techniques. Includes genre-specific MIDI grooves.",
        "url": "https://www.toontrack.com/product/ezx-blues/",
        "rating": 4.4,
        "ratingCount": 210,
    },
    {
        "name": "EZX Country",
        "slug": "ezx-country",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion offering crisp, punchy country drum sounds with a healthy selection of MIDI grooves in traditional and modern country styles.",
        "url": "https://www.toontrack.com/product/ezx-country/",
        "rating": 4.4,
        "ratingCount": 195,
    },
    {
        "name": "EZX Jazz",
        "slug": "ezx-jazz",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion featuring warm, nuanced jazz drum sounds recorded with brushes and rods alongside sticks. Comes with authentic swing and bop MIDI grooves.",
        "url": "https://www.toontrack.com/product/ezx-jazz/",
        "rating": 4.5,
        "ratingCount": 230,
    },
    {
        "name": "EZX Roots No 1",
        "slug": "ezx-roots-no-1",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion capturing organic, roots-music drum tones with a focus on warm acoustics and minimal processing. Ideal for folk, country, and acoustic singer-songwriter productions.",
        "url": "https://www.toontrack.com/product/ezx-roots-no-1/",
        "rating": 4.4,
        "ratingCount": 175,
    },
    {
        "name": "EZX Percussion",
        "slug": "ezx-percussion",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion dedicated to world and Latin percussion, including congas, bongos, shakers, and more. Adds rhythmic texture and groove to any production.",
        "url": "https://www.toontrack.com/product/ezx-percussion/",
        "rating": 4.4,
        "ratingCount": 200,
    },
    {
        "name": "EZX Pop Rock",
        "slug": "ezx-pop-rock",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion delivering polished, commercial pop-rock drum sounds with punchy transients and smooth room ambience. Suited for radio-ready productions.",
        "url": "https://www.toontrack.com/product/ezx-pop-rock/",
        "rating": 4.5,
        "ratingCount": 340,
    },
    {
        "name": "EZX Hip-Hop",
        "slug": "ezx-hip-hop",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion focusing on the hard-hitting, processed drum sounds of hip-hop and trap production. Includes lo-fi textures, snappy snares, and booming kick samples.",
        "url": "https://www.toontrack.com/product/ezx-hip-hop/",
        "rating": 4.5,
        "ratingCount": 290,
    },
    {
        "name": "EZX Vintage Rock",
        "slug": "ezx-vintage-rock",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion recreating the warm, slightly compressed drum sounds of classic 1960s and 70s rock recordings. Perfect for vintage-inspired productions.",
        "url": "https://www.toontrack.com/product/ezx-vintage-rock/",
        "rating": 4.5,
        "ratingCount": 265,
    },
    {
        "name": "EZX Studio Rock",
        "slug": "ezx-studio-rock",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion capturing tight, powerful studio rock drum sounds ideal for modern hard rock and alternative productions. Recorded with premium drum kits and outboard gear.",
        "url": "https://www.toontrack.com/product/ezx-studio-rock/",
        "rating": 4.5,
        "ratingCount": 300,
    },
    {
        "name": "EZX Dream Pop",
        "slug": "ezx-dream-pop",
        "developer": "Toontrack",
        "category": "drums",
        "price": "$59",
        "priceType": "paid",
        "description": "An EZdrummer expansion offering lush, ambient drum sounds with heavy reverb and subtle lo-fi textures. Designed for dream pop, shoegaze, and atmospheric indie production.",
        "url": "https://www.toontrack.com/product/ezx-dream-pop/",
        "rating": 4.4,
        "ratingCount": 185,
    },

    # --- XLN Audio ---
    {
        "name": "Addictive Drums 2",
        "slug": "addictive-drums-2",
        "developer": "XLN Audio",
        "category": "drums",
        "price": "$179",
        "priceType": "paid",
        "description": "A powerful and flexible drum plugin with an intuitive mixer, transient shaping, and a vast library of expansion kits. Renowned for its fast workflow and outstanding out-of-the-box sound.",
        "url": "https://www.xlnaudio.com/products/addictive_drums",
        "rating": 4.8,
        "ratingCount": 1750,
    },
    {
        "name": "Addictive Keys Studio Grand",
        "slug": "addictive-keys-studio-grand",
        "developer": "XLN Audio",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A meticulously sampled grand piano featuring a Steinway Model D recorded in a professional studio. Includes a built-in effects chain and intuitive controls for fast sound sculpting.",
        "url": "https://www.xlnaudio.com/products/addictive_keys/instrument/studio_grand",
        "rating": 4.7,
        "ratingCount": 680,
    },
    {
        "name": "Addictive Keys Modern Upright",
        "slug": "addictive-keys-modern-upright",
        "developer": "XLN Audio",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A characterful upright piano with a mid-century aesthetic, sampled with multiple microphone positions and effects options. Ideal for indie, pop, and cinematic productions.",
        "url": "https://www.xlnaudio.com/products/addictive_keys/instrument/modern_upright",
        "rating": 4.6,
        "ratingCount": 520,
    },
    {
        "name": "Addictive Keys Mark One",
        "slug": "addictive-keys-mark-one",
        "developer": "XLN Audio",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A meticulous recreation of the iconic Fender Rhodes Mark I electric piano, complete with authentic tine response and vintage amp emulations. A staple for soul, funk, and jazz productions.",
        "url": "https://www.xlnaudio.com/products/addictive_keys/instrument/mark_one",
        "rating": 4.7,
        "ratingCount": 730,
    },
    {
        "name": "Addictive Keys Vladiator",
        "slug": "addictive-keys-vladiator",
        "developer": "XLN Audio",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A faithful emulation of the rare Vladimir Kuzmin Soviet-era electric piano, offering unique metallic tones not found in mainstream keyboards. Perfect for experimental and lo-fi productions.",
        "url": "https://www.xlnaudio.com/products/addictive_keys/instrument/vladiator",
        "rating": 4.5,
        "ratingCount": 310,
    },
    {
        "name": "RC-20 Retro Color",
        "slug": "rc-20-retro-color",
        "developer": "XLN Audio",
        "category": "effects",
        "price": "$99",
        "priceType": "paid",
        "description": "A multi-effect plugin emulating the organic imperfections of vintage recording media including tape, vinyl, and lo-fi electronics. Adds instant character and warmth to any sound source.",
        "url": "https://www.xlnaudio.com/products/rc-20",
        "rating": 4.8,
        "ratingCount": 1420,
    },
    {
        "name": "RC-48 Reverb",
        "slug": "rc-48-reverb",
        "developer": "XLN Audio",
        "category": "effects",
        "price": "$99",
        "priceType": "paid",
        "description": "A vintage plate and hall reverb plugin modeled after classic studio hardware units. Features an intuitive interface and lush, musical reverb tails.",
        "url": "https://www.xlnaudio.com/products/rc-48",
        "rating": 4.6,
        "ratingCount": 560,
    },
    {
        "name": "RC-24 Reverb",
        "slug": "rc-24-reverb",
        "developer": "XLN Audio",
        "category": "effects",
        "price": "$99",
        "priceType": "paid",
        "description": "A lush algorithmic reverb plugin inspired by classic studio hardware with a focus on natural room and hall sounds. Includes an easy-to-use macro interface for fast dialing.",
        "url": "https://www.xlnaudio.com/products/rc-24",
        "rating": 4.6,
        "ratingCount": 490,
    },
    {
        "name": "XO",
        "slug": "xo-xln-audio",
        "developer": "XLN Audio",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "An AI-powered drum machine and sample explorer that maps your sample library into a visual space and intelligently groups similar sounds. Makes beat building intuitive and discovery-driven.",
        "url": "https://www.xlnaudio.com/products/xo",
        "rating": 4.7,
        "ratingCount": 890,
    },

    # --- BFD ---
    {
        "name": "BFD3",
        "slug": "bfd3",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$299",
        "priceType": "paid",
        "description": "A professional-grade acoustic drum software with an extensive library of multi-layer samples and a highly detailed mixer. Known for its deep sampling and expressive humanization features.",
        "url": "https://www.bfddrums.com/products/bfd3",
        "rating": 4.7,
        "ratingCount": 1120,
    },
    {
        "name": "BFD Eco",
        "slug": "bfd-eco",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$49",
        "priceType": "paid",
        "description": "A streamlined, entry-level version of BFD3 offering a curated selection of world-class drum samples at a lower price point. Great for producers who want BFD quality without the full suite.",
        "url": "https://www.bfddrums.com/products/bfd-eco",
        "rating": 4.4,
        "ratingCount": 430,
    },
    {
        "name": "BFD London Sessions",
        "slug": "bfd-london-sessions",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A BFD expansion recorded at iconic London studios featuring classic British drum kits and room sounds. Delivers the warm, characterful tones of vintage UK pop and rock recordings.",
        "url": "https://www.bfddrums.com/products/bfd-london-sessions",
        "rating": 4.6,
        "ratingCount": 290,
    },
    {
        "name": "BFD Jazz & Funk",
        "slug": "bfd-jazz-and-funk",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A BFD expansion delivering authentic jazz and funk drum kits recorded with period-correct microphone placements and vintage gear. Includes brushes, rods, and mallets.",
        "url": "https://www.bfddrums.com/products/bfd-jazz-funk",
        "rating": 4.5,
        "ratingCount": 260,
    },
    {
        "name": "BFD Crush & Tune",
        "slug": "bfd-crush-and-tune",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A BFD expansion focused on heavily processed and manipulated drum sounds including crushed, tuned, and pitch-shifted kits. Perfect for electronic, industrial, and experimental productions.",
        "url": "https://www.bfddrums.com/products/bfd-crush-tune",
        "rating": 4.4,
        "ratingCount": 195,
    },
    {
        "name": "BFD Maple Custom",
        "slug": "bfd-maple-custom",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A BFD expansion capturing a premium maple drum kit with multiple tuning options and microphone configurations. Delivers warm, open drum tones suited to a wide range of genres.",
        "url": "https://www.bfddrums.com/products/bfd-maple-custom",
        "rating": 4.5,
        "ratingCount": 220,
    },
    {
        "name": "BFD Nick Mason Signatures",
        "slug": "bfd-nick-mason-signatures",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A BFD expansion featuring the personal drum kits of Pink Floyd's Nick Mason, captured with detailed multi-layer sampling. Includes genre-specific grooves from Mason himself.",
        "url": "https://www.bfddrums.com/products/bfd-nick-mason-signatures",
        "rating": 4.6,
        "ratingCount": 330,
    },
    {
        "name": "BFD Modern Retro",
        "slug": "bfd-modern-retro",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A BFD expansion blending vintage drum aesthetics with modern recording techniques, offering a hybrid sound suited to indie, pop, and retro-influenced music.",
        "url": "https://www.bfddrums.com/products/bfd-modern-retro",
        "rating": 4.5,
        "ratingCount": 240,
    },
    {
        "name": "BFD Deluxe Kit Pieces",
        "slug": "bfd-deluxe-kit-pieces",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A BFD expansion adding premium individual drum and cymbal samples for building custom kits within BFD3. Includes rare and high-end kit pieces not found in the base library.",
        "url": "https://www.bfddrums.com/products/bfd-deluxe-kit-pieces",
        "rating": 4.4,
        "ratingCount": 185,
    },
    {
        "name": "BFD Wersey Drums",
        "slug": "bfd-wersey-drums",
        "developer": "BFD Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A BFD expansion sampled from classic vintage drum kits with a warm, slightly compressed character. Ideal for Merseybeat, 1960s pop, and early rock productions.",
        "url": "https://www.bfddrums.com/products/bfd-wersey-drums",
        "rating": 4.4,
        "ratingCount": 170,
    },

    # --- Steven Slate Drums ---
    {
        "name": "Steven Slate Drums 5",
        "slug": "steven-slate-drums-5",
        "developer": "Steven Slate Drums",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A professional drum plugin sampled from world-class kits played by top session drummers and processed through vintage hardware. Known for its punchy, mix-ready sound.",
        "url": "https://stevenslatedrums.com/ssd5/",
        "rating": 4.7,
        "ratingCount": 980,
    },
    {
        "name": "Steven Slate Drums SSD5.5",
        "slug": "steven-slate-drums-ssd5-5",
        "developer": "Steven Slate Drums",
        "category": "drums",
        "price": "$199",
        "priceType": "paid",
        "description": "An expanded update to SSD5 adding new premium drum kits and an enhanced mixing environment. Delivers even more sample variety and tonal range for modern productions.",
        "url": "https://stevenslatedrums.com/ssd5/",
        "rating": 4.8,
        "ratingCount": 740,
    },
    {
        "name": "SSD4",
        "slug": "ssd4",
        "developer": "Steven Slate Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "The fourth-generation Steven Slate drum plugin featuring meticulously recorded kit samples and a straightforward mixing interface. Still widely used for its distinctive punchy character.",
        "url": "https://stevenslatedrums.com/ssd4/",
        "rating": 4.5,
        "ratingCount": 550,
    },
    {
        "name": "SSD Free",
        "slug": "ssd-free",
        "developer": "Steven Slate Drums",
        "category": "drums",
        "price": "Free",
        "priceType": "free",
        "description": "A free version of Steven Slate Drums offering a curated selection of premium drum samples and a simplified plugin interface. An excellent starting point for producers on a budget.",
        "url": "https://stevenslatedrums.com/ssd5/#SSD5FREE",
        "rating": 4.4,
        "ratingCount": 1200,
    },
    {
        "name": "Trigger 2",
        "slug": "trigger-2",
        "developer": "Steven Slate Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A professional drum replacement and augmentation plugin that detects drum hits in audio recordings and replaces or layers them with samples. Industry standard for metal and rock production.",
        "url": "https://stevenslatedrums.com/trigger-2/",
        "rating": 4.6,
        "ratingCount": 860,
    },
    {
        "name": "Trigger 2 Platinum",
        "slug": "trigger-2-platinum",
        "developer": "Steven Slate Drums",
        "category": "drums",
        "price": "$249",
        "priceType": "paid",
        "description": "The full-featured version of Trigger 2 including an extensive library of premium replacement samples and expanded polyphony. Essential for studio-quality drum replacement workflows.",
        "url": "https://stevenslatedrums.com/trigger-2/",
        "rating": 4.7,
        "ratingCount": 570,
    },
    {
        "name": "All Access Pass",
        "slug": "steven-slate-all-access-pass",
        "developer": "Steven Slate Drums",
        "category": "drums",
        "price": "Subscription",
        "priceType": "subscription",
        "description": "A subscription bundle giving access to the entire Steven Slate Drums plugin catalog including SSD5.5, Trigger 2, and all expansions. Ideal for producers who want the full toolkit.",
        "url": "https://stevenslatedrums.com/all-access-pass/",
        "rating": 4.7,
        "ratingCount": 620,
    },

    # --- Heavyocity ---
    {
        "name": "Damage 2",
        "slug": "damage-2",
        "developer": "Heavyocity",
        "category": "drums",
        "price": "$349",
        "priceType": "paid",
        "description": "The successor to the legendary Damage, featuring an expanded library of hybrid cinematic percussion, rhythmic loops, and explosive sound design. A go-to for trailer and film music producers.",
        "url": "https://heavyocity.com/product/damage2/",
        "rating": 4.8,
        "ratingCount": 730,
    },
    {
        "name": "Novo Essentials",
        "slug": "novo-essentials",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A streamlined version of Novo featuring modern strings with an innovative rhythmic engine and cinematic articulations. Delivers professional orchestral string textures for media composers.",
        "url": "https://heavyocity.com/product/novo-essentials/",
        "rating": 4.6,
        "ratingCount": 390,
    },
    {
        "name": "Vento Essentials",
        "slug": "vento-essentials",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "An essential woodwind library from Heavyocity featuring expressive solo and ensemble woodwind performances. Includes the signature Heavyocity rhythmic engine for evolving textures.",
        "url": "https://heavyocity.com/product/vento-essentials/",
        "rating": 4.5,
        "ratingCount": 280,
    },
    {
        "name": "Gravity Strings",
        "slug": "gravity-strings",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A hybrid string instrument combining organic orchestral samples with Heavyocity's signature sound design. Features evolving textures and pulsing rhythmic content for cinematic productions.",
        "url": "https://heavyocity.com/product/gravity-strings/",
        "rating": 4.6,
        "ratingCount": 320,
    },
    {
        "name": "Vex",
        "slug": "vex-heavyocity",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A dark and complex sound design tool from Heavyocity featuring chaotic textures, hybrid percussion, and evolving atmospheres. Ideal for horror, thriller, and experimental film scoring.",
        "url": "https://heavyocity.com/product/vex/",
        "rating": 4.5,
        "ratingCount": 260,
    },
    {
        "name": "Damage",
        "slug": "damage-heavyocity",
        "developer": "Heavyocity",
        "category": "drums",
        "price": "$349",
        "priceType": "paid",
        "description": "The original Heavyocity cinematic percussion powerhouse featuring massive hybrid drums, loops, and sound design elements. A film and trailer music industry standard since its release.",
        "url": "https://heavyocity.com/product/damage/",
        "rating": 4.8,
        "ratingCount": 950,
    },
    {
        "name": "Forzo",
        "slug": "forzo-heavyocity",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A modern brass library combining orchestral performance with aggressive sound design elements. Built for cinematic composers who need powerful, hybrid brass textures.",
        "url": "https://heavyocity.com/product/forzo/",
        "rating": 4.7,
        "ratingCount": 450,
    },
    {
        "name": "Mosaic Tape",
        "slug": "mosaic-tape",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "Part of Heavyocity's Mosaic series, featuring tape-saturated samples processed through vintage analog gear. Perfect for lo-fi, warm, and nostalgic sound design.",
        "url": "https://heavyocity.com/product/mosaic-tape/",
        "rating": 4.5,
        "ratingCount": 310,
    },
    {
        "name": "Mosaic Brass",
        "slug": "mosaic-brass",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A Mosaic series library featuring intimate, close-miked brass samples with a raw, organic feel. Designed for producers who want natural brass textures without a bombastic orchestral character.",
        "url": "https://heavyocity.com/product/mosaic-brass/",
        "rating": 4.5,
        "ratingCount": 270,
    },
    {
        "name": "Mosaic Keys",
        "slug": "mosaic-keys",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A Mosaic series piano and keyboard library featuring intimate, processed key sounds with a warm, textured character. Ideal for cinematic, ambient, and indie productions.",
        "url": "https://heavyocity.com/product/mosaic-keys/",
        "rating": 4.6,
        "ratingCount": 330,
    },
    {
        "name": "Mosaic Voices",
        "slug": "mosaic-voices",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A Mosaic series vocal library offering ethereal, processed choir and solo vocal textures. Delivers haunting atmospheric pads, breaths, and melodic phrases for cinematic scoring.",
        "url": "https://heavyocity.com/product/mosaic-voices/",
        "rating": 4.5,
        "ratingCount": 295,
    },
    {
        "name": "Mosaic Guitar",
        "slug": "mosaic-guitar",
        "developer": "Heavyocity",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A Mosaic series library featuring intimate, processed guitar samples with a warm, lo-fi aesthetic. Includes fingerpicked acoustic and electric guitar textures for atmospheric production.",
        "url": "https://heavyocity.com/product/mosaic-guitar/",
        "rating": 4.4,
        "ratingCount": 240,
    },
    {
        "name": "Damage PC",
        "slug": "damage-pc",
        "developer": "Heavyocity",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A standalone percussion and cinematic drum expansion for Damage, adding new kit pieces, loops, and sound design elements. Extends the Damage ecosystem with fresh content.",
        "url": "https://heavyocity.com/product/damage-pc/",
        "rating": 4.5,
        "ratingCount": 210,
    },

    # --- Output Industries / Other Drum Plugins ---
    {
        "name": "Slate + Ash Cycles",
        "slug": "slate-ash-cycles",
        "developer": "Slate + Ash",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A generative sample instrument that creates evolving, cyclic textures from deeply processed sound sources. Designed for ambient, cinematic, and experimental electronic production.",
        "url": "https://www.slateandash.com/products/cycles",
        "rating": 4.6,
        "ratingCount": 340,
    },
    {
        "name": "GetGood Drums Modern & Massive",
        "slug": "getgood-drums-modern-and-massive",
        "developer": "GetGood Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A drum sample library built for modern metal and hard rock, featuring massive low-end kick sounds, razor-sharp snares, and pristine cymbals. Includes presets from top metal producers.",
        "url": "https://www.getgooddrums.com/products/modern-and-massive",
        "rating": 4.7,
        "ratingCount": 650,
    },
    {
        "name": "GetGood Drums Matt Halpern Signature Pack",
        "slug": "getgood-drums-matt-halpern-signature-pack",
        "developer": "GetGood Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A drum sample library capturing the personal kits of Periphery drummer Matt Halpern with his signature progressive metal tones. Includes MIDI grooves programmed by Halpern himself.",
        "url": "https://www.getgooddrums.com/products/matt-halpern",
        "rating": 4.7,
        "ratingCount": 480,
    },
    {
        "name": "GetGood Drums Nagamatzu",
        "slug": "getgood-drums-nagamatzu",
        "developer": "GetGood Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "A genre-crossing drum sample library from GetGood Drums featuring versatile kits suited to rock, metal, and ambient production. Engineered with exceptional dynamic range and natural transients.",
        "url": "https://www.getgooddrums.com/products/nagamatzu",
        "rating": 4.6,
        "ratingCount": 360,
    },
    {
        "name": "GetGood Drums Invasion",
        "slug": "getgood-drums-invasion",
        "developer": "GetGood Drums",
        "category": "drums",
        "price": "$99",
        "priceType": "paid",
        "description": "An electronically processed drum library from GetGood Drums blending organic acoustic samples with aggressive electronic processing. Perfect for industrial, djent, and hybrid electronic productions.",
        "url": "https://www.getgooddrums.com/products/invasion",
        "rating": 4.6,
        "ratingCount": 320,
    },
    {
        "name": "Ugritone Kvlt Drums",
        "slug": "ugritone-kvlt-drums",
        "developer": "Ugritone",
        "category": "drums",
        "price": "$49",
        "priceType": "paid",
        "description": "A raw, lo-fi black metal drum plugin from Ugritone capturing the classic lo-fi aesthetic of underground black metal recordings. Features primitive room sounds and deliberately rough textures.",
        "url": "https://ugritone.com/products/kvlt-drums",
        "rating": 4.5,
        "ratingCount": 290,
    },
    {
        "name": "Ugritone Rude Drums",
        "slug": "ugritone-rude-drums",
        "developer": "Ugritone",
        "category": "drums",
        "price": "$49",
        "priceType": "paid",
        "description": "A punk and hardcore-oriented drum plugin delivering aggressive, in-your-face drum sounds. Built for speed, the Rude Drums preset library covers everything from 80s hardcore to modern punk.",
        "url": "https://ugritone.com/products/rude-drums",
        "rating": 4.4,
        "ratingCount": 210,
    },
    {
        "name": "Ugritone Meta Drums",
        "slug": "ugritone-meta-drums",
        "developer": "Ugritone",
        "category": "drums",
        "price": "$49",
        "priceType": "paid",
        "description": "A modern metal drum plugin from Ugritone featuring thick, powerful tones designed for contemporary metal production. Covers djent, metalcore, and progressive metal aesthetics.",
        "url": "https://ugritone.com/products/meta-drums",
        "rating": 4.5,
        "ratingCount": 280,
    },
    {
        "name": "Ugritone Neon Drums",
        "slug": "ugritone-neon-drums",
        "developer": "Ugritone",
        "category": "drums",
        "price": "$49",
        "priceType": "paid",
        "description": "An 80s-inspired drum plugin from Ugritone featuring gated reverb snares, booming kicks, and vintage drum machine-influenced sounds. Perfect for synthwave and retro pop productions.",
        "url": "https://ugritone.com/products/neon-drums",
        "rating": 4.5,
        "ratingCount": 240,
    },
    {
        "name": "Ugritone Electro Drums",
        "slug": "ugritone-electro-drums",
        "developer": "Ugritone",
        "category": "drums",
        "price": "$49",
        "priceType": "paid",
        "description": "A heavily processed electronic drum plugin from Ugritone combining acoustic samples with synthesized elements. Aimed at industrial, EBM, and electronic metal productions.",
        "url": "https://ugritone.com/products/electro-drums",
        "rating": 4.4,
        "ratingCount": 195,
    },
    {
        "name": "Room Sound Vintage Snare Foundry",
        "slug": "room-sound-vintage-snare-foundry",
        "developer": "Room Sound",
        "category": "drums",
        "price": "$79",
        "priceType": "paid",
        "description": "A curated collection of vintage snare drum samples recorded across multiple studios, tunings, and striking positions. An essential resource for producers who need the perfect snare sound.",
        "url": "https://www.roomsound.com/vintage-snare-foundry",
        "rating": 4.6,
        "ratingCount": 310,
    },
    {
        "name": "Soniccouture Torn & Blown",
        "slug": "soniccouture-torn-and-blown",
        "developer": "Soniccouture",
        "category": "sampler",
        "price": "$69",
        "priceType": "paid",
        "description": "A damaged and prepared piano library capturing the unique textures of a deliberately altered upright piano. Features buzzing, rattling, and muted strings for experimental sound design.",
        "url": "https://www.soniccouture.com/en/products/35-extended-techniques/g32-torn-blown/",
        "rating": 4.5,
        "ratingCount": 220,
    },
    {
        "name": "PastToFutureReverbs Drum Room",
        "slug": "pasttofuturereverbs-drum-room",
        "developer": "PastToFutureReverbs",
        "category": "drums",
        "price": "$29",
        "priceType": "paid",
        "description": "An impulse response reverb library capturing the acoustic character of classic drum recording rooms and chambers. Adds authentic space and depth to virtual and recorded drum tracks.",
        "url": "https://www.pasttofuturereverbs.com/drum-room",
        "rating": 4.4,
        "ratingCount": 175,
    },
    {
        "name": "DrumVault Vintage Vol. 1",
        "slug": "drumvault-vintage-vol-1",
        "developer": "DrumVault",
        "category": "drums",
        "price": "$49",
        "priceType": "paid",
        "description": "A vintage drum sample library featuring meticulously recorded classic drum kits from the 1960s and 70s. Captures the organic, slightly imperfect character of early rock and soul recordings.",
        "url": "https://www.drumvault.com/vintage-vol-1",
        "rating": 4.4,
        "ratingCount": 185,
    },

    # --- Orchestral Tools ---
    {
        "name": "Berlin Orchestra Inspire 3",
        "slug": "berlin-orchestra-inspire-3",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$399",
        "priceType": "paid",
        "description": "A comprehensive orchestral library recorded with the Berlin Radio Symphony Orchestra, offering a wide range of articulations for all major sections. Built on the powerful SINE player engine.",
        "url": "https://www.orchestraltools.com/store/series/72",
        "rating": 4.8,
        "ratingCount": 820,
    },
    {
        "name": "Berlin Strings",
        "slug": "berlin-strings",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$799",
        "priceType": "paid",
        "description": "A flagship string library recorded with premier Berlin session musicians across multiple microphone positions. Renowned for its expressive legato transitions and tonal depth.",
        "url": "https://www.orchestraltools.com/store/series/1",
        "rating": 4.9,
        "ratingCount": 710,
    },
    {
        "name": "Berlin Brass",
        "slug": "berlin-brass",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$699",
        "priceType": "paid",
        "description": "A comprehensive brass library capturing a full orchestral brass section with extensive articulations and multiple microphone positions. Delivers powerful, natural brass ensemble sounds.",
        "url": "https://www.orchestraltools.com/store/series/2",
        "rating": 4.8,
        "ratingCount": 590,
    },
    {
        "name": "Berlin Woodwinds",
        "slug": "berlin-woodwinds",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$699",
        "priceType": "paid",
        "description": "A detailed woodwind library featuring flutes, oboes, clarinets, and bassoons recorded with world-class Berlin session players. Offers extensive legato scripting and breath noise controls.",
        "url": "https://www.orchestraltools.com/store/series/3",
        "rating": 4.8,
        "ratingCount": 540,
    },
    {
        "name": "Berlin Woodwinds Exp A",
        "slug": "berlin-woodwinds-exp-a",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "An expansion to Berlin Woodwinds adding additional articulations, extended techniques, and solo woodwind performances. Deepens the expressive range of the core Berlin Woodwinds library.",
        "url": "https://www.orchestraltools.com/store/series/berlin-woodwinds-exp-a",
        "rating": 4.7,
        "ratingCount": 290,
    },
    {
        "name": "Berlin Brass Exp A",
        "slug": "berlin-brass-exp-a",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "An expansion to Berlin Brass that adds muted brass, additional dynamic layers, and extended techniques to the base library. Essential for composers needing maximum brass versatility.",
        "url": "https://www.orchestraltools.com/store/series/berlin-brass-exp-a",
        "rating": 4.7,
        "ratingCount": 270,
    },
    {
        "name": "Berlin Percussion",
        "slug": "berlin-percussion",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$499",
        "priceType": "paid",
        "description": "A massive orchestral percussion library featuring timpani, snare, cymbals, and a wide range of orchestral pitched and unpitched instruments. Recorded at Teldex Studio Berlin.",
        "url": "https://www.orchestraltools.com/store/series/berlin-percussion",
        "rating": 4.8,
        "ratingCount": 420,
    },
    {
        "name": "Berlin Choir",
        "slug": "berlin-choir",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$499",
        "priceType": "paid",
        "description": "A professional choral library recorded with a full Berlin choir ensemble across multiple vowels, dynamics, and articulations. Provides rich, detailed choral textures for cinematic and classical scoring.",
        "url": "https://www.orchestraltools.com/store/series/berlin-choir",
        "rating": 4.7,
        "ratingCount": 380,
    },
    {
        "name": "Berlin Pop Orchestra Brass",
        "slug": "berlin-pop-orchestra-brass",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A pop and commercial-oriented brass library featuring tight, punchy brass section recordings suited to pop, jazz, and funk productions. Recorded with a hand-picked ensemble of Berlin session players.",
        "url": "https://www.orchestraltools.com/store/series/berlin-pop-orchestra-brass",
        "rating": 4.6,
        "ratingCount": 310,
    },
    {
        "name": "Tallinn",
        "slug": "tallinn-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A haunting string library recorded at the Estonian Radio Concert Hall in Tallinn, capturing a distinctive Nordic acoustic character. Particularly suited to minimal, atmospheric, and modern classical scoring.",
        "url": "https://www.orchestraltools.com/store/series/tallinn",
        "rating": 4.7,
        "ratingCount": 360,
    },
    {
        "name": "Metropolis Ark 1",
        "slug": "metropolis-ark-1",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$499",
        "priceType": "paid",
        "description": "A massive, epic orchestral library designed for blockbuster film and game scoring, featuring an 85-piece orchestra recorded at Teldex Studio Berlin. Includes dramatic, cinematic articulations.",
        "url": "https://www.orchestraltools.com/store/series/metropolis-ark-1",
        "rating": 4.9,
        "ratingCount": 780,
    },
    {
        "name": "Metropolis Ark 2",
        "slug": "metropolis-ark-2",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$499",
        "priceType": "paid",
        "description": "The second volume of the Metropolis Ark series focusing on soft, delicate, and intimate orchestral textures as a counterpart to Ark 1's power. Perfect for emotional underscore and tender moments.",
        "url": "https://www.orchestraltools.com/store/series/metropolis-ark-2",
        "rating": 4.8,
        "ratingCount": 560,
    },
    {
        "name": "Metropolis Ark 3",
        "slug": "metropolis-ark-3",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$499",
        "priceType": "paid",
        "description": "The third Metropolis Ark volume featuring extended techniques, col legno strings, and extreme orchestral textures. A unique toolkit for modern, avant-garde, and horror film scoring.",
        "url": "https://www.orchestraltools.com/store/series/metropolis-ark-3",
        "rating": 4.7,
        "ratingCount": 440,
    },
    {
        "name": "Metropolis Ark 4",
        "slug": "metropolis-ark-4",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$499",
        "priceType": "paid",
        "description": "The fourth installment of Metropolis Ark focused on solo instruments and small chamber ensembles. Brings an intimate, expressive counterbalance to the grandeur of the earlier volumes.",
        "url": "https://www.orchestraltools.com/store/series/metropolis-ark-4",
        "rating": 4.7,
        "ratingCount": 390,
    },
    {
        "name": "CAGE",
        "slug": "cage-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "A prepared piano library inspired by John Cage's experimental works, featuring screwed, muted, and altered string preparations. Delivers distinctive avant-garde piano textures.",
        "url": "https://www.orchestraltools.com/store/series/cage",
        "rating": 4.6,
        "ratingCount": 260,
    },
    {
        "name": "Balalaika",
        "slug": "balalaika-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A detailed sampling of the traditional Russian balalaika featuring multiple playing techniques and dynamic layers. Brings authentic Eastern European folk character to compositions.",
        "url": "https://www.orchestraltools.com/store/series/balalaika",
        "rating": 4.4,
        "ratingCount": 180,
    },
    {
        "name": "Thai Traditional",
        "slug": "thai-traditional-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A collection of sampled traditional Thai instruments including the ranat ek, klong, and pi nai. An authentic resource for world music scoring and cultural productions.",
        "url": "https://www.orchestraltools.com/store/series/thai-traditional",
        "rating": 4.4,
        "ratingCount": 165,
    },
    {
        "name": "Lacrimosa",
        "slug": "lacrimosa-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A dark, emotive choral library featuring deeply expressive ensemble performances with a wide range of vowel and dynamic variations. Designed for dramatic film and classical scoring.",
        "url": "https://www.orchestraltools.com/store/series/lacrimosa",
        "rating": 4.7,
        "ratingCount": 340,
    },
    {
        "name": "Nocturne Strings",
        "slug": "nocturne-strings",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "An intimate chamber string library recorded at night for a uniquely calm acoustic environment. Delivers delicate, close-miked string textures ideal for tender emotional scoring.",
        "url": "https://www.orchestraltools.com/store/series/nocturne-strings",
        "rating": 4.7,
        "ratingCount": 370,
    },
    {
        "name": "Miroire",
        "slug": "miroire-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "A reflective, intimate piano library recorded with a focus on quiet dynamics and late-night character. Features soft pedaling, una corda, and close-miked tone colors.",
        "url": "https://www.orchestraltools.com/store/series/miroire",
        "rating": 4.6,
        "ratingCount": 280,
    },
    {
        "name": "Swing! More! Jazz Big Band",
        "slug": "swing-more-jazz-big-band",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A comprehensive jazz big band library featuring full sections of saxophones, trumpets, trombones, and rhythm section instruments. Includes idiomatic swing articulations and realistic jazz phrasing.",
        "url": "https://www.orchestraltools.com/store/series/swing-more",
        "rating": 4.7,
        "ratingCount": 360,
    },
    {
        "name": "Forte Piano",
        "slug": "forte-piano-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "A meticulously sampled fortepiano capturing the authentic sound of early classical keyboard instruments. Ideal for period-correct classical and baroque scoring.",
        "url": "https://www.orchestraltools.com/store/series/forte-piano",
        "rating": 4.5,
        "ratingCount": 215,
    },
    {
        "name": "Cimbalom",
        "slug": "cimbalom-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A detailed sampling of the cimbalom, the traditional Hungarian hammered dulcimer, featuring multiple articulations and dynamic layers. Brings unique Eastern European texture to orchestral writing.",
        "url": "https://www.orchestraltools.com/store/series/cimbalom",
        "rating": 4.4,
        "ratingCount": 165,
    },
    {
        "name": "Boris",
        "slug": "boris-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A solo cello library featuring expressive, deeply characterized performances with a broad range of classical and extended technique articulations. Named after the sampled cellist.",
        "url": "https://www.orchestraltools.com/store/series/boris",
        "rating": 4.6,
        "ratingCount": 280,
    },
    {
        "name": "Boris Winds",
        "slug": "boris-winds-orchestral-tools",
        "developer": "Orchestral Tools",
        "category": "sampler",
        "price": "$99",
        "priceType": "paid",
        "description": "A companion solo woodwind library to Boris, featuring expressive solo oboe, clarinet, and bassoon performances with intimate, close-miked character.",
        "url": "https://www.orchestraltools.com/store/series/boris-winds",
        "rating": 4.5,
        "ratingCount": 220,
    },

    # --- ProjectSAM ---
    {
        "name": "Symphobia 1",
        "slug": "symphobia-1",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$399",
        "priceType": "paid",
        "description": "A groundbreaking orchestral library focused on ensemble performances, clusters, and hybrid sounds recorded at Galaxy Studios. Known for its lush legato and powerful ensemble patches.",
        "url": "https://projectsam.com/libraries/symphobia-1/",
        "rating": 4.8,
        "ratingCount": 720,
    },
    {
        "name": "Symphobia 2",
        "slug": "symphobia-2",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$399",
        "priceType": "paid",
        "description": "The sequel to Symphobia 1, featuring an expanded ensemble palette with unique hybrid articulations, dissonant clusters, and extended orchestral techniques.",
        "url": "https://projectsam.com/libraries/symphobia-2/",
        "rating": 4.8,
        "ratingCount": 590,
    },
    {
        "name": "Symphobia 3 Lumina",
        "slug": "symphobia-3-lumina",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$399",
        "priceType": "paid",
        "description": "A lush, ethereal orchestral library focused on delicate, shimmering textures and atmospheric ensemble sounds. Lumina balances acoustic instruments with subtle electronic processing.",
        "url": "https://projectsam.com/libraries/symphobia-3-lumina/",
        "rating": 4.7,
        "ratingCount": 460,
    },
    {
        "name": "Symphobia 4 Pandora",
        "slug": "symphobia-4-pandora",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$399",
        "priceType": "paid",
        "description": "The fourth Symphobia volume delivering dark, dramatic, and dissonant orchestral textures. Pandora focuses on tension-building and experimental orchestration techniques.",
        "url": "https://projectsam.com/libraries/symphobia-4-pandora/",
        "rating": 4.7,
        "ratingCount": 390,
    },
    {
        "name": "Orchestral Essentials 1",
        "slug": "orchestral-essentials-1",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "An accessible, comprehensive orchestral library covering all major sections with clean, versatile articulations. Ideal for composers new to orchestral writing or those needing a broad-coverage library.",
        "url": "https://projectsam.com/libraries/orchestral-essentials-1/",
        "rating": 4.6,
        "ratingCount": 510,
    },
    {
        "name": "Orchestral Essentials 2",
        "slug": "orchestral-essentials-2",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "A companion volume to Orchestral Essentials 1 offering extended articulations, additional percussion, and more specialized orchestral patches.",
        "url": "https://projectsam.com/libraries/orchestral-essentials-2/",
        "rating": 4.6,
        "ratingCount": 400,
    },
    {
        "name": "True Strike 1",
        "slug": "true-strike-1",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A cinematic percussion library featuring taiko drums, orchestral hits, and an enormous range of rhythmic percussion elements. Built for film and trailer music production.",
        "url": "https://projectsam.com/libraries/true-strike-1/",
        "rating": 4.7,
        "ratingCount": 530,
    },
    {
        "name": "True Strike 2",
        "slug": "true-strike-2",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "The follow-up to True Strike 1, expanding the cinematic percussion palette with additional world percussion, orchestral elements, and hybrid processed sounds.",
        "url": "https://projectsam.com/libraries/true-strike-2/",
        "rating": 4.7,
        "ratingCount": 440,
    },
    {
        "name": "Swing! More!",
        "slug": "projectsam-swing-more",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A jazz big band library featuring authentic swing articulations, ensemble sections, and solo instruments. Designed to make realistic jazz band writing accessible within a sampler environment.",
        "url": "https://projectsam.com/libraries/swing-more/",
        "rating": 4.7,
        "ratingCount": 350,
    },
    {
        "name": "Intimate WOODWINDS",
        "slug": "intimate-woodwinds-projectsam",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "A close-miked, intimate woodwind library featuring solo and small ensemble recordings with a warm, natural character. Particularly suited to chamber, contemporary classical, and underscore.",
        "url": "https://projectsam.com/libraries/intimate-woodwinds/",
        "rating": 4.6,
        "ratingCount": 310,
    },
    {
        "name": "Fanfare",
        "slug": "fanfare-projectsam",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "A dedicated brass ensemble library focusing on powerful fanfare-style articulations, including rips, falls, and ensemble swells. Built for epic and ceremonial musical moments.",
        "url": "https://projectsam.com/libraries/fanfare/",
        "rating": 4.6,
        "ratingCount": 280,
    },
    {
        "name": "The Free Orchestra",
        "slug": "the-free-orchestra-projectsam",
        "developer": "ProjectSAM",
        "category": "sampler",
        "price": "Free",
        "priceType": "free",
        "description": "A free orchestral library from ProjectSAM offering a curated selection of high-quality string, brass, woodwind, and percussion patches. A generous introduction to the ProjectSAM sound.",
        "url": "https://projectsam.com/libraries/the-free-orchestra/",
        "rating": 4.7,
        "ratingCount": 1450,
    },

    # --- 8Dio ---
    {
        "name": "Adagio Violins",
        "slug": "adagio-violins-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A deeply expressive violin section library from 8Dio featuring multiple divisi configurations and rich legato scripting. Captured in a prestigious European concert hall.",
        "url": "https://8dio.com/product/adagio-violins/",
        "rating": 4.7,
        "ratingCount": 420,
    },
    {
        "name": "Adagio Violas",
        "slug": "adagio-violas-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A lush viola section library with detailed articulations and expressive legato transitions. Part of 8Dio's acclaimed Adagio series of orchestral string libraries.",
        "url": "https://8dio.com/product/adagio-violas/",
        "rating": 4.7,
        "ratingCount": 340,
    },
    {
        "name": "Adagio Cellos",
        "slug": "adagio-cellos-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A powerful cello section library with deep, resonant tone and extensive articulation options. A cornerstone of 8Dio's Adagio orchestral string family.",
        "url": "https://8dio.com/product/adagio-cellos/",
        "rating": 4.7,
        "ratingCount": 360,
    },
    {
        "name": "Adagio Basses",
        "slug": "adagio-basses-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A rich double bass section library delivering the low-end foundation of the orchestral string family. Features powerful pizzicato, arco, and tremolo articulations.",
        "url": "https://8dio.com/product/adagio-basses/",
        "rating": 4.6,
        "ratingCount": 290,
    },
    {
        "name": "Adagio Flutes",
        "slug": "adagio-flutes-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A bright and airy flute section library featuring solo and ensemble flute performances with detailed breath and attack controls. Part of 8Dio's Adagio woodwind collection.",
        "url": "https://8dio.com/product/adagio-flutes/",
        "rating": 4.6,
        "ratingCount": 260,
    },
    {
        "name": "Adagio Oboes",
        "slug": "adagio-oboes-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A poignant oboe library from 8Dio capturing the distinctive nasal character of solo and small ensemble oboe performances. Includes a range of expressive articulations.",
        "url": "https://8dio.com/product/adagio-oboes/",
        "rating": 4.6,
        "ratingCount": 220,
    },
    {
        "name": "Adagio Clarinets",
        "slug": "adagio-clarinets-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A warm and versatile clarinet library featuring both solo and ensemble performances from 8Dio's Adagio woodwind series. Delivers wide dynamic range and detailed tonal shading.",
        "url": "https://8dio.com/product/adagio-clarinets/",
        "rating": 4.6,
        "ratingCount": 240,
    },
    {
        "name": "Adagio Bassoons",
        "slug": "adagio-bassoons-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A rich and characterful bassoon library capturing the unique tonal depth of solo and ensemble bassoon performances. Part of 8Dio's comprehensive Adagio woodwind family.",
        "url": "https://8dio.com/product/adagio-bassoons/",
        "rating": 4.6,
        "ratingCount": 210,
    },
    {
        "name": "Adagio Horns",
        "slug": "adagio-horns-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A majestic French horn library from 8Dio featuring a full section and solo horn performances with extensive articulations. Captures the warm, rounded character of orchestral horn writing.",
        "url": "https://8dio.com/product/adagio-horns/",
        "rating": 4.7,
        "ratingCount": 310,
    },
    {
        "name": "Adagio Trumpets",
        "slug": "adagio-trumpets-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A brilliant trumpet section library from 8Dio with powerful fortissimo and delicate pianissimo articulations. Delivers the full expressive range of orchestral trumpet writing.",
        "url": "https://8dio.com/product/adagio-trumpets/",
        "rating": 4.7,
        "ratingCount": 290,
    },
    {
        "name": "Adagio Trombones",
        "slug": "adagio-trombones-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A powerful trombone section library capturing the full dynamic range from soft lyrical lines to bold brass attacks. Includes tenor and bass trombone performances.",
        "url": "https://8dio.com/product/adagio-trombones/",
        "rating": 4.6,
        "ratingCount": 260,
    },
    {
        "name": "Adagio Tubas",
        "slug": "adagio-tubas-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A deep and resonant tuba library from 8Dio featuring both solo and small ensemble tuba performances. Delivers the full weight and gravitas of the orchestral bass brass voice.",
        "url": "https://8dio.com/product/adagio-tubas/",
        "rating": 4.6,
        "ratingCount": 195,
    },
    {
        "name": "Century Strings",
        "slug": "century-strings-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$499",
        "priceType": "paid",
        "description": "8Dio's flagship string library recorded with a large Hollywood-style string ensemble. Features an innovative 9-channel microphone setup and extensive true legato scripting.",
        "url": "https://8dio.com/product/century-strings/",
        "rating": 4.8,
        "ratingCount": 560,
    },
    {
        "name": "Century Brass",
        "slug": "century-brass-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$499",
        "priceType": "paid",
        "description": "A monumental brass library featuring a full Hollywood-style brass ensemble with extensive articulations and multiple microphone positions. Part of 8Dio's Century series.",
        "url": "https://8dio.com/product/century-brass/",
        "rating": 4.8,
        "ratingCount": 480,
    },
    {
        "name": "Anthology Strings",
        "slug": "anthology-strings-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$799",
        "priceType": "paid",
        "description": "8Dio's ultimate string collection spanning multiple ensemble sizes and recording environments. A comprehensive resource for any composer needing complete string coverage.",
        "url": "https://8dio.com/product/anthology-strings/",
        "rating": 4.8,
        "ratingCount": 390,
    },
    {
        "name": "1937 Steinway D",
        "slug": "1937-steinway-d-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A meticulously captured 1937 Steinway Model D grand piano with a warm, aged character and intimate acoustic presence. Offers multiple velocity layers and close/room microphone options.",
        "url": "https://8dio.com/product/1937-steinway-d/",
        "rating": 4.7,
        "ratingCount": 370,
    },
    {
        "name": "1928 Bosendorfer",
        "slug": "1928-bosendorfer-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A rare 1928 Bosendorfer grand piano captured with stunning detail and tonal richness. Features the distinctive warm, dark character unique to vintage Bosendorfer instruments.",
        "url": "https://8dio.com/product/1928-bosendorfer/",
        "rating": 4.7,
        "ratingCount": 340,
    },
    {
        "name": "New Antique Grand",
        "slug": "new-antique-grand-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A vintage grand piano library from 8Dio featuring a beautifully aged instrument with warm, intimate tone. Includes both unprocessed acoustic and creatively processed versions.",
        "url": "https://8dio.com/product/new-antique-grand/",
        "rating": 4.6,
        "ratingCount": 270,
    },
    {
        "name": "Claire — Solo Violin",
        "slug": "claire-solo-violin-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "An expressive solo violin library from 8Dio named after and performed by violinist Claire Underwood. Features intimate, deeply personal performances with extensive articulations.",
        "url": "https://8dio.com/product/claire-solo-violin/",
        "rating": 4.7,
        "ratingCount": 320,
    },
    {
        "name": "Liberis — Boys Choir",
        "slug": "liberis-boys-choir-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "A angelic boys choir library from 8Dio featuring pure, bright ensemble vocals with multiple vowels and dynamic layers. Perfect for sacred, cinematic, and emotional choral writing.",
        "url": "https://8dio.com/product/liberis/",
        "rating": 4.7,
        "ratingCount": 290,
    },
    {
        "name": "Lacrimosa Choir",
        "slug": "lacrimosa-choir-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A dramatic and powerful choral library from 8Dio designed for dark, emotional, and cinematic choral writing. Features full SATB ensemble recordings with multiple articulation options.",
        "url": "https://8dio.com/product/lacrimosa-choir/",
        "rating": 4.7,
        "ratingCount": 350,
    },
    {
        "name": "Studio Brass",
        "slug": "studio-brass-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A versatile studio brass library from 8Dio featuring pop, jazz, and commercial brass section recordings. Ideal for producers working in commercial, R&B, and contemporary orchestral styles.",
        "url": "https://8dio.com/product/studio-brass/",
        "rating": 4.6,
        "ratingCount": 280,
    },
    {
        "name": "Studio Strings",
        "slug": "studio-strings-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A commercial studio string library from 8Dio designed for pop, R&B, and contemporary scoring. Features lush, processed string sounds alongside clean orchestral articulations.",
        "url": "https://8dio.com/product/studio-strings/",
        "rating": 4.6,
        "ratingCount": 300,
    },
    {
        "name": "Studio Woodwinds",
        "slug": "studio-woodwinds-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$299",
        "priceType": "paid",
        "description": "A studio woodwind library from 8Dio offering commercial pop and film scoring woodwind textures. Includes solo and ensemble patches optimized for modern music production.",
        "url": "https://8dio.com/product/studio-woodwinds/",
        "rating": 4.5,
        "ratingCount": 240,
    },
    {
        "name": "Hybrid Tools 1",
        "slug": "hybrid-tools-1-8dio",
        "developer": "8Dio",
        "category": "sampler",
        "price": "$198",
        "priceType": "paid",
        "description": "A hybrid cinematic toolkit from 8Dio combining organic orchestral samples with aggressive electronic processing and sound design. A powerful resource for modern trailer and game music production.",
        "url": "https://8dio.com/product/hybrid-tools-1/",
        "rating": 4.7,
        "ratingCount": 430,
    },

    # --- Sonuscore ---
    {
        "name": "The Orchestra",
        "slug": "the-orchestra-sonuscore",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$399",
        "priceType": "paid",
        "description": "A comprehensive orchestral composition engine from Sonuscore featuring intelligent arpeggiators, rhythm generators, and full orchestral sections. Designed for fast, inspiring orchestral writing.",
        "url": "https://sonuscore.com/shop/the-orchestra/",
        "rating": 4.8,
        "ratingCount": 680,
    },
    {
        "name": "The Orchestra Companion Strings",
        "slug": "the-orchestra-companion-strings",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A companion string expansion for The Orchestra adding additional articulations, textures, and expressive capabilities to the string section. Deepens the orchestral string palette.",
        "url": "https://sonuscore.com/shop/the-orchestra-companion-strings/",
        "rating": 4.6,
        "ratingCount": 310,
    },
    {
        "name": "The Orchestra Companion Brass",
        "slug": "the-orchestra-companion-brass",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A brass expansion for The Orchestra adding extended brass articulations and ensemble textures. Provides greater expressive range and tonal variety within the Sonuscore ecosystem.",
        "url": "https://sonuscore.com/shop/the-orchestra-companion-brass/",
        "rating": 4.6,
        "ratingCount": 270,
    },
    {
        "name": "The Orchestra Companion Woodwinds",
        "slug": "the-orchestra-companion-woodwinds",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$149",
        "priceType": "paid",
        "description": "A woodwind expansion for The Orchestra adding detailed solo and ensemble woodwind articulations. Rounds out the complete orchestral palette within The Orchestra system.",
        "url": "https://sonuscore.com/shop/the-orchestra-companion-woodwinds/",
        "rating": 4.5,
        "ratingCount": 240,
    },
    {
        "name": "Origins Vol.1 – Celtic Harp",
        "slug": "origins-vol1-celtic-harp",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$79",
        "priceType": "paid",
        "description": "The first volume of Sonuscore's Origins world instrument series, featuring a beautifully recorded Celtic harp with multiple playing techniques and integrated arpeggiator.",
        "url": "https://sonuscore.com/shop/origins-celtic-harp/",
        "rating": 4.6,
        "ratingCount": 310,
    },
    {
        "name": "Origins Vol.2 – Duduk",
        "slug": "origins-vol2-duduk",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$79",
        "priceType": "paid",
        "description": "The second Origins volume featuring the Armenian duduk, a haunting double-reed woodwind instrument with a deeply expressive character. Includes authentic legato and vibrato performances.",
        "url": "https://sonuscore.com/shop/origins-duduk/",
        "rating": 4.6,
        "ratingCount": 270,
    },
    {
        "name": "Origins Vol.3 – Turkish Saz Baglama",
        "slug": "origins-vol3-turkish-saz-baglama",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$79",
        "priceType": "paid",
        "description": "The third Origins volume capturing the Turkish saz baglama, a long-necked lute central to Anatolian folk music. Features authentic picking techniques and microtonal tuning options.",
        "url": "https://sonuscore.com/shop/origins-turkish-saz-baglama/",
        "rating": 4.5,
        "ratingCount": 230,
    },
    {
        "name": "Origins Vol.4 – Japanese Koto",
        "slug": "origins-vol4-japanese-koto",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$79",
        "priceType": "paid",
        "description": "The fourth Origins volume presenting the Japanese koto, a thirteen-string zither with a distinctly elegant and meditative character. Includes pizzicato, glissando, and tremolo articulations.",
        "url": "https://sonuscore.com/shop/origins-japanese-koto/",
        "rating": 4.5,
        "ratingCount": 210,
    },
    {
        "name": "Origins Vol.5 – Native American Flute",
        "slug": "origins-vol5-native-american-flute",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$79",
        "priceType": "paid",
        "description": "The fifth Origins volume featuring the Native American flute, a breathy, intimate wind instrument with deep spiritual character. Ideal for nature documentary, meditation, and world music scoring.",
        "url": "https://sonuscore.com/shop/origins-native-american-flute/",
        "rating": 4.5,
        "ratingCount": 195,
    },
    {
        "name": "Origins Vol.6 – African Kalimba",
        "slug": "origins-vol6-african-kalimba",
        "developer": "Sonuscore",
        "category": "sampler",
        "price": "$79",
        "priceType": "paid",
        "description": "The sixth Origins volume capturing the African kalimba (thumb piano) with its distinctive warm, tinkling character. Perfect for world music, meditation, and contemporary atmospheric production.",
        "url": "https://sonuscore.com/shop/origins-african-kalimba/",
        "rating": 4.5,
        "ratingCount": 220,
    },

    # --- Production Libraries and Packs ---
    {
        "name": "Splice Sounds",
        "slug": "splice-sounds",
        "developer": "Splice",
        "category": "sampler",
        "price": "Subscription",
        "priceType": "subscription",
        "description": "A subscription-based sample library platform offering millions of royalty-free loops, one-shots, and presets across all genres. Includes samples from top artists and sound designers worldwide.",
        "url": "https://splice.com/sounds",
        "rating": 4.7,
        "ratingCount": 1980,
    },
    {
        "name": "Loopmasters Fundamentals",
        "slug": "loopmasters-fundamentals",
        "developer": "Loopmasters",
        "category": "sampler",
        "price": "$29",
        "priceType": "paid",
        "description": "A foundational sample pack collection from Loopmasters covering essential loops and one-shots across major genres. An affordable starting point for producers building their sample library.",
        "url": "https://www.loopmasters.com/fundamentals",
        "rating": 4.4,
        "ratingCount": 560,
    },
    {
        "name": "LANDR Samples",
        "slug": "landr-samples",
        "developer": "LANDR",
        "category": "sampler",
        "price": "Subscription",
        "priceType": "subscription",
        "description": "A subscription sample library from LANDR offering curated royalty-free loops and one-shots paired with AI-powered mastering tools. Integrated into the broader LANDR production platform.",
        "url": "https://www.landr.com/samples/",
        "rating": 4.3,
        "ratingCount": 430,
    },
    {
        "name": "Producer Loops",
        "slug": "producer-loops",
        "developer": "Producer Loops",
        "category": "sampler",
        "price": "$29",
        "priceType": "paid",
        "description": "A sample pack publisher offering a wide range of genre-specific loop and one-shot packs for electronic music producers. Known for high-quality club music and EDM content.",
        "url": "https://www.producerloops.com/",
        "rating": 4.4,
        "ratingCount": 390,
    },
    {
        "name": "Prime Loops",
        "slug": "prime-loops",
        "developer": "Prime Loops",
        "category": "sampler",
        "price": "$29",
        "priceType": "paid",
        "description": "A sample pack publisher specializing in contemporary urban and electronic music content including hip-hop, trap, and bass music. All samples are royalty-free for commercial use.",
        "url": "https://www.primeloops.com/",
        "rating": 4.3,
        "ratingCount": 310,
    },
    {
        "name": "Sample Magic",
        "slug": "sample-magic",
        "developer": "Sample Magic",
        "category": "sampler",
        "price": "$29",
        "priceType": "paid",
        "description": "A UK-based sample pack publisher with an extensive catalog of electronic music loops and one-shots across house, techno, drum and bass, and more. Known for meticulous sound selection.",
        "url": "https://www.samplemagic.com/",
        "rating": 4.5,
        "ratingCount": 480,
    },
    {
        "name": "Looperman Free Samples",
        "slug": "looperman-free-samples",
        "developer": "Looperman",
        "category": "sampler",
        "price": "Free",
        "priceType": "free",
        "description": "A community-driven platform offering hundreds of thousands of free loops and samples uploaded by producers worldwide. All content is available under a Looperman royalty-free license.",
        "url": "https://www.looperman.com/",
        "rating": 4.3,
        "ratingCount": 820,
    },
    {
        "name": "Freesound.org",
        "slug": "freesound-org",
        "developer": "Universitat Pompeu Fabra",
        "category": "sampler",
        "price": "Free",
        "priceType": "free",
        "description": "A collaborative database of Creative Commons licensed audio recordings and samples contributed by a global community. An invaluable resource for sound designers, composers, and educators.",
        "url": "https://freesound.org/",
        "rating": 4.5,
        "ratingCount": 1650,
    },
    {
        "name": "Noiiz",
        "slug": "noiiz",
        "developer": "Noiiz",
        "category": "sampler",
        "price": "Subscription",
        "priceType": "subscription",
        "description": "A subscription-based sample platform offering a growing library of royalty-free loops, one-shots, and MIDI files across electronic and contemporary genres. Features an integrated plugin browser.",
        "url": "https://www.noiiz.com/",
        "rating": 4.4,
        "ratingCount": 370,
    },
    {
        "name": "Noiiz Classic",
        "slug": "noiiz-classic",
        "developer": "Noiiz",
        "category": "sampler",
        "price": "$29",
        "priceType": "paid",
        "description": "A curated collection of classic and foundational sample content from the Noiiz library, available as a one-time purchase. Covers essential loops and one-shots for electronic production.",
        "url": "https://www.noiiz.com/classic",
        "rating": 4.3,
        "ratingCount": 195,
    },
    {
        "name": "Capsule Audio",
        "slug": "capsule-audio",
        "developer": "Capsule Audio",
        "category": "sampler",
        "price": "$29",
        "priceType": "paid",
        "description": "A boutique sample pack label focusing on high-quality, deeply curated content for house, techno, and electronic music producers. Known for its meticulous sound design and musicality.",
        "url": "https://www.capsuleaudio.com/",
        "rating": 4.4,
        "ratingCount": 210,
    },
    {
        "name": "Black Octopus Sound",
        "slug": "black-octopus-sound",
        "developer": "Black Octopus Sound",
        "category": "sampler",
        "price": "$29",
        "priceType": "paid",
        "description": "A sample pack publisher with a strong focus on bass music, future bass, and electronic music production. Known for its energetic, mix-ready sound design content.",
        "url": "https://blackoctopus-sound.com/",
        "rating": 4.5,
        "ratingCount": 390,
    },
    {
        "name": "Cymatics",
        "slug": "cymatics",
        "developer": "Cymatics",
        "category": "sampler",
        "price": "$29",
        "priceType": "paid",
        "description": "A popular sample pack brand known for high-quality trap, hip-hop, and electronic music loops and one-shots. Offers a mix of free and premium packs across a range of modern genres.",
        "url": "https://cymatics.fm/",
        "rating": 4.5,
        "ratingCount": 680,
    },
    {
        "name": "KSHMR Sample Pack",
        "slug": "kshmr-sample-pack",
        "developer": "KSHMR / Splice",
        "category": "sampler",
        "price": "Subscription",
        "priceType": "subscription",
        "description": "A curated sample pack by superstar DJ/producer KSHMR available through Splice, featuring world-influenced EDM loops, one-shots, and signature bass sounds.",
        "url": "https://splice.com/sounds/packs/kshmr",
        "rating": 4.6,
        "ratingCount": 540,
    },
    {
        "name": "Vengeance Sound Ultimate Clubsounds",
        "slug": "vengeance-sound-ultimate-clubsounds",
        "developer": "Vengeance Sound",
        "category": "sampler",
        "price": "$79",
        "priceType": "paid",
        "description": "A foundational sample pack from Vengeance Sound covering classic club music genres including trance, house, and electro. An industry-standard resource for European EDM production since the 2000s.",
        "url": "https://www.vengeance-sound.com/",
        "rating": 4.5,
        "ratingCount": 720,
    },
    {
        "name": "Vengeance Producer Suite",
        "slug": "vengeance-producer-suite",
        "developer": "Vengeance Sound",
        "category": "sampler",
        "price": "$199",
        "priceType": "paid",
        "description": "A comprehensive bundle from Vengeance Sound including multiple sample packs and the Avenger synthesizer plugin. A complete production toolkit for electronic music producers.",
        "url": "https://www.vengeance-sound.com/",
        "rating": 4.6,
        "ratingCount": 590,
    },

    # --- Drum Machines / Hardware Emulations ---
    {
        "name": "Arturia DrumBrute Impact",
        "slug": "arturia-drumbrute-impact",
        "developer": "Arturia",
        "category": "drums",
        "price": "$299",
        "priceType": "paid",
        "description": "A compact analog drum machine with ten fully analog drum voices, a color-coded step sequencer, and real-time performance controls. Ideal for live performance and analog drum sound design.",
        "url": "https://www.arturia.com/products/hardware-synths/drumbrute-impact/overview",
        "rating": 4.6,
        "ratingCount": 870,
    },
    {
        "name": "Roland TR-808",
        "slug": "roland-tr-808",
        "developer": "Roland",
        "category": "drums",
        "price": "$1999",
        "priceType": "paid",
        "description": "The legendary vintage analog drum machine that defined decades of popular music production. The TR-808's kick drum, hi-hat, and clap sounds remain culturally iconic and widely emulated.",
        "url": "https://www.roland.com/global/categories/rhythm/rhythm-composers/",
        "rating": 5.0,
        "ratingCount": 1980,
    },
    {
        "name": "Roland TR-909",
        "slug": "roland-tr-909",
        "developer": "Roland",
        "category": "drums",
        "price": "$2499",
        "priceType": "paid",
        "description": "A vintage analog/PCM drum machine that became the defining sound of house and techno music. The TR-909's open hi-hat and snare are among the most recognizable sounds in electronic music history.",
        "url": "https://www.roland.com/global/categories/rhythm/rhythm-composers/",
        "rating": 5.0,
        "ratingCount": 1750,
    },
    {
        "name": "Elektron Digitakt",
        "slug": "elektron-digitakt",
        "developer": "Elektron",
        "category": "drums",
        "price": "$799",
        "priceType": "paid",
        "description": "A compact digital drum computer and sampler with Elektron's powerful step sequencer and parameter locking system. Capable of complex rhythmic programming and real-time performance manipulation.",
        "url": "https://www.elektron.se/en/digitakt-explorer",
        "rating": 4.8,
        "ratingCount": 1420,
    },
    {
        "name": "Elektron Analog Rytm MKII",
        "slug": "elektron-analog-rytm-mkii",
        "developer": "Elektron",
        "category": "drums",
        "price": "$1699",
        "priceType": "paid",
        "description": "Elektron's flagship drum machine combining analog synthesis with sample playback and the powerful Elektron sequencer. The definitive hardware drum machine for live electronic performance.",
        "url": "https://www.elektron.se/en/analog-rytm-explorer",
        "rating": 4.9,
        "ratingCount": 980,
    },
    {
        "name": "Vermona DRM1 MKIV",
        "slug": "vermona-drm1-mkiv",
        "developer": "Vermona",
        "category": "drums",
        "price": "$899",
        "priceType": "paid",
        "description": "A fully analog drum synthesizer module with eight discrete analog voice channels and extensive CV/gate connectivity. Known for its raw, aggressive analog drum character.",
        "url": "https://www.vermona.com/en/products/drums-percussion/product/drm1-mkiv/",
        "rating": 4.7,
        "ratingCount": 390,
    },
    {
        "name": "Korg Volca Beats",
        "slug": "korg-volca-beats",
        "developer": "Korg",
        "category": "drums",
        "price": "$149",
        "priceType": "paid",
        "description": "A compact, affordable analog drum machine from Korg's Volca series featuring six analog percussion voices and a classic-style 16-step sequencer. Perfect for entry-level hardware drum programming.",
        "url": "https://www.korg.com/us/products/dj/volca_beats/",
        "rating": 4.4,
        "ratingCount": 760,
    },
    {
        "name": "Akai MPC One",
        "slug": "akai-mpc-one",
        "developer": "Akai Professional",
        "category": "drums",
        "price": "$699",
        "priceType": "paid",
        "description": "A standalone MPC production workstation with a color touchscreen, 16 velocity-sensitive pads, and deep sampling capabilities. Runs the full MPC software independently without a computer.",
        "url": "https://www.akaipro.com/mpc-one",
        "rating": 4.7,
        "ratingCount": 1180,
    },
    {
        "name": "Akai MPC Live II",
        "slug": "akai-mpc-live-ii",
        "developer": "Akai Professional",
        "category": "drums",
        "price": "$1199",
        "priceType": "paid",
        "description": "Akai's battery-powered standalone MPC workstation designed for mobile production and live performance. Features built-in monitors, an expanded touchscreen, and extensive connectivity.",
        "url": "https://www.akaipro.com/mpc-live-ii",
        "rating": 4.7,
        "ratingCount": 870,
    },
    {
        "name": "Roland TR-8S",
        "slug": "roland-tr-8s",
        "developer": "Roland",
        "category": "drums",
        "price": "$499",
        "priceType": "paid",
        "description": "A modern drum machine combining Roland's ACB analog circuit behavior modeling of classic TR machines with sample playback. Offers authentic TR-808 and TR-909 sounds alongside custom sample import.",
        "url": "https://www.roland.com/global/products/tr-8s/",
        "rating": 4.7,
        "ratingCount": 980,
    },
    {
        "name": "Behringer RD-8",
        "slug": "behringer-rd-8",
        "developer": "Behringer",
        "category": "drums",
        "price": "$299",
        "priceType": "paid",
        "description": "An affordable analog drum machine closely modeled after the Roland TR-808 with full analog voice circuits and individual audio outputs. A budget-friendly way to access classic 808 drum sounds.",
        "url": "https://www.behringer.com/product.html?modelCode=P0FY9",
        "rating": 4.4,
        "ratingCount": 690,
    },
    {
        "name": "Behringer RD-9",
        "slug": "behringer-rd-9",
        "developer": "Behringer",
        "category": "drums",
        "price": "$299",
        "priceType": "paid",
        "description": "An analog drum machine closely modeled after the Roland TR-909 featuring fully discrete analog voice circuits and individual audio outputs. Delivers classic TR-909 sounds at an accessible price.",
        "url": "https://www.behringer.com/product.html?modelCode=P0FY8",
        "rating": 4.4,
        "ratingCount": 580,
    },
    {
        "name": "Teenage Engineering Pocket Operator PO-32",
        "slug": "teenage-engineering-po-32",
        "developer": "Teenage Engineering",
        "category": "drums",
        "price": "$89",
        "priceType": "paid",
        "description": "A pocket-sized digital drum machine from Teenage Engineering with a built-in microphone for recording custom sounds and a 16-step sequencer. Uniquely transfers sounds via audio using the Sonic Charge Microtonic engine.",
        "url": "https://teenage.engineering/products/po/tonic",
        "rating": 4.5,
        "ratingCount": 540,
    },
]
