"""Bulk product generator - compact seed data expanded into full product objects."""
import re

def slugify(name):
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')

def make(name, dev, cat, price="49.99", pt="paid", desc=None):
    if not desc:
        desc = f"{name} by {dev} - professional {cat} tool for music production."
    return {
        "name": name, "slug": slugify(name), "developer": dev,
        "category": cat, "price": price, "priceType": pt,
        "description": desc, "url": f"https://{slugify(dev)}.com",
        "rating": 4.2, "ratingCount": 50,
    }

# Format: (name, developer, category, price, priceType)
# Compact seed data - each line = one product
SEEDS = [
    # --- Synths: lesser-known / niche ---
    ("Pigments 5", "Arturia", "synth", "199", "paid"),
    ("Bazille", "u-he", "synth", "149", "paid"),
    ("Hive 2", "u-he", "synth", "149", "paid"),
    ("Podolski", "u-he", "synth", "0", "free"),
    ("Triple Cheese", "u-he", "synth", "0", "free"),
    ("Tyrell N6", "u-he", "synth", "0", "free"),
    ("SynthMaster 2", "KV331 Audio", "synth", "99", "paid"),
    ("SynthMaster One", "KV331 Audio", "synth", "49", "paid"),
    ("SynthMaster Player", "KV331 Audio", "synth", "0", "free"),
    ("Aalto", "Madrona Labs", "synth", "99", "paid"),
    ("Kaivo", "Madrona Labs", "synth", "129", "paid"),
    ("Virta", "Madrona Labs", "synth", "79", "paid"),
    ("Surge XT", "Surge Synth Team", "synth", "0", "free"),
    ("Shortcircuit XT", "Surge Synth Team", "synth", "0", "free"),
    ("Odin 2", "TheWaveWarden", "synth", "0", "free"),
    ("Vital", "Matt Tytel", "synth", "0", "free"),
    ("Helm", "Matt Tytel", "synth", "0", "free"),
    ("Synth1", "Daichi Laboratory", "synth", "0", "free"),
    ("Dexed", "Digital Suburban", "synth", "0", "free"),
    ("OB-Xd", "discoDSP", "synth", "0", "free"),
    ("TAL-NoiseMaker", "TAL Software", "synth", "0", "free"),
    ("TAL-BassLine-101", "TAL Software", "synth", "60", "paid"),
    ("TAL-Mod", "TAL Software", "synth", "60", "paid"),
    ("TAL-Sampler", "TAL Software", "synth", "30", "paid"),
    ("TAL-DAC", "TAL Software", "synth", "60", "paid"),
    ("TAL-Pha", "TAL Software", "synth", "40", "paid"),
    ("Zebralette", "u-he", "synth", "0", "free"),
    ("ZebraHZ", "u-he", "synth", "199", "paid"),
    ("Repro-1", "u-he", "synth", "99", "paid"),
    ("Repro-5", "u-he", "synth", "99", "paid"),
    ("ACE", "u-he", "synth", "79", "paid"),
    ("Monark", "Native Instruments", "synth", "99", "paid"),
    ("Prism", "Native Instruments", "synth", "69", "paid"),
    ("Reaktor Spark", "Native Instruments", "synth", "49", "paid"),
    ("Form", "Native Instruments", "synth", "99", "paid"),
    ("Skanner XT", "Native Instruments", "synth", "49", "paid"),
    ("Rounds", "Native Instruments", "synth", "99", "paid"),
    ("Razor", "Native Instruments", "synth", "69", "paid"),
    ("Absynth 5", "Native Instruments", "synth", "99", "paid"),
    ("FM8", "Native Instruments", "synth", "99", "paid"),
    ("Super 8", "Native Instruments", "synth", "99", "paid"),
    ("Massive X", "Native Instruments", "synth", "149", "paid"),
    ("Kontakt 7 Player", "Native Instruments", "sampler", "0", "free"),
    ("PolyBrute V", "Arturia", "synth", "99", "paid"),
    ("Prophet-5 V", "Arturia", "synth", "99", "paid"),
    ("Prophet-VS V", "Arturia", "synth", "99", "paid"),
    ("CS-80 V", "Arturia", "synth", "99", "paid"),
    ("SEM V", "Arturia", "synth", "99", "paid"),
    ("ARP 2600 V", "Arturia", "synth", "99", "paid"),
    ("Synthi V", "Arturia", "synth", "99", "paid"),
    ("Buchla Easel V", "Arturia", "synth", "99", "paid"),
    ("Clavinet V", "Arturia", "synth", "99", "paid"),
    ("DX7 V", "Arturia", "synth", "99", "paid"),
    ("Emulator II V", "Arturia", "synth", "99", "paid"),
    ("Farfisa V", "Arturia", "synth", "99", "paid"),
    ("Jup-8 V", "Arturia", "synth", "99", "paid"),
    ("Matrix-12 V", "Arturia", "synth", "99", "paid"),
    ("Mellotron V", "Arturia", "synth", "99", "paid"),
    ("Modular V", "Arturia", "synth", "99", "paid"),
    ("OB-Xa V", "Arturia", "synth", "99", "paid"),
    ("Solina V", "Arturia", "synth", "99", "paid"),
    ("SQ80 V", "Arturia", "synth", "99", "paid"),
    ("Vocoder V", "Arturia", "synth", "99", "paid"),
    ("Wurli V", "Arturia", "synth", "99", "paid"),
    ("Mini V", "Arturia", "synth", "99", "paid"),
    ("Analog Lab V", "Arturia", "synth", "99", "paid"),
    ("Augmented STRINGS", "Arturia", "synth", "99", "paid"),
    ("Augmented VOICES", "Arturia", "synth", "99", "paid"),
    ("Augmented BRASS", "Arturia", "synth", "99", "paid"),
    ("Augmented WOODWINDS", "Arturia", "synth", "99", "paid"),
    ("Augmented GRAND PIANO", "Arturia", "synth", "99", "paid"),
    ("Cherry Audio Voltage Modular", "Cherry Audio", "synth", "49", "paid"),
    ("Cherry Audio Dreamsynth", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Harmonia", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio GX-80", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Mercury-6", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Memorymode", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio PS-20", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio DCO-106", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Polymode", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio MG-1 Plus", "Cherry Audio", "synth", "0", "free"),
    ("Cherry Audio Surrealistic MG-1", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Eight Voice", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Elka-X", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Miniverse", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Stardust 201", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Sines", "Cherry Audio", "synth", "39", "paid"),
    ("Cherry Audio Galactic Reverb", "Cherry Audio", "effects", "29", "paid"),
    ("IK Multimedia Syntronik 2", "IK Multimedia", "synth", "149", "paid"),
    ("IK Multimedia SampleTank 4", "IK Multimedia", "sampler", "149", "paid"),
    ("IK Multimedia Modo Drum", "IK Multimedia", "drums", "149", "paid"),
    ("IK Multimedia Modo Bass 2", "IK Multimedia", "synth", "149", "paid"),
    ("IK Multimedia Hammond B-3X", "IK Multimedia", "synth", "149", "paid"),
    ("IK Multimedia Lurssen Mastering Console", "IK Multimedia", "mastering", "149", "paid"),
    ("IK Multimedia T-RackS 5", "IK Multimedia", "mastering", "149", "paid"),
    ("IK Multimedia MixBox", "IK Multimedia", "effects", "99", "paid"),
    ("IK Multimedia AmpliTube 5 SE", "IK Multimedia", "guitar", "0", "free"),
    ("IK Multimedia CSR Classik Studio Reverb", "IK Multimedia", "effects", "79", "paid"),
    ("IK Multimedia Tape Machine Collection", "IK Multimedia", "effects", "99", "paid"),
    ("IK Multimedia EQ Collection", "IK Multimedia", "effects", "99", "paid"),
    ("IK Multimedia Comp Collection", "IK Multimedia", "effects", "99", "paid"),
    ("IK Multimedia Bus Comp Collection", "IK Multimedia", "effects", "79", "paid"),
    # --- Effects: niche/boutique ---
    ("Soundtheory Gullfoss", "Soundtheory", "effects", "199", "paid"),
    ("Wavesfactory Spectre", "Wavesfactory", "effects", "69", "paid"),
    ("Wavesfactory Trackspacer", "Wavesfactory", "effects", "59", "paid"),
    ("Wavesfactory Cassette", "Wavesfactory", "effects", "29", "paid"),
    ("Wavesfactory Echo Cat", "Wavesfactory", "effects", "39", "paid"),
    ("Wavesfactory SK10", "Wavesfactory", "effects", "29", "paid"),
    ("Wavesfactory SnareBuzz", "Wavesfactory", "effects", "0", "free"),
    ("Klanghelm MJUC jr.", "Klanghelm", "effects", "0", "free"),
    ("Klanghelm IVGI", "Klanghelm", "effects", "0", "free"),
    ("Klanghelm DC1A", "Klanghelm", "effects", "0", "free"),
    ("Klanghelm MJUC", "Klanghelm", "effects", "24", "paid"),
    ("Klanghelm SDRR 2", "Klanghelm", "effects", "24", "paid"),
    ("Klanghelm DC8C", "Klanghelm", "effects", "24", "paid"),
    ("Klanghelm VUMT 2", "Klanghelm", "effects", "24", "paid"),
    ("AudioThing Vinyl Strip", "AudioThing", "effects", "29", "paid"),
    ("AudioThing Fog Convolver", "AudioThing", "effects", "55", "paid"),
    ("AudioThing Speaker", "AudioThing", "effects", "39", "paid"),
    ("AudioThing Outer Space", "AudioThing", "effects", "39", "paid"),
    ("AudioThing Springs", "AudioThing", "effects", "55", "paid"),
    ("AudioThing Reels", "AudioThing", "effects", "45", "paid"),
    ("AudioThing Frostbite 2", "AudioThing", "effects", "45", "paid"),
    ("AudioThing Things Motor", "AudioThing", "effects", "29", "paid"),
    ("AudioThing Space Strip", "AudioThing", "effects", "29", "paid"),
    ("AudioThing Wires", "AudioThing", "effects", "55", "paid"),
    ("AudioThing Type A", "AudioThing", "effects", "29", "paid"),
    ("AudioThing Blindfold EQ", "AudioThing", "effects", "39", "paid"),
    ("AudioThing Hand Clapper", "AudioThing", "effects", "25", "paid"),
    ("AudioThing miniBit", "AudioThing", "synth", "15", "paid"),
    ("AudioThing Noises", "AudioThing", "synth", "39", "paid"),
    ("AudioThing Hats", "AudioThing", "drums", "25", "paid"),
    ("AudioThing SR-88", "AudioThing", "drums", "25", "paid"),
    ("AudioThing Latin Percussion", "AudioThing", "drums", "39", "paid"),
    ("AudioThing TX-101", "AudioThing", "synth", "25", "paid"),
    ("Unfiltered Audio BYOME", "Unfiltered Audio", "effects", "99", "paid"),
    ("Unfiltered Audio Indent 2", "Unfiltered Audio", "effects", "99", "paid"),
    ("Unfiltered Audio LION", "Unfiltered Audio", "synth", "99", "paid"),
    ("Unfiltered Audio Sandman Pro", "Unfiltered Audio", "effects", "79", "paid"),
    ("Unfiltered Audio SpecOps", "Unfiltered Audio", "effects", "99", "paid"),
    ("Unfiltered Audio Dent 2", "Unfiltered Audio", "effects", "79", "paid"),
    ("Unfiltered Audio Bass-Mint", "Unfiltered Audio", "effects", "49", "paid"),
    ("Unfiltered Audio G8", "Unfiltered Audio", "effects", "49", "paid"),
    ("Unfiltered Audio ZIP", "Unfiltered Audio", "effects", "49", "paid"),
    ("Unfiltered Audio Fault", "Unfiltered Audio", "effects", "49", "paid"),
    ("Sknote Disto", "Sknote", "effects", "59", "paid"),
    ("Sknote Roundtone", "Sknote", "effects", "49", "paid"),
    ("Sknote Strip2", "Sknote", "effects", "79", "paid"),
    ("Sknote SDC", "Sknote", "effects", "49", "paid"),
    ("Acustica Audio Aquamarine", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio Taupe", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio Gold", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio Coffee", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio Coral", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio Crimson", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio Sand", "Acustica Audio", "effects", "69", "paid"),
    ("Acustica Audio Ivory 3", "Acustica Audio", "effects", "149", "paid"),
    ("Acustica Audio Lava", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio White 2", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio Fire", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio Sienna", "Acustica Audio", "effects", "99", "paid"),
    ("Acustica Audio Ash", "Acustica Audio", "effects", "0", "free"),
    ("Acustica Audio Honey", "Acustica Audio", "effects", "99", "paid"),
    ("Sonnox Oxford Limiter", "Sonnox", "mastering", "130", "paid"),
    ("Sonnox Oxford Inflator", "Sonnox", "mastering", "130", "paid"),
    ("Sonnox Oxford EQ", "Sonnox", "effects", "200", "paid"),
    ("Sonnox Oxford Dynamics", "Sonnox", "effects", "200", "paid"),
    ("Sonnox Oxford Reverb", "Sonnox", "effects", "200", "paid"),
    ("Sonnox Oxford SuprEsser", "Sonnox", "effects", "130", "paid"),
    ("Sonnox Oxford TransMod", "Sonnox", "effects", "100", "paid"),
    ("Sonnox Oxford Envolution", "Sonnox", "effects", "130", "paid"),
    ("Sonnox Claro", "Sonnox", "effects", "99", "paid"),
    ("Brainworx bx_masterdesk", "Brainworx", "mastering", "149", "paid"),
    ("Brainworx bx_console Focusrite SC", "Brainworx", "effects", "149", "paid"),
    ("Brainworx bx_console SSL 4000 E", "Brainworx", "effects", "149", "paid"),
    ("Brainworx bx_console SSL 4000 G", "Brainworx", "effects", "149", "paid"),
    ("Brainworx bx_console AMEK 9099", "Brainworx", "effects", "149", "paid"),
    ("Brainworx bx_console N", "Brainworx", "effects", "149", "paid"),
    ("Brainworx bx_digital V3", "Brainworx", "effects", "199", "paid"),
    ("Brainworx bx_refinement", "Brainworx", "effects", "149", "paid"),
    ("Brainworx bx_saturator", "Brainworx", "effects", "99", "paid"),
    ("Brainworx bx_townhouse Buss Compressor", "Brainworx", "effects", "149", "paid"),
    ("Brainworx bx_XL V2", "Brainworx", "mastering", "99", "paid"),
    ("Brainworx bx_subsynth", "Brainworx", "effects", "99", "paid"),
    ("Brainworx bx_delay 2500", "Brainworx", "effects", "99", "paid"),
    ("Brainworx bx_meter", "Brainworx", "utility", "0", "free"),
    # --- Drums & Sample Packs ---
    ("GetGood Drums Modern & Massive", "GetGood Drums", "drums", "99", "paid"),
    ("GetGood Drums Matt Halpern Signature", "GetGood Drums", "drums", "99", "paid"),
    ("GetGood Drums One Kit Wonder Aggressive", "GetGood Drums", "drums", "49", "paid"),
    ("GetGood Drums One Kit Wonder Organic", "GetGood Drums", "drums", "49", "paid"),
    ("GetGood Drums Invasion", "GetGood Drums", "drums", "99", "paid"),
    ("GetGood Drums Smash & Grab", "GetGood Drums", "drums", "99", "paid"),
    ("GetGood Drums P IV Matt Halpern", "GetGood Drums", "drums", "99", "paid"),
    ("Room Sound Kurt Ballou Drums", "Room Sound", "drums", "99", "paid"),
    ("Room Sound Jay Maas Drums", "Room Sound", "drums", "99", "paid"),
    ("Room Sound Diamonds", "Room Sound", "drums", "49", "paid"),
    ("Steven Slate Drums 5.5", "Steven Slate", "drums", "99", "paid"),
    ("Steven Slate Trigger 2", "Steven Slate", "drums", "149", "paid"),
    ("XLN Audio Addictive Drums 2", "XLN Audio", "drums", "149", "paid"),
    ("XLN Audio Addictive Keys", "XLN Audio", "synth", "79", "paid"),
    ("XLN Audio XO", "XLN Audio", "drums", "99", "paid"),
    ("XLN Audio RC-20 Retro Color", "XLN Audio", "effects", "79", "paid"),
    ("XLN Audio Life", "XLN Audio", "drums", "79", "paid"),
    ("Toontrack EZdrummer 3", "Toontrack", "drums", "149", "paid"),
    ("Toontrack Superior Drummer 3", "Toontrack", "drums", "349", "paid"),
    ("Toontrack EZbass", "Toontrack", "synth", "149", "paid"),
    ("Toontrack EZkeys", "Toontrack", "synth", "149", "paid"),
    ("Toontrack EZmix 3", "Toontrack", "effects", "149", "paid"),
    ("BFD3", "FXpansion", "drums", "349", "paid"),
    ("Strike 2", "AIR Music Tech", "drums", "99", "paid"),
    ("AIR Music Tech Xpand!2", "AIR Music Tech", "synth", "49", "paid"),
    ("AIR Music Tech Hybrid 3", "AIR Music Tech", "synth", "49", "paid"),
    ("AIR Music Tech Loom II", "AIR Music Tech", "synth", "49", "paid"),
    ("AIR Music Tech Vacuum Pro", "AIR Music Tech", "synth", "49", "paid"),
    ("AIR Music Tech Mini Grand", "AIR Music Tech", "synth", "29", "paid"),
    ("AIR Music Tech Velvet 2", "AIR Music Tech", "synth", "29", "paid"),
    ("AIR Music Tech DB-33", "AIR Music Tech", "synth", "29", "paid"),
    ("AIR Music Tech Boom", "AIR Music Tech", "drums", "29", "paid"),
    # --- MIDI & Composition ---
    ("Scaler 2", "Plugin Boutique", "midi", "59", "paid"),
    ("Captain Chords", "Mixed In Key", "midi", "79", "paid"),
    ("Captain Melody", "Mixed In Key", "midi", "79", "paid"),
    ("Captain Deep", "Mixed In Key", "midi", "79", "paid"),
    ("Captain Beat", "Mixed In Key", "midi", "79", "paid"),
    ("Cthulhu", "Xfer Records", "midi", "39", "paid"),
    ("Riffer", "Audiomodern", "midi", "39", "paid"),
    ("Playbeat 3", "Audiomodern", "midi", "59", "paid"),
    ("Chordjam", "Audiomodern", "midi", "39", "paid"),
    ("Gatelab", "Audiomodern", "midi", "29", "paid"),
    ("Loopcloud", "Loopmasters", "utility", "0", "free"),
    ("Loopcloud PLAY", "Loopmasters", "sampler", "0", "free"),
    ("Loopcloud DRUM", "Loopmasters", "drums", "0", "free"),
    ("Splice Creator", "Splice", "utility", "0", "free"),
    ("Output Arcade", "Output", "synth", "9.99", "subscription"),
    ("Output Portal", "Output", "effects", "99", "paid"),
    ("Output Thermal", "Output", "effects", "99", "paid"),
    ("Output Movement", "Output", "effects", "99", "paid"),
    ("Output Exhale", "Output", "synth", "199", "paid"),
    ("Output Signal", "Output", "synth", "199", "paid"),
    ("Output Substance", "Output", "synth", "199", "paid"),
    ("Output REV", "Output", "synth", "149", "paid"),
    ("Output Analog Strings", "Output", "synth", "199", "paid"),
    ("Output Analog Brass & Winds", "Output", "synth", "199", "paid"),
    # --- Mastering & Metering ---
    ("iZotope Insight 2", "iZotope", "mastering", "199", "paid"),
    ("iZotope RX 10 Standard", "iZotope", "utility", "399", "paid"),
    ("iZotope RX 10 Advanced", "iZotope", "utility", "1199", "paid"),
    ("iZotope RX 10 Elements", "iZotope", "utility", "129", "paid"),
    ("iZotope Tonal Balance Control 2", "iZotope", "mastering", "99", "paid"),
    ("iZotope Neoverb", "iZotope", "effects", "99", "paid"),
    ("iZotope Trash", "iZotope", "effects", "49", "paid"),
    ("iZotope Stutter Edit 2", "iZotope", "effects", "99", "paid"),
    ("iZotope Vocal Doubler", "iZotope", "vocal", "0", "free"),
    ("iZotope Vinyl", "iZotope", "effects", "0", "free"),
    ("iZotope Ozone Imager", "iZotope", "mastering", "0", "free"),
    ("NUGEN Audio MasterCheck", "NUGEN Audio", "mastering", "99", "paid"),
    ("NUGEN Audio Visualizer", "NUGEN Audio", "utility", "199", "paid"),
    ("NUGEN Audio SEQ-ST", "NUGEN Audio", "effects", "99", "paid"),
    ("NUGEN Audio ISL 2", "NUGEN Audio", "mastering", "149", "paid"),
    ("NUGEN Audio Monofilter", "NUGEN Audio", "utility", "79", "paid"),
    ("NUGEN Audio Stereoizer", "NUGEN Audio", "utility", "79", "paid"),
    ("NUGEN Audio LM-Correct 2", "NUGEN Audio", "mastering", "249", "paid"),
    ("NUGEN Audio SigMod", "NUGEN Audio", "utility", "49", "paid"),
    ("NUGEN Audio Paragon", "NUGEN Audio", "effects", "499", "paid"),
    ("Youlean Loudness Meter 2", "Youlean", "utility", "0", "free"),
    ("Youlean Loudness Meter 2 Pro", "Youlean", "utility", "49", "paid"),
    ("MeterPlugs Perception", "MeterPlugs", "utility", "49", "paid"),
    ("MeterPlugs LCAST", "MeterPlugs", "utility", "49", "paid"),
    ("MeterPlugs Dynameter", "MeterPlugs", "utility", "29", "paid"),
    ("Waves WLM Plus", "Waves", "mastering", "49", "paid"),
    ("PSP Audioware Xenon", "PSP Audioware", "mastering", "149", "paid"),
    ("PSP Audioware InfiniStrip", "PSP Audioware", "effects", "149", "paid"),
    ("PSP Audioware MasterComp", "PSP Audioware", "mastering", "99", "paid"),
    ("PSP Audioware VintageWarmer 2", "PSP Audioware", "mastering", "99", "paid"),
    ("PSP Audioware Saturator", "PSP Audioware", "effects", "49", "paid"),
    ("PSP Audioware 2445", "PSP Audioware", "effects", "99", "paid"),
    ("PSP Audioware Nexcellence", "PSP Audioware", "effects", "59", "paid"),
    ("PSP Audioware oldTimer", "PSP Audioware", "effects", "49", "paid"),
    ("PSP Audioware springBox", "PSP Audioware", "effects", "49", "paid"),
    ("PSP Audioware pianoverb", "PSP Audioware", "effects", "0", "free"),
    ("PSP Audioware Neon HR", "PSP Audioware", "effects", "49", "paid"),
    ("PSP Audioware TripleMeter", "PSP Audioware", "utility", "0", "free"),
    # --- Guitar & Bass ---
    ("Neural DSP Archetype Nolly", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Archetype Plini", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Archetype Gojira", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Archetype Tim Henson", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Archetype Cory Wong", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Archetype Rabea", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Archetype Abasi", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Archetype Petrucci", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Tone King", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Soldano", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Omega Granophyre", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Parallax", "Neural DSP", "guitar", "99", "paid"),
    ("Neural DSP Darkglass Ultra", "Neural DSP", "guitar", "99", "paid"),
    ("ML Sound Lab Amped Roots Free", "ML Sound Lab", "guitar", "0", "free"),
    ("ML Sound Lab Amped Stevie T", "ML Sound Lab", "guitar", "59", "paid"),
    ("ML Sound Lab Amped Mark IIC+", "ML Sound Lab", "guitar", "59", "paid"),
    ("ML Sound Lab Amped ML5", "ML Sound Lab", "guitar", "59", "paid"),
    ("STL Tones AmpHub", "STL Tones", "guitar", "9.99", "subscription"),
    ("STL Tones Amphub MAX", "STL Tones", "guitar", "14.99", "subscription"),
    ("STL Tones Tonality Andy James", "STL Tones", "guitar", "99", "paid"),
    ("STL Tones Tonality Howard Benson", "STL Tones", "guitar", "99", "paid"),
    ("STL Tones Tonality Lasse Lammert", "STL Tones", "guitar", "99", "paid"),
    ("STL Tones Tonality Will Putney", "STL Tones", "guitar", "99", "paid"),
    ("Line 6 Helix Native", "Line 6", "guitar", "399", "paid"),
    ("Line 6 POD Farm 2.5", "Line 6", "guitar", "99", "paid"),
    ("Positive Grid BIAS FX 2", "Positive Grid", "guitar", "99", "paid"),
    ("Positive Grid BIAS Amp 2", "Positive Grid", "guitar", "99", "paid"),
    ("Positive Grid BIAS Pedal", "Positive Grid", "guitar", "59", "paid"),
    ("Overloud TH-U", "Overloud", "guitar", "199", "paid"),
    ("Overloud Gem Comp670", "Overloud", "effects", "79", "paid"),
    ("Overloud Gem EQ550", "Overloud", "effects", "79", "paid"),
    ("Overloud Gem EQ84", "Overloud", "effects", "79", "paid"),
    ("Overloud Gem Dopamine", "Overloud", "effects", "79", "paid"),
    ("Overloud Mark Studio 2", "Overloud", "guitar", "99", "paid"),
    ("Overloud Springage", "Overloud", "effects", "49", "paid"),
    ("Mercuriall Spark", "Mercuriall", "guitar", "0", "free"),
    ("Mercuriall Euphoria", "Mercuriall", "guitar", "49", "paid"),
    ("Mercuriall ReAxis", "Mercuriall", "guitar", "69", "paid"),
    ("Mercuriall Cab IR Collection", "Mercuriall", "guitar", "29", "paid"),
    ("Mercuriall SS-11X", "Mercuriall", "guitar", "49", "paid"),
    ("Mercuriall U530", "Mercuriall", "guitar", "49", "paid"),
    # --- Orchestral / Cinematic ---
    ("Spitfire Audio LABS", "Spitfire Audio", "sampler", "0", "free"),
    ("Spitfire Audio BBC Symphony Orchestra Discover", "Spitfire Audio", "sampler", "49", "paid"),
    ("Spitfire Audio BBC Symphony Orchestra Core", "Spitfire Audio", "sampler", "449", "paid"),
    ("Spitfire Audio BBC Symphony Orchestra Pro", "Spitfire Audio", "sampler", "999", "paid"),
    ("Spitfire Audio Albion ONE", "Spitfire Audio", "sampler", "449", "paid"),
    ("Spitfire Audio Albion Tundra", "Spitfire Audio", "sampler", "449", "paid"),
    ("Spitfire Audio Chamber Strings", "Spitfire Audio", "sampler", "449", "paid"),
    ("Spitfire Audio Originals Firewood Piano", "Spitfire Audio", "sampler", "29", "paid"),
    ("Spitfire Audio Originals Cinematic Frozen Strings", "Spitfire Audio", "sampler", "29", "paid"),
    ("Spitfire Audio Originals Epic Strings", "Spitfire Audio", "sampler", "29", "paid"),
    ("Spitfire Audio Originals Intimate Strings", "Spitfire Audio", "sampler", "29", "paid"),
    ("Spitfire Audio Originals Cinematic Percussion", "Spitfire Audio", "sampler", "29", "paid"),
    ("Spitfire Audio Originals Felt Piano", "Spitfire Audio", "sampler", "29", "paid"),
    ("Orchestral Tools Metropolis Ark 1", "Orchestral Tools", "sampler", "449", "paid"),
    ("Orchestral Tools Metropolis Ark 2", "Orchestral Tools", "sampler", "449", "paid"),
    ("Orchestral Tools Berlin Strings", "Orchestral Tools", "sampler", "799", "paid"),
    ("Orchestral Tools Berlin Woodwinds", "Orchestral Tools", "sampler", "599", "paid"),
    ("Orchestral Tools Berlin Brass", "Orchestral Tools", "sampler", "599", "paid"),
    ("Orchestral Tools Berlin Percussion", "Orchestral Tools", "sampler", "399", "paid"),
    ("Orchestral Tools Layers", "Orchestral Tools", "sampler", "0", "free"),
    ("EastWest Hollywood Orchestra Opus", "EastWest", "sampler", "29.99", "subscription"),
    ("EastWest Composer Cloud+", "EastWest", "sampler", "19.99", "subscription"),
    ("EastWest Hollywood Strings", "EastWest", "sampler", "599", "paid"),
    ("EastWest Hollywood Brass", "EastWest", "sampler", "599", "paid"),
    ("EastWest Hollywood Woodwinds", "EastWest", "sampler", "599", "paid"),
    ("EastWest Spaces II", "EastWest", "effects", "199", "paid"),
    ("EastWest RA", "EastWest", "sampler", "399", "paid"),
    ("EastWest Goliath", "EastWest", "sampler", "499", "paid"),
    ("EastWest Stormdrum 3", "EastWest", "sampler", "399", "paid"),
    ("EastWest Forbidden Planet", "EastWest", "sampler", "299", "paid"),
    ("Cinematic Studio Strings", "Cinematic Studio Series", "sampler", "399", "paid"),
    ("Cinematic Studio Brass", "Cinematic Studio Series", "sampler", "399", "paid"),
    ("Cinematic Studio Woodwinds", "Cinematic Studio Series", "sampler", "399", "paid"),
    ("Cinematic Studio Piano", "Cinematic Studio Series", "sampler", "249", "paid"),
    ("Cinematic Studio Solo Strings", "Cinematic Studio Series", "sampler", "399", "paid"),
    ("ProjectSAM Symphobia 4", "ProjectSAM", "sampler", "599", "paid"),
    ("ProjectSAM Orchestral Essentials 2", "ProjectSAM", "sampler", "299", "paid"),
    ("ProjectSAM Swing!", "ProjectSAM", "sampler", "399", "paid"),
    ("ProjectSAM True Strike", "ProjectSAM", "sampler", "299", "paid"),
    ("8Dio Anthology Strings", "8Dio", "sampler", "498", "paid"),
    ("8Dio Studio Sopranos", "8Dio", "sampler", "248", "paid"),
    ("8Dio Lacrimosa Epic Choir", "8Dio", "sampler", "248", "paid"),
    ("8Dio 1969 Steinway Piano", "8Dio", "sampler", "248", "paid"),
    ("8Dio Majestica", "8Dio", "sampler", "498", "paid"),
    ("8Dio Deep Solo Cello", "8Dio", "sampler", "98", "paid"),
    ("Heavyocity Gravity", "Heavyocity", "sampler", "449", "paid"),
    ("Heavyocity Mosaic Tape", "Heavyocity", "sampler", "99", "paid"),
    ("Heavyocity Punish", "Heavyocity", "effects", "99", "paid"),
    ("Heavyocity Novo Modern Strings", "Heavyocity", "sampler", "399", "paid"),
    ("Heavyocity Damage 2", "Heavyocity", "sampler", "349", "paid"),
    ("Heavyocity Forzo Modern Brass", "Heavyocity", "sampler", "399", "paid"),
    ("Heavyocity Vento Modern Woodwinds", "Heavyocity", "sampler", "399", "paid"),
    ("Cinesamples CineBrass", "Cinesamples", "sampler", "399", "paid"),
    ("Cinesamples CineStrings Core", "Cinesamples", "sampler", "399", "paid"),
    ("Cinesamples CineWinds Core", "Cinesamples", "sampler", "399", "paid"),
    ("Cinesamples CinePerc", "Cinesamples", "sampler", "399", "paid"),
    ("Cinesamples Piano in Blue", "Cinesamples", "sampler", "199", "paid"),
    ("Cinesamples Hollywoodwinds", "Cinesamples", "sampler", "199", "paid"),
    # --- Vocal ---
    ("Antares Auto-Tune Pro X", "Antares", "vocal", "399", "paid"),
    ("Antares Auto-Tune Artist", "Antares", "vocal", "199", "paid"),
    ("Antares Auto-Tune EFX+", "Antares", "vocal", "129", "paid"),
    ("Antares Auto-Tune Access", "Antares", "vocal", "99", "paid"),
    ("Antares Harmony Engine", "Antares", "vocal", "249", "paid"),
    ("Antares Mic Mod", "Antares", "vocal", "129", "paid"),
    ("Antares Throat", "Antares", "vocal", "129", "paid"),
    ("Antares Aspire", "Antares", "vocal", "129", "paid"),
    ("Antares AVOX 4", "Antares", "vocal", "399", "paid"),
    ("Antares Mutator", "Antares", "vocal", "129", "paid"),
    ("Antares Choir", "Antares", "vocal", "129", "paid"),
    ("Antares Warm", "Antares", "vocal", "59", "paid"),
    ("Celemony Melodyne 5 Essential", "Celemony", "vocal", "99", "paid"),
    ("Celemony Melodyne 5 Assistant", "Celemony", "vocal", "249", "paid"),
    ("Celemony Melodyne 5 Editor", "Celemony", "vocal", "499", "paid"),
    ("Celemony Melodyne 5 Studio", "Celemony", "vocal", "699", "paid"),
    ("Synchro Arts VocAlign Ultra", "Synchro Arts", "vocal", "289", "paid"),
    ("Synchro Arts VocAlign Project", "Synchro Arts", "vocal", "149", "paid"),
    ("Synchro Arts Revoice Pro 4", "Synchro Arts", "vocal", "599", "paid"),
    ("Synchro Arts RePitch", "Synchro Arts", "vocal", "99", "paid"),
    ("Waves Tune Real-Time", "Waves", "vocal", "49", "paid"),
    ("Waves OVox", "Waves", "vocal", "35", "paid"),
    ("Soundtoys Little AlterBoy", "Soundtoys", "vocal", "49", "paid"),
    ("Soundtoys PrimalTap", "Soundtoys", "effects", "49", "paid"),
    ("Soundtoys MicroShift", "Soundtoys", "effects", "49", "paid"),
    ("Soundtoys Sie-Q", "Soundtoys", "effects", "0", "free"),
    ("Soundtoys Radiator", "Soundtoys", "effects", "49", "paid"),
    ("Soundtoys Devil-Loc Deluxe", "Soundtoys", "effects", "49", "paid"),
    ("Soundtoys FilterFreak", "Soundtoys", "effects", "49", "paid"),
    ("Soundtoys PanMan", "Soundtoys", "effects", "49", "paid"),
    ("Soundtoys Tremolator", "Soundtoys", "effects", "49", "paid"),
    ("Soundtoys Phase Mistress", "Soundtoys", "effects", "49", "paid"),
    ("Soundtoys Crystallizer", "Soundtoys", "effects", "49", "paid"),
    # --- Experimental / Granular ---
    ("Arturia Efx FRAGMENTS", "Arturia", "effects", "99", "paid"),
    ("Arturia Efx REFRACT", "Arturia", "effects", "99", "paid"),
    ("Arturia Rev PLATE-140", "Arturia", "effects", "99", "paid"),
    ("Arturia Rev INTENSITY", "Arturia", "effects", "99", "paid"),
    ("Arturia Rev SPRING-636", "Arturia", "effects", "99", "paid"),
    ("Arturia Delay TAPE-201", "Arturia", "effects", "99", "paid"),
    ("Arturia Delay MEMORY-BRIGADE", "Arturia", "effects", "99", "paid"),
    ("Arturia Delay ETERNITY", "Arturia", "effects", "99", "paid"),
    ("Arturia Comp TUBE-STA", "Arturia", "effects", "99", "paid"),
    ("Arturia Comp VCA-65", "Arturia", "effects", "99", "paid"),
    ("Arturia Comp FET-76", "Arturia", "effects", "99", "paid"),
    ("Arturia Comp DIODE-609", "Arturia", "effects", "99", "paid"),
    ("Arturia Pre 1973", "Arturia", "effects", "99", "paid"),
    ("Arturia Pre V76", "Arturia", "effects", "99", "paid"),
    ("Arturia Pre TridA", "Arturia", "effects", "99", "paid"),
    ("Arturia Filter MINI", "Arturia", "effects", "99", "paid"),
    ("Arturia Filter M12", "Arturia", "effects", "99", "paid"),
    ("Arturia Filter SEM", "Arturia", "effects", "99", "paid"),
    ("Arturia Bus FORCE", "Arturia", "effects", "99", "paid"),
    ("Arturia Tape MELLO-FI", "Arturia", "effects", "99", "paid"),
    ("Arturia Dist COLDFIRE", "Arturia", "effects", "99", "paid"),
    ("Arturia Dist OPAMP-21", "Arturia", "effects", "99", "paid"),
    ("Arturia Dist TUBE-CULTURE", "Arturia", "effects", "99", "paid"),
    ("Arturia Phaser BI-TRON", "Arturia", "effects", "99", "paid"),
    ("Arturia Chorus JUN-6", "Arturia", "effects", "99", "paid"),
    ("Arturia Chorus DIMENSION-D", "Arturia", "effects", "99", "paid"),
    ("Arturia Flanger BL-20", "Arturia", "effects", "99", "paid"),
    ("Arturia Rotary CLS-222", "Arturia", "effects", "99", "paid"),
    ("GForce Oberheim OB-E", "GForce Software", "synth", "129", "paid"),
    ("GForce M-Tron Pro", "GForce Software", "synth", "129", "paid"),
    ("GForce Minimonsta 2", "GForce Software", "synth", "129", "paid"),
    ("GForce Oddity3", "GForce Software", "synth", "129", "paid"),
    ("GForce impOSCar3", "GForce Software", "synth", "89", "paid"),
    ("Rob Papen Blade 2", "Rob Papen", "synth", "99", "paid"),
    ("Rob Papen Go2", "Rob Papen", "synth", "39", "paid"),
    ("Rob Papen Blue III", "Rob Papen", "synth", "179", "paid"),
    ("Rob Papen Punch 2", "Rob Papen", "drums", "99", "paid"),
    ("Rob Papen RAW", "Rob Papen", "synth", "99", "paid"),
    ("Rob Papen SubBoomBass 2", "Rob Papen", "synth", "79", "paid"),
    ("Rob Papen Predator 3", "Rob Papen", "synth", "129", "paid"),
    ("Rob Papen RP-Verb 2", "Rob Papen", "effects", "79", "paid"),
    ("Rob Papen RP-Delay", "Rob Papen", "effects", "49", "paid"),
    ("Rob Papen RP-Distort", "Rob Papen", "effects", "39", "paid"),
    ("Rob Papen MasterMagic", "Rob Papen", "mastering", "39", "paid"),
    ("Rob Papen Prisma", "Rob Papen", "effects", "69", "paid"),
    ("D16 Group Repeater", "D16 Group", "effects", "49", "paid"),
    ("D16 Group Toraverb 2", "D16 Group", "effects", "39", "paid"),
    ("D16 Group Frontier", "D16 Group", "effects", "29", "paid"),
    ("D16 Group Antresol", "D16 Group", "effects", "29", "paid"),
    ("D16 Group Syntorus 2", "D16 Group", "effects", "39", "paid"),
    ("D16 Group Fazortan 2", "D16 Group", "effects", "29", "paid"),
    ("D16 Group Devastor 2", "D16 Group", "effects", "29", "paid"),
    ("D16 Group Redoptor 2", "D16 Group", "effects", "29", "paid"),
    ("D16 Group Tekturon", "D16 Group", "effects", "39", "paid"),
    ("D16 Group PunchBox", "D16 Group", "drums", "69", "paid"),
    ("D16 Group Drumazon 2", "D16 Group", "drums", "49", "paid"),
    ("D16 Group Nithonat", "D16 Group", "drums", "49", "paid"),
    ("D16 Group Nepheton 2", "D16 Group", "drums", "49", "paid"),
    ("D16 Group LuSH-2", "D16 Group", "synth", "79", "paid"),
    ("D16 Group Phoscyon 2", "D16 Group", "synth", "69", "paid"),
    # --- Utility / Analysis ---
    ("SPAN Plus", "Voxengo", "utility", "0", "free"),
    ("Voxengo SPAN", "Voxengo", "utility", "0", "free"),
    ("Voxengo MSED", "Voxengo", "utility", "0", "free"),
    ("Voxengo Boogex", "Voxengo", "guitar", "0", "free"),
    ("Voxengo OldSkoolVerb", "Voxengo", "effects", "0", "free"),
    ("Voxengo Sound Delay", "Voxengo", "utility", "0", "free"),
    ("Voxengo Tube Amp", "Voxengo", "effects", "0", "free"),
    ("Voxengo Elephant", "Voxengo", "mastering", "99", "paid"),
    ("Voxengo Polysquasher", "Voxengo", "mastering", "69", "paid"),
    ("Voxengo Marquis Compressor", "Voxengo", "effects", "79", "paid"),
    ("Voxengo GlissEQ", "Voxengo", "effects", "79", "paid"),
    ("Voxengo Deft Compressor", "Voxengo", "effects", "49", "paid"),
    ("Voxengo Warmifier", "Voxengo", "effects", "39", "paid"),
    ("Voxengo Crunchessor", "Voxengo", "effects", "49", "paid"),
    ("Voxengo Shinechilla", "Voxengo", "effects", "39", "paid"),
    ("Voxengo PHA-979", "Voxengo", "utility", "39", "paid"),
    ("Voxengo CurveEQ", "Voxengo", "effects", "89", "paid"),
    ("Voxengo HarmoniEQ", "Voxengo", "effects", "69", "paid"),
    ("Voxengo Pristine Space", "Voxengo", "effects", "99", "paid"),
    ("Voxengo r8brain PRO", "Voxengo", "utility", "49", "paid"),
    ("Plugin Alliance MEGA Bundle", "Plugin Alliance", "effects", "14.99", "subscription"),
    ("Slate Digital All Access Pass", "Slate Digital", "effects", "14.99", "subscription"),
    ("Slate Digital Virtual Mix Rack", "Slate Digital", "effects", "149", "paid"),
    ("Slate Digital Virtual Tape Machines", "Slate Digital", "effects", "149", "paid"),
    ("Slate Digital Virtual Console Collection", "Slate Digital", "effects", "149", "paid"),
    ("Slate Digital Fresh Air", "Slate Digital", "effects", "0", "free"),
    ("Slate Digital FG-X 2", "Slate Digital", "mastering", "149", "paid"),
    ("Slate Digital Verbsuite Classics", "Slate Digital", "effects", "149", "paid"),
    ("Slate Digital Infinity EQ", "Slate Digital", "effects", "149", "paid"),
    ("Slate Digital Custom Series", "Slate Digital", "effects", "149", "paid"),
    ("Slate Digital Eiosis AirEQ", "Slate Digital", "effects", "99", "paid"),
    ("Slate Digital MetaTune", "Slate Digital", "vocal", "149", "paid"),
    ("Kilohearts Phase Plant", "Kilohearts", "synth", "199", "paid"),
    ("Kilohearts Multipass", "Kilohearts", "effects", "99", "paid"),
    ("Kilohearts Snap Heap", "Kilohearts", "effects", "49", "paid"),
    ("Kilohearts Disperser", "Kilohearts", "effects", "29", "paid"),
    ("Kilohearts Carve EQ", "Kilohearts", "effects", "29", "paid"),
    ("Kilohearts kHs ONE", "Kilohearts", "synth", "0", "free"),
    ("Kilohearts Bitcrush", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Chorus", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Comb Filter", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Compressor", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Delay", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Distortion", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Dynamics", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Ensemble", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Filter", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Flanger", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Formant Filter", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Frequency Shifter", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Gain", "Kilohearts", "utility", "0", "free"),
    ("Kilohearts Gate", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Haas", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Ladder Filter", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Limiter", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Phaser", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Pitch Shifter", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Resonator", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Reverb", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Ring Mod", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Stereo", "Kilohearts", "utility", "0", "free"),
    ("Kilohearts Tape Stop", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Trance Gate", "Kilohearts", "effects", "0", "free"),
    ("Kilohearts Transient Shaper", "Kilohearts", "effects", "0", "free"),
    # --- More unique tools ---
    ("Goodhertz Vulf Compressor", "Goodhertz", "effects", "99", "paid"),
    ("Goodhertz Tiltshift", "Goodhertz", "effects", "95", "paid"),
    ("Goodhertz CanOpener Studio", "Goodhertz", "utility", "95", "paid"),
    ("Goodhertz Lossy", "Goodhertz", "effects", "39", "paid"),
    ("Goodhertz Tone Control", "Goodhertz", "effects", "59", "paid"),
    ("Goodhertz Midside", "Goodhertz", "utility", "59", "paid"),
    ("Goodhertz Faraday Limiter", "Goodhertz", "mastering", "95", "paid"),
    ("Goodhertz Wow Control", "Goodhertz", "effects", "95", "paid"),
    ("Goodhertz Panpot", "Goodhertz", "utility", "39", "paid"),
    ("Goodhertz Megaverb", "Goodhertz", "effects", "95", "paid"),
    ("Goodhertz Good Dither", "Goodhertz", "mastering", "39", "paid"),
    ("Goodhertz Lohi", "Goodhertz", "effects", "59", "paid"),
    ("Softube Console 1", "Softube", "effects", "399", "paid"),
    ("Softube Weiss DS1-MK3", "Softube", "mastering", "199", "paid"),
    ("Softube Tube-Tech CL 1B", "Softube", "effects", "199", "paid"),
    ("Softube Summit Audio TLA-100A", "Softube", "effects", "99", "paid"),
    ("Softube Harmonics", "Softube", "effects", "79", "paid"),
    ("Softube Saturation Knob", "Softube", "effects", "0", "free"),
    ("Softube American Class A", "Softube", "effects", "79", "paid"),
    ("Softube British Class A", "Softube", "effects", "79", "paid"),
    ("Softube SSL 4000 E Channel Strip", "Softube", "effects", "199", "paid"),
    ("Softube Drawmer 1973", "Softube", "effects", "99", "paid"),
    ("Softube Fix Flanger", "Softube", "effects", "49", "paid"),
    ("Softube Fix Phaser", "Softube", "effects", "49", "paid"),
    ("Softube Fix Doubler", "Softube", "effects", "49", "paid"),
    ("Softube Modular", "Softube", "synth", "199", "paid"),
    ("Softube Amp Room", "Softube", "guitar", "199", "paid"),
    ("Softube Marshall Plexi Super Lead", "Softube", "guitar", "99", "paid"),
    ("Softube Metal Amp Room", "Softube", "guitar", "99", "paid"),
    ("Softube Vintage Amp Room", "Softube", "guitar", "99", "paid"),
    ("Softube Bass Amp Room", "Softube", "guitar", "99", "paid"),
    ("Eventide Blackhole", "Eventide", "effects", "99", "paid"),
    ("Eventide MangledVerb", "Eventide", "effects", "99", "paid"),
    ("Eventide ShimmerVerb", "Eventide", "effects", "99", "paid"),
    ("Eventide Instant Phaser Mk II", "Eventide", "effects", "49", "paid"),
    ("Eventide Instant Flanger Mk II", "Eventide", "effects", "49", "paid"),
    ("Eventide MicroPitch", "Eventide", "effects", "49", "paid"),
    ("Eventide TriceraChorus", "Eventide", "effects", "49", "paid"),
    ("Eventide UltraChannel", "Eventide", "effects", "99", "paid"),
    ("Eventide Omnipressor", "Eventide", "effects", "99", "paid"),
    ("Eventide EChannel", "Eventide", "effects", "99", "paid"),
    ("Eventide Elevate", "Eventide", "mastering", "199", "paid"),
    ("Eventide SplitEQ", "Eventide", "effects", "99", "paid"),
    ("Eventide Physion", "Eventide", "effects", "199", "paid"),
    ("Eventide Fission", "Eventide", "effects", "199", "paid"),
    ("Eventide H3000 Factory", "Eventide", "effects", "249", "paid"),
    ("Eventide Anthology XII", "Eventide", "effects", "499", "paid"),
    ("Eventide CrushStation", "Eventide", "effects", "49", "paid"),
    # --- DAW Add-ons / Reason Rack Extensions / Max for Live ---
    ("Max for Live Convolution Reverb", "Ableton", "effects", "0", "free"),
    ("Max for Live Granulator II", "Ableton", "synth", "0", "free"),
    ("Max for Live Drift", "Ableton", "synth", "0", "free"),
    ("Max for Live Meld", "Ableton", "synth", "0", "free"),
    ("Max for Live DS Clang", "Ableton", "drums", "0", "free"),
    ("Max for Live DS Kick", "Ableton", "drums", "0", "free"),
    ("Max for Live DS HH", "Ableton", "drums", "0", "free"),
    ("Max for Live DS Snare", "Ableton", "drums", "0", "free"),
    ("Max for Live CV Tools", "Ableton", "midi", "0", "free"),
    ("Max for Live Connection Kit", "Ableton", "midi", "0", "free"),
    ("Propellerhead Reason Rack Plugin", "Reason Studios", "synth", "99", "paid"),
    ("Reason Europa", "Reason Studios", "synth", "99", "paid"),
    ("Reason Grain", "Reason Studios", "synth", "99", "paid"),
    ("Reason Complex-1", "Reason Studios", "synth", "99", "paid"),
    ("Reason Algoritm", "Reason Studios", "synth", "69", "paid"),
    ("Reason Parsec 2", "Reason Studios", "synth", "49", "paid"),
    ("Reason Radical Piano", "Reason Studios", "synth", "69", "paid"),
    ("Reason Objekt", "Reason Studios", "synth", "99", "paid"),
    ("Reason Scenic Hybrid Instrument", "Reason Studios", "synth", "69", "paid"),
    ("Reason Friktion", "Reason Studios", "synth", "69", "paid"),
    ("Reason Humana", "Reason Studios", "vocal", "69", "paid"),
    ("Reason A-List Acoustic Guitarist", "Reason Studios", "guitar", "69", "paid"),
    ("Reason A-List Electric Guitarist", "Reason Studios", "guitar", "69", "paid"),
    ("Reason Umpf Club Drums", "Reason Studios", "drums", "69", "paid"),
    ("Reason Umpf Retro Beats", "Reason Studios", "drums", "69", "paid"),
    ("Reason PX7 FM Synthesizer", "Reason Studios", "synth", "49", "paid"),
    # --- Steinberg ---
    ("Steinberg HALion 7", "Steinberg", "sampler", "349", "paid"),
    ("Steinberg HALion Sonic 7", "Steinberg", "sampler", "149", "paid"),
    ("Steinberg Groove Agent 5", "Steinberg", "drums", "149", "paid"),
    ("Steinberg Retrologue 2", "Steinberg", "synth", "99", "paid"),
    ("Steinberg Padshop 2", "Steinberg", "synth", "49", "paid"),
    ("Steinberg Backbone", "Steinberg", "drums", "99", "paid"),
    ("Steinberg Iconica Sketch", "Steinberg", "sampler", "99", "paid"),
    ("Steinberg SpectraLayers Pro 10", "Steinberg", "utility", "299", "paid"),
    ("Steinberg WaveLab Pro 12", "Steinberg", "mastering", "499", "paid"),
    ("Steinberg WaveLab Elements 12", "Steinberg", "mastering", "99", "paid"),
    ("Steinberg The Grand 3", "Steinberg", "synth", "149", "paid"),
    ("Steinberg Absolute 7", "Steinberg", "synth", "499", "paid"),
    # --- Roland ---
    ("Roland ZENOLOGY Pro", "Roland", "synth", "199", "paid"),
    ("Roland ZENOLOGY", "Roland", "synth", "0", "free"),
    ("Roland SRX ELECTRIC PIANO", "Roland", "synth", "29.99", "paid"),
    ("Roland SRX WORLD", "Roland", "synth", "29.99", "paid"),
    ("Roland SRX STRINGS", "Roland", "synth", "29.99", "paid"),
    ("Roland SRX BRASS", "Roland", "synth", "29.99", "paid"),
    ("Roland SRX ORCHESTRA", "Roland", "synth", "29.99", "paid"),
    ("Roland SRX PIANO", "Roland", "synth", "29.99", "paid"),
    ("Roland SRX STUDIO", "Roland", "synth", "29.99", "paid"),
    ("Roland SRX DRUM", "Roland", "drums", "29.99", "paid"),
    ("Roland JD-800 Model Expansion", "Roland", "synth", "49.99", "paid"),
    ("Roland JUNO-106 Model Expansion", "Roland", "synth", "49.99", "paid"),
    ("Roland JUPITER-8 Model Expansion", "Roland", "synth", "49.99", "paid"),
    ("Roland JX-8P Model Expansion", "Roland", "synth", "49.99", "paid"),
    ("Roland SH-101 Model Expansion", "Roland", "synth", "49.99", "paid"),
    ("Roland TB-303 Model Expansion", "Roland", "synth", "49.99", "paid"),
    ("Roland TR-808 Software Rhythm Composer", "Roland", "drums", "19.99", "paid"),
    ("Roland TR-909 Software Rhythm Composer", "Roland", "drums", "19.99", "paid"),
    ("Roland TR-606 Software Rhythm Composer", "Roland", "drums", "19.99", "paid"),
    # --- Korg ---
    ("Korg Collection 4 Bundle", "Korg", "synth", "399", "paid"),
    ("Korg MS-20 Plugin", "Korg", "synth", "49.99", "paid"),
    ("Korg Polysix Plugin", "Korg", "synth", "49.99", "paid"),
    ("Korg Mono/Poly Plugin", "Korg", "synth", "49.99", "paid"),
    ("Korg M1 Plugin", "Korg", "synth", "49.99", "paid"),
    ("Korg Wavestation Plugin", "Korg", "synth", "49.99", "paid"),
    ("Korg MDE-X Plugin", "Korg", "effects", "19.99", "paid"),
    ("Korg ARP Odyssey Plugin", "Korg", "synth", "49.99", "paid"),
    ("Korg MiniKORG 700S Plugin", "Korg", "synth", "49.99", "paid"),
    ("Korg Prophecy Plugin", "Korg", "synth", "49.99", "paid"),
    ("Korg Triton Plugin", "Korg", "synth", "49.99", "paid"),
    ("Korg modwave native", "Korg", "synth", "49.99", "paid"),
    ("Korg opsix native", "Korg", "synth", "49.99", "paid"),
    ("Korg minilogue xd native", "Korg", "synth", "49.99", "paid"),
    # --- Misc unique tools ---
    ("Izotope Exponential Audio PhoenixVerb", "iZotope", "effects", "99", "paid"),
    ("Izotope Exponential Audio Stratus", "iZotope", "effects", "199", "paid"),
    ("Izotope Exponential Audio Nimbus", "iZotope", "effects", "199", "paid"),
    ("Izotope Exponential Audio R4", "iZotope", "effects", "299", "paid"),
    ("Izotope Exponential Audio Symphony", "iZotope", "effects", "299", "paid"),
    ("Izotope Exponential Audio Excalibur", "iZotope", "effects", "199", "paid"),
    ("Acon Digital Acoustica", "Acon Digital", "mastering", "199", "paid"),
    ("Acon Digital Equalize 2", "Acon Digital", "effects", "49", "paid"),
    ("Acon Digital Verberate 2", "Acon Digital", "effects", "49", "paid"),
    ("Acon Digital DeVerberate 3", "Acon Digital", "effects", "99", "paid"),
    ("Acon Digital Multiply", "Acon Digital", "effects", "0", "free"),
    ("Acon Digital DeFilter", "Acon Digital", "effects", "49", "paid"),
    ("Acon Digital Extract:Dialogue", "Acon Digital", "vocal", "99", "paid"),
    ("Acon Digital Restoration Suite 2", "Acon Digital", "utility", "149", "paid"),
    ("TDR Nova", "Tokyo Dawn Records", "effects", "0", "free"),
    ("TDR Kotelnikov", "Tokyo Dawn Records", "effects", "0", "free"),
    ("TDR SlickEQ", "Tokyo Dawn Records", "effects", "0", "free"),
    ("TDR VOS SlickEQ GE", "Tokyo Dawn Records", "effects", "50", "paid"),
    ("TDR Kotelnikov GE", "Tokyo Dawn Records", "effects", "50", "paid"),
    ("TDR Nova GE", "Tokyo Dawn Records", "effects", "50", "paid"),
    ("TDR Limiter 6 GE", "Tokyo Dawn Records", "mastering", "50", "paid"),
    ("TDR Molot GE", "Tokyo Dawn Records", "effects", "50", "paid"),
    ("Tone2 Icarus 2", "Tone2", "synth", "149", "paid"),
    ("Tone2 Gladiator 3", "Tone2", "synth", "149", "paid"),
    ("Tone2 Saurus 2", "Tone2", "synth", "99", "paid"),
    ("Tone2 Nemesis", "Tone2", "synth", "99", "paid"),
    ("Tone2 RayBlaster 2", "Tone2", "synth", "99", "paid"),
    ("Tone2 FireBird 2", "Tone2", "synth", "79", "paid"),
    ("Tone2 ElectraX", "Tone2", "synth", "129", "paid"),
    ("Tone2 Warmverb", "Tone2", "effects", "29", "paid"),
    ("Tone2 BiFilter 2", "Tone2", "effects", "29", "paid"),
    ("MeldaProduction MFreeFXBundle", "MeldaProduction", "effects", "0", "free"),
    ("MeldaProduction MCompletBundle", "MeldaProduction", "effects", "999", "paid"),
    ("MeldaProduction MSuperLooper", "MeldaProduction", "utility", "99", "paid"),
    ("MeldaProduction MDrummer", "MeldaProduction", "drums", "149", "paid"),
    ("MeldaProduction MAutoAlign", "MeldaProduction", "utility", "99", "paid"),
    ("MeldaProduction MStereoProcessor", "MeldaProduction", "utility", "0", "free"),
    ("MeldaProduction MAnalyzer", "MeldaProduction", "utility", "0", "free"),
    ("MeldaProduction MRecorder", "MeldaProduction", "utility", "0", "free"),
    ("MeldaProduction MStereoScope", "MeldaProduction", "utility", "0", "free"),
    ("MeldaProduction MNoiseGenerator", "MeldaProduction", "utility", "0", "free"),
    ("MeldaProduction MOscilloscope", "MeldaProduction", "utility", "0", "free"),
    ("MeldaProduction MTuner", "MeldaProduction", "utility", "0", "free"),
    ("Blue Cat Audio Patchwork", "Blue Cat Audio", "utility", "99", "paid"),
    ("Blue Cat Audio MB-7 Mixer", "Blue Cat Audio", "utility", "129", "paid"),
    ("Blue Cat Audio Axiom", "Blue Cat Audio", "guitar", "199", "paid"),
    ("Blue Cat Audio Late Replies", "Blue Cat Audio", "effects", "129", "paid"),
    ("Blue Cat Audio Destructor", "Blue Cat Audio", "effects", "99", "paid"),
    ("Blue Cat Audio Re-Guitar", "Blue Cat Audio", "guitar", "79", "paid"),
    ("Blue Cat Audio StereoScope Pro", "Blue Cat Audio", "utility", "49", "paid"),
    ("Blue Cat Audio FreqAnalyst Pro", "Blue Cat Audio", "utility", "49", "paid"),
    ("Blue Cat Audio Oscilloscope Multi", "Blue Cat Audio", "utility", "49", "paid"),
    ("Blue Cat Audio DP Meter Pro", "Blue Cat Audio", "utility", "49", "paid"),
    ("Blue Cat Audio Dynamics", "Blue Cat Audio", "effects", "99", "paid"),
    ("Blue Cat Audio Freeware Pack", "Blue Cat Audio", "effects", "0", "free"),
    ("Newfangled Audio Elevate", "Newfangled Audio", "mastering", "199", "paid"),
    ("Newfangled Audio Saturate", "Newfangled Audio", "effects", "49", "paid"),
    ("Newfangled Audio Generate", "Newfangled Audio", "synth", "99", "paid"),
    ("Newfangled Audio Pendulate", "Newfangled Audio", "synth", "0", "free"),
    ("Newfangled Audio EQuivocate", "Newfangled Audio", "effects", "99", "paid"),
    ("Denise Audio Perfect Room", "Denise Audio", "effects", "39", "paid"),
    ("Denise Audio God Mode", "Denise Audio", "effects", "39", "paid"),
    ("Denise Audio Bite Harder", "Denise Audio", "effects", "29", "paid"),
    ("Denise Audio Bad Tape", "Denise Audio", "effects", "29", "paid"),
    ("Denise Audio Poltergate", "Denise Audio", "effects", "29", "paid"),
    ("Denise Audio Noize 2", "Denise Audio", "effects", "39", "paid"),
    ("Denise Audio Dragon Fire", "Denise Audio", "effects", "39", "paid"),
    ("Denise Audio Slappy", "Denise Audio", "effects", "29", "paid"),
    ("Denise Audio Space Invader", "Denise Audio", "effects", "39", "paid"),
    ("Letimix GainMatch", "Letimix", "utility", "29", "paid"),
    ("DDMF PluginDoctor", "DDMF", "utility", "39", "paid"),
    ("DDMF MetaPlugin", "DDMF", "utility", "39", "paid"),
    ("DDMF LP10", "DDMF", "effects", "39", "paid"),
    ("DDMF NYCompressor", "DDMF", "effects", "29", "paid"),
    ("DDMF 6144", "DDMF", "effects", "39", "paid"),
    ("DDMF IIEQPro", "DDMF", "effects", "39", "paid"),
    ("DDMF NoLimits", "DDMF", "mastering", "39", "paid"),
    ("DDMF BridgeWize", "DDMF", "utility", "19", "paid"),
    ("Analog Obsession RARE", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession Britpressor", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession LALA", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession TuPre", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession Fetish", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession CHANNEV", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession BUSTERse", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession Merica", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession SSQ", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession DISTOX", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession Konsol", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession dBComp", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession PREBOX", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession SPECOMP", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession Dremux", "Analog Obsession", "effects", "0", "free"),
    ("Chowdhury DSP ChowTape Model", "Chowdhury DSP", "effects", "0", "free"),
    ("Chowdhury DSP BYOD", "Chowdhury DSP", "guitar", "0", "free"),
    ("Chowdhury DSP ChowCentaur", "Chowdhury DSP", "guitar", "0", "free"),
    ("Chowdhury DSP ChowMatrix", "Chowdhury DSP", "effects", "0", "free"),
    ("Chowdhury DSP ChowPhaser", "Chowdhury DSP", "effects", "0", "free"),
    ("Airwindows Monitoring", "Airwindows", "utility", "0", "free"),
    ("Airwindows Console7", "Airwindows", "effects", "0", "free"),
    ("Airwindows ToTape6", "Airwindows", "effects", "0", "free"),
    ("Airwindows Pressure5", "Airwindows", "effects", "0", "free"),
    ("Airwindows Iron Oxide 5", "Airwindows", "effects", "0", "free"),
    ("Airwindows DeRez2", "Airwindows", "effects", "0", "free"),
    ("Airwindows PurestDrive", "Airwindows", "effects", "0", "free"),
    ("Airwindows Density", "Airwindows", "effects", "0", "free"),
    ("Airwindows NC-17", "Airwindows", "effects", "0", "free"),
    ("Airwindows Galactic", "Airwindows", "effects", "0", "free"),
    ("HY-Plugins HY-Delay4", "HY-Plugins", "effects", "35", "paid"),
    ("HY-Plugins HY-Filter4", "HY-Plugins", "effects", "25", "paid"),
    ("HY-Plugins HY-Phaser2", "HY-Plugins", "effects", "0", "free"),
    ("HY-Plugins HY-Looper2", "HY-Plugins", "utility", "35", "paid"),
    ("HY-Plugins HY-MPS2", "HY-Plugins", "synth", "35", "paid"),
    ("HY-Plugins HY-Poly AU2", "HY-Plugins", "synth", "35", "paid"),
    ("HY-Plugins HY-SeqCollection2", "HY-Plugins", "midi", "29", "paid"),
    ("Valhalla DSP Supermassive", "Valhalla DSP", "effects", "0", "free"),
    ("Valhalla DSP FreqEcho", "Valhalla DSP", "effects", "0", "free"),
    ("Valhalla DSP SpaceModulator", "Valhalla DSP", "effects", "0", "free"),
    ("Valhalla DSP VintageVerb", "Valhalla DSP", "effects", "50", "paid"),
    ("Valhalla DSP Room", "Valhalla DSP", "effects", "50", "paid"),
    ("Valhalla DSP Plate", "Valhalla DSP", "effects", "50", "paid"),
    ("Valhalla DSP Shimmer", "Valhalla DSP", "effects", "50", "paid"),
    ("Valhalla DSP Delay", "Valhalla DSP", "effects", "50", "paid"),
    ("Valhalla DSP UberMod", "Valhalla DSP", "effects", "50", "paid"),
    ("FabFilter Pro-Q 3", "FabFilter", "effects", "179", "paid"),
    ("FabFilter Pro-L 2", "FabFilter", "mastering", "169", "paid"),
    ("FabFilter Pro-R 2", "FabFilter", "effects", "169", "paid"),
    ("FabFilter Pro-C 2", "FabFilter", "effects", "179", "paid"),
    ("FabFilter Pro-MB", "FabFilter", "effects", "179", "paid"),
    ("FabFilter Pro-DS", "FabFilter", "effects", "149", "paid"),
    ("FabFilter Saturn 2", "FabFilter", "effects", "154", "paid"),
    ("FabFilter Timeless 3", "FabFilter", "effects", "154", "paid"),
    ("FabFilter Volcano 3", "FabFilter", "effects", "154", "paid"),
    ("FabFilter Simplon", "FabFilter", "effects", "54", "paid"),
    ("FabFilter Micro", "FabFilter", "effects", "34", "paid"),
    ("FabFilter Twin 3", "FabFilter", "synth", "154", "paid"),
    ("FabFilter One", "FabFilter", "synth", "34", "paid"),
    ("FabFilter Total Bundle", "FabFilter", "effects", "899", "paid"),
    # --- More samplers/libraries ---
    ("Best Service Era II Vocal Codex", "Best Service", "sampler", "199", "paid"),
    ("Best Service Engine 2", "Best Service", "sampler", "0", "free"),
    ("Best Service Emotional Cello", "Best Service", "sampler", "199", "paid"),
    ("Best Service Ethno World 6", "Best Service", "sampler", "299", "paid"),
    ("Best Service Galaxy Vintage D", "Best Service", "sampler", "149", "paid"),
    ("Best Service Chris Hein Guitars", "Best Service", "sampler", "149", "paid"),
    ("Best Service Chris Hein Horns Vol 1", "Best Service", "sampler", "149", "paid"),
    ("Impact Soundworks Shreddage 3 Stratus", "Impact Soundworks", "sampler", "149", "paid"),
    ("Impact Soundworks Shreddage 3 Abyss", "Impact Soundworks", "sampler", "99", "paid"),
    ("Impact Soundworks Shreddage 3 Jupiter", "Impact Soundworks", "sampler", "129", "paid"),
    ("Impact Soundworks Super Audio Cart", "Impact Soundworks", "sampler", "149", "paid"),
    ("Impact Soundworks Cosmos", "Impact Soundworks", "sampler", "79", "paid"),
    ("Impact Soundworks Groove Bias", "Impact Soundworks", "drums", "99", "paid"),
    ("Impact Soundworks Juggernaut", "Impact Soundworks", "sampler", "149", "paid"),
    ("Orange Tree Samples Evolution Electric Guitar Strawberry", "Orange Tree Samples", "sampler", "179", "paid"),
    ("Orange Tree Samples Evolution Acoustic Guitar Steel", "Orange Tree Samples", "sampler", "179", "paid"),
    ("Orange Tree Samples Evolution Rick 12", "Orange Tree Samples", "sampler", "179", "paid"),
    ("Orange Tree Samples Evolution Jazz Archtop", "Orange Tree Samples", "sampler", "179", "paid"),
    ("Orange Tree Samples CoreBass Pear", "Orange Tree Samples", "sampler", "99", "paid"),
    ("Ample Sound Ample Guitar M III", "Ample Sound", "sampler", "119", "paid"),
    ("Ample Sound Ample Guitar T III", "Ample Sound", "sampler", "119", "paid"),
    ("Ample Sound Ample Guitar LP III", "Ample Sound", "sampler", "119", "paid"),
    ("Ample Sound Ample Guitar SC III", "Ample Sound", "sampler", "119", "paid"),
    ("Ample Sound Ample Bass P III", "Ample Sound", "sampler", "119", "paid"),
    ("Ample Sound Ample Bass J III", "Ample Sound", "sampler", "119", "paid"),
    ("Ample Sound Ample Guitar M Lite II", "Ample Sound", "sampler", "0", "free"),
    ("Ample Sound Ample Percussion CloudDrum", "Ample Sound", "drums", "59", "paid"),
    ("Ample Sound Ample Guitar TC III", "Ample Sound", "sampler", "99", "paid"),
    ("Ample Sound Ample Metal Ray5", "Ample Sound", "sampler", "99", "paid"),
    ("Ample Sound Ample Metal Eclipse", "Ample Sound", "sampler", "129", "paid"),
    # --- Closing batch: 120 more unique entries ---
    ("Waldorf Largo", "Waldorf", "synth", "149", "paid"),
    ("Waldorf Nave", "Waldorf", "synth", "129", "paid"),
    ("Waldorf PPG Wave 3.V", "Waldorf", "synth", "99", "paid"),
    ("Waldorf Attack", "Waldorf", "drums", "79", "paid"),
    ("Waldorf D", "Waldorf", "synth", "49", "paid"),
    ("Waldorf Edition 2", "Waldorf", "synth", "99", "paid"),
    ("Waldorf Lector", "Waldorf", "vocal", "99", "paid"),
    ("Waldorf Streichfett Plugin", "Waldorf", "synth", "49", "paid"),
    ("Waldorf Blofeld Plugin", "Waldorf", "synth", "99", "paid"),
    ("Waldorf Quantum Plugin", "Waldorf", "synth", "199", "paid"),
    ("Waldorf Iridium Plugin", "Waldorf", "synth", "199", "paid"),
    ("Waldorf Zarenbourg", "Waldorf", "synth", "79", "paid"),
    ("2CAudio Aether", "2CAudio", "effects", "149", "paid"),
    ("2CAudio B2", "2CAudio", "effects", "149", "paid"),
    ("2CAudio Breeze 2", "2CAudio", "effects", "99", "paid"),
    ("2CAudio Kaleidoscope", "2CAudio", "effects", "149", "paid"),
    ("2CAudio Precedence", "2CAudio", "effects", "99", "paid"),
    ("Audiority Polaris", "Audiority", "effects", "49", "paid"),
    ("Audiority GrainSpace", "Audiority", "effects", "55", "paid"),
    ("Audiority The Abuser", "Audiority", "effects", "29", "paid"),
    ("Audiority Space Station UM282", "Audiority", "effects", "39", "paid"),
    ("Audiority XL305", "Audiority", "effects", "39", "paid"),
    ("Audiority Echoes", "Audiority", "effects", "39", "paid"),
    ("Audiority Pre X7", "Audiority", "effects", "29", "paid"),
    ("Audiority TS-1 Transient Shaper", "Audiority", "effects", "19", "paid"),
    ("Audiority BigGoat", "Audiority", "guitar", "0", "free"),
    ("Audiority L12X", "Audiority", "guitar", "49", "paid"),
    ("Pulsar Audio Mu", "Pulsar Audio", "effects", "99", "paid"),
    ("Pulsar Audio 1178", "Pulsar Audio", "effects", "99", "paid"),
    ("Pulsar Audio Smasher", "Pulsar Audio", "effects", "0", "free"),
    ("Pulsar Audio W495", "Pulsar Audio", "effects", "49", "paid"),
    ("Pulsar Audio P42", "Pulsar Audio", "effects", "99", "paid"),
    ("Pulsar Audio 8200", "Pulsar Audio", "effects", "99", "paid"),
    ("Pulsar Audio Echorec", "Pulsar Audio", "effects", "79", "paid"),
    ("Pulsar Audio Massive", "Pulsar Audio", "mastering", "149", "paid"),
    ("Credland Audio StereoSavage 2", "Credland Audio", "utility", "39", "paid"),
    ("Credland Audio BigClipper", "Credland Audio", "effects", "25", "paid"),
    ("Credland Audio Pink 2", "Credland Audio", "utility", "0", "free"),
    ("SocaLabs Wavetable", "SocaLabs", "synth", "0", "free"),
    ("SocaLabs Organ", "SocaLabs", "synth", "0", "free"),
    ("SocaLabs Drum Kit", "SocaLabs", "drums", "0", "free"),
    ("SocaLabs EQ", "SocaLabs", "effects", "0", "free"),
    ("Dead Duck Software Free Effects", "Dead Duck Software", "effects", "0", "free"),
    ("Dead Duck Software Deducktion", "Dead Duck Software", "synth", "0", "free"),
    ("LSP Plugins Parametric EQ", "LSP Plugins", "effects", "0", "free"),
    ("LSP Plugins Compressor", "LSP Plugins", "effects", "0", "free"),
    ("LSP Plugins Limiter", "LSP Plugins", "mastering", "0", "free"),
    ("LSP Plugins Gate", "LSP Plugins", "effects", "0", "free"),
    ("LSP Plugins Delay Compensator", "LSP Plugins", "utility", "0", "free"),
    ("LSP Plugins Oscillator", "LSP Plugins", "utility", "0", "free"),
    ("LSP Plugins Spectrum Analyzer", "LSP Plugins", "utility", "0", "free"),
    ("Analog Obsession YALA", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession Rhenium", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession Full Strip", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession Lovend", "Analog Obsession", "effects", "0", "free"),
    ("Analog Obsession ReLife", "Analog Obsession", "effects", "0", "free"),
    ("Baby Audio Spaced Out", "Baby Audio", "effects", "49", "paid"),
    ("Baby Audio Super VHS", "Baby Audio", "effects", "39", "paid"),
    ("Baby Audio Smooth Operator", "Baby Audio", "effects", "49", "paid"),
    ("Baby Audio Parallel Aggressor", "Baby Audio", "effects", "39", "paid"),
    ("Baby Audio I Heart NY", "Baby Audio", "effects", "39", "paid"),
    ("Baby Audio BA-1", "Baby Audio", "synth", "49", "paid"),
    ("Baby Audio Transit", "Baby Audio", "effects", "49", "paid"),
    ("Baby Audio TAIP", "Baby Audio", "effects", "49", "paid"),
    ("Baby Audio Comeback Kid", "Baby Audio", "effects", "49", "paid"),
    ("Baby Audio Crystalline", "Baby Audio", "effects", "49", "paid"),
    ("Baby Audio Atoms", "Baby Audio", "effects", "29", "paid"),
    ("UJAM Virtual Bassist ROYAL 2", "UJAM", "synth", "99", "paid"),
    ("UJAM Virtual Bassist DANDY 2", "UJAM", "synth", "99", "paid"),
    ("UJAM Virtual Bassist MELLOW 2", "UJAM", "synth", "99", "paid"),
    ("UJAM Virtual Guitarist IRON 2", "UJAM", "guitar", "99", "paid"),
    ("UJAM Virtual Guitarist SPARKLE 2", "UJAM", "guitar", "99", "paid"),
    ("UJAM Virtual Guitarist AMBER 2", "UJAM", "guitar", "99", "paid"),
    ("UJAM Virtual Guitarist SILK 2", "UJAM", "guitar", "99", "paid"),
    ("UJAM Virtual Drummer SOLID 2", "UJAM", "drums", "99", "paid"),
    ("UJAM Virtual Drummer HEAVY 2", "UJAM", "drums", "99", "paid"),
    ("UJAM Virtual Drummer PHAT 2", "UJAM", "drums", "99", "paid"),
    ("UJAM Virtual Drummer BRUTE 2", "UJAM", "drums", "99", "paid"),
    ("UJAM Beatmaker DOPE 2", "UJAM", "drums", "49", "paid"),
    ("UJAM Beatmaker VICE 2", "UJAM", "drums", "49", "paid"),
    ("UJAM Beatmaker HUSTLE 2", "UJAM", "drums", "49", "paid"),
    ("UJAM Beatmaker VOID 2", "UJAM", "drums", "49", "paid"),
    ("UJAM Finisher FLUXX", "UJAM", "effects", "69", "paid"),
    ("UJAM Finisher VOODOO", "UJAM", "effects", "69", "paid"),
    ("UJAM Finisher NEO", "UJAM", "effects", "69", "paid"),
    ("UJAM Finisher RETRO", "UJAM", "effects", "69", "paid"),
    ("UJAM Finisher BOOST", "UJAM", "mastering", "69", "paid"),
    ("Polyverse Music Wider", "Polyverse Music", "utility", "0", "free"),
    ("Polyverse Music Comet", "Polyverse Music", "effects", "99", "paid"),
    ("Polyverse Music Supermodal", "Polyverse Music", "effects", "99", "paid"),
    ("Polyverse Music Gatekeeper", "Polyverse Music", "effects", "99", "paid"),
    ("Polyverse Music I Wish", "Polyverse Music", "effects", "99", "paid"),
    ("Polyverse Music Manipulator", "Polyverse Music", "vocal", "99", "paid"),
    ("Polyverse Music Infected Mushroom Gatekeeper", "Polyverse Music", "effects", "49", "paid"),
    ("Cableguys ShaperBox 3", "Cableguys", "effects", "99", "paid"),
    ("Cableguys VolumeShaper 7", "Cableguys", "effects", "35", "paid"),
    ("Cableguys TimeShaper 3", "Cableguys", "effects", "35", "paid"),
    ("Cableguys FilterShaper XL", "Cableguys", "effects", "49", "paid"),
    ("Cableguys PanShaper 3", "Cableguys", "effects", "25", "paid"),
    ("Cableguys WideShaper 3", "Cableguys", "effects", "25", "paid"),
    ("Cableguys DriveShaper", "Cableguys", "effects", "35", "paid"),
    ("Cableguys NoiseShaper", "Cableguys", "effects", "25", "paid"),
    ("Cableguys CrushShaper", "Cableguys", "effects", "25", "paid"),
    ("Cableguys LiquidShaper", "Cableguys", "effects", "25", "paid"),
    ("Cableguys HalfTime", "Cableguys", "effects", "10", "paid"),
    ("SampleScience Amore Grand Piano", "SampleScience", "sampler", "0", "free"),
    ("SampleScience Analog Waveforms", "SampleScience", "synth", "0", "free"),
    ("SampleScience RÉMIDY Compressor", "SampleScience", "effects", "0", "free"),
    ("SampleScience UNO Synth", "SampleScience", "synth", "0", "free"),
    ("SampleScience CZ Synth", "SampleScience", "synth", "0", "free"),
    ("Fuse Audio Labs VCL-373", "Fuse Audio Labs", "effects", "39", "paid"),
    ("Fuse Audio Labs VCL-864", "Fuse Audio Labs", "effects", "39", "paid"),
    ("Fuse Audio Labs VPRE-73", "Fuse Audio Labs", "effects", "39", "paid"),
    ("Fuse Audio Labs VEQ-55A", "Fuse Audio Labs", "effects", "29", "paid"),
    ("Fuse Audio Labs RS-W2395C", "Fuse Audio Labs", "effects", "29", "paid"),
    ("Fuse Audio Labs VREV-666", "Fuse Audio Labs", "effects", "29", "paid"),
    ("Fuse Audio Labs F-59", "Fuse Audio Labs", "guitar", "0", "free"),
    ("Fuse Audio Labs VCS-1", "Fuse Audio Labs", "effects", "59", "paid"),
    ("BPB Dirty Filter", "Bedroom Producers Blog", "effects", "0", "free"),
    ("BPB Dirty VHS", "Bedroom Producers Blog", "effects", "0", "free"),
    ("BPB Saturator", "Bedroom Producers Blog", "effects", "0", "free"),
    ("Datsounds Hyperion Strings Micro", "Datsounds", "sampler", "0", "free"),
    ("Spitfire Audio Originals Mrs Mills Piano", "Spitfire Audio", "sampler", "29", "paid"),
    ("Spitfire Audio Originals Drum Comp", "Spitfire Audio", "sampler", "29", "paid"),
    ("Spitfire Audio Originals Jangle Box Piano", "Spitfire Audio", "sampler", "29", "paid"),
    ("Spitfire Audio Originals Cinematic Pads", "Spitfire Audio", "sampler", "29", "paid"),
]

PRODUCTS = [make(n, d, c, p, pt) for n, d, c, p, pt in SEEDS]
