"""Final catalog batch — covering niche developers, iOS apps, hardware synth software,
DJ tools, broadcast tools, game audio, and extended plugin families."""

def _p(name, slug, dev, cat, price, ptype, desc, url, rating, rc):
    return {"name":name,"slug":slug,"developer":dev,"category":cat,"price":price,
            "priceType":ptype,"description":desc,"url":url,"rating":float(rating),"ratingCount":int(rc)}

PRODUCTS = [
    # ─── WAVES (remaining catalog) ────────────────────────────────────────────
    _p("Waves LiveTrack","waves-livetrack","Waves","utility","Subscription","subscription","Real-time streaming audio toolkit for broadcast and online content.","https://www.waves.com/live",4.4,312),
    _p("Waves eMotion LV1","waves-emotion-lv1","Waves","utility","Subscription","subscription","Professional live mixing console with SoundGrid DSP for 64-channel mixing.","https://www.waves.com/mixers-racks/emotion-lv1",4.7,423),
    _p("Waves Spectrum","waves-spectrum","Waves","utility","$29","paid","Real-time spectrum analyzer with three views: spectrum, spectrogram, and levels.","https://www.waves.com/plugins/waves-spectrum",4.4,289),
    _p("Waves SoundGrid Impact Server","waves-soundgrid-impact","Waves","utility","$1499","paid","Hardware DSP server for real-time low-latency plugin processing in live settings.","https://www.waves.com/hardware/soundgrid-impact-server",4.7,156),
    _p("Waves Bass Fingers","waves-bass-fingers","Waves","sampler","$49","paid","Bass guitar instrument with fingerstyle, slap, and picked articulations.","https://www.waves.com/plugins/bass-fingers",4.4,289),
    _p("Waves Electric 88 Piano","waves-electric-88-piano","Waves","sampler","$49","paid","Vintage electric piano instrument with tine-based modeling and amp simulation.","https://www.waves.com/plugins/electric-88-piano",4.4,312),
    _p("Waves Electric Grand 80","waves-electric-grand-80-2","Waves","sampler","$49","paid","Yamaha CP-80 electric grand piano with faithful acoustic/amplified character.","https://www.waves.com/plugins/electric-grand-80-piano",4.4,267),
    _p("Waves Manny Marroquin EQ","waves-manny-marroquin-eq","Waves","effects","$29","paid","5-band EQ with Manny Marroquin's signature studio-refined settings.","https://www.waves.com/plugins/manny-marroquin-eq",4.4,312),
    _p("Waves Manny Marroquin Tone Shaper","waves-manny-marroquin-tone-shaper","Waves","effects","$29","paid","Multiband dynamics processor with subtle tone shaping per frequency band.","https://www.waves.com/plugins/manny-marroquin-tone-shaper",4.4,267),
    _p("Waves Vocal Rider Live","waves-vocal-rider-live","Waves","vocal","$49","paid","Live performance vocal leveler for maintaining consistent vocal volume.","https://www.waves.com/plugins/vocal-rider",4.5,345),
    _p("Waves CLA MixHub","waves-cla-mixhub","Waves","effects","$299","paid","Virtual mixing desk with 64 channels and Chris Lord-Alge's console signal path.","https://www.waves.com/plugins/cla-mixhub",4.7,534),
    _p("Waves Nx Ambisonics","waves-nx-ambisonics","Waves","utility","$49","paid","Ambisonic monitoring and binaural rendering plugin for immersive audio.","https://www.waves.com/plugins/nx-ambisonics",4.5,234),
    _p("Waves Nx Head Tracker","waves-nx-head-tracker","Waves","utility","$49","paid","Head-tracking plugin for 3D audio monitoring on headphones.","https://www.waves.com/plugins/nx",4.4,312),
    _p("Waves MultiRack Native","waves-multirack-native","Waves","utility","$299","paid","Plugin rack host for live event sound with low latency SoundGrid processing.","https://www.waves.com/mixers-racks/multirack",4.6,267),
    _p("Waves Magma BD503","waves-magma-bd503","Waves","effects","$29","paid","Classic 500-series bus compressor emulation for mix bus glue.","https://www.waves.com/plugins/magma-bd503",4.5,234),
    _p("Waves Berzerk Distortion","waves-berzerk-distortion","Waves","effects","$29","paid","Extreme distortion plugin with multiple parallel distortion engines.","https://www.waves.com/plugins/berzerk",4.4,267),
    _p("Waves MV2","waves-mv2","Waves","effects","$29","paid","Low-level maximizer and compressor for bringing up low-level details.","https://www.waves.com/plugins/mv2",4.3,289),
    _p("Waves Butch Vig Vocals","waves-butch-vig-vocals","Waves","vocal","$49","paid","Vocal production plugin by Nirvana/Garbage producer Butch Vig.","https://www.waves.com/plugins/butch-vig-vocals",4.5,345),
    _p("Waves Chris Lord-Alge Guitar Slap","waves-cla-guitar-slap","Waves","guitar","$29","paid","Guitar slapback and room ambience plugin modeled on CLA's studio setup.","https://www.waves.com/plugins/cla-guitar",4.3,234),
    _p("Waves Submarine","waves-submarine","Waves","effects","$49","paid","Sub-harmonic synthesizer for extreme low-frequency enhancement.","https://www.waves.com/plugins/submarine",4.4,312),
    _p("Waves SoundShifter","waves-soundshifter","Waves","effects","$49","paid","Pitch and time-shifting plugin for audio post-production and music production.","https://www.waves.com/plugins/soundshifter",4.4,289),
    _p("Waves Doppler","waves-doppler","Waves","effects","$29","paid","Real-time Doppler effect plugin for creative panning and spatial movement.","https://www.waves.com/plugins/doppler",4.3,234),
    _p("Waves Tune Realtime Advanced","waves-tune-realtime-advanced","Waves","vocal","$49","paid","Advanced real-time pitch correction with formant control and scale locking.","https://www.waves.com/plugins/waves-tune-real-time",4.5,423),
    _p("Waves GTR Tuner","waves-gtr-tuner","Waves","utility","Free","free","Free high-precision chromatic tuner plugin for guitars and all instruments.","https://www.waves.com/plugins/gtr-tuner",4.3,534),
    _p("Waves MultiMod Rack","waves-multimod-rack","Waves","effects","$49","paid","Multi-modulation effects processor with 7 modulation types per channel.","https://www.waves.com/plugins/multimod-rack",4.3,189),
    _p("Waves Q10 Paragraphic EQ","waves-q10","Waves","effects","$29","paid","10-band parametric equalizer with high-resolution frequency shaping.","https://www.waves.com/plugins/q10-paragraphic-equalizer",4.4,289),
    _p("Waves H-EQ","waves-h-eq-legacy","Waves","effects","$49","paid","Legacy 7-band hybrid equalizer with vintage and modern filter responses.","https://www.waves.com/plugins/h-eq",4.5,356),
    _p("Waves L3-LL Multimaximizer","waves-l3-ll-multimaximizer","Waves","mastering","$49","paid","Low-latency variant of the L3 Multimaximizer for broadcast and live use.","https://www.waves.com/plugins/l3-multimaximizer",4.6,312),
    _p("Waves API 200 Series Bus Compressor","waves-api-200-bus","Waves","effects","$49","paid","API 2500-based bus compressor optimized for mix bus and stem mastering.","https://www.waves.com/plugins/api-2500",4.7,423),
    _p("Waves MaxxStereo","waves-maxxstereo","Waves","effects","$29","paid","Stereo enhancement plugin for adding width and spatial depth to mono sources.","https://www.waves.com/plugins/maxxstereo",4.3,234),

    # ─── PLUGIN ALLIANCE EXTENDED ─────────────────────────────────────────────
    _p("Brainworx bx_opto","bx-opto","Brainworx","effects","$99","paid","Optical compressor emulation based on the Teletronix LA-2A circuit.","https://www.plugin-alliance.com/en/products/bx_opto.html",4.6,312),
    _p("Brainworx bx_cleansweep V2","bx-cleansweep-v2","Brainworx","effects","$49","paid","High-pass and low-pass filter plugin for quick clean-up of mud and rumble.","https://www.plugin-alliance.com/en/products/bx_cleansweep_v2.html",4.5,267),
    _p("Brainworx bx_rockrack V3","bx-rockrack-v3","Brainworx","guitar","$299","paid","Guitar amp simulator with 12 classic and modern amp heads.","https://www.plugin-alliance.com/en/products/bx_rockrack_v3.html",4.6,345),
    _p("Brainworx bx_console Focusrite SC","bx-console-focusrite-sc","Brainworx","effects","$299","paid","Focusrite ISA 430 Studio Console channel strip emulation with TMT.","https://www.plugin-alliance.com/en/products/bx_console_focusrite_sc.html",4.7,423),
    _p("Plugin Alliance Complete Bundle","pa-complete-bundle","Plugin Alliance","effects","Subscription","subscription","All-access subscription to 200+ Plugin Alliance plugins and emulations.","https://www.plugin-alliance.com/en/products/pa_complete_bundle.html",4.8,712),
    _p("Lindell 7X-500","lindell-7x-500","Lindell Audio","effects","$99","paid","500-series style bus compressor emulation with punchy VCA character.","https://www.plugin-alliance.com/en/products/lindell_7x-500.html",4.6,267),
    _p("Lindell TE-100","lindell-te-100","Lindell Audio","effects","$99","paid","Tube EQ emulation with vintage transformer warmth and gentle frequency curves.","https://www.plugin-alliance.com/en/products/lindell_te-100.html",4.5,234),
    _p("Maag MAGNUM-K","maag-magnum-k","Maag Audio","mastering","$299","paid","Complete mastering chain with Maag signature AIR BAND equalizer.","https://www.plugin-alliance.com/en/products/maag_magnum-k.html",4.7,312),
    _p("Vertigo Sound VSM-3","vertigo-vsm-3","Vertigo Sound","effects","$299","paid","Mix bus saturation device with discrete transistor saturation circuits.","https://www.plugin-alliance.com/en/products/vertigo_sound_vsm-3.html",4.7,345),
    _p("Dangerous Music Compressor","dangerous-music-compressor","Dangerous Music","mastering","$249","paid","Mastering compressor with mid-side and stereo modes and sidechain EQ.","https://www.plugin-alliance.com/en/products/dangerous_compressor.html",4.7,289),
    _p("Noveltech Character","noveltech-character","Noveltech","effects","$149","paid","Intelligent harmonic enhancer adapting to the dynamic content of the signal.","https://www.plugin-alliance.com/en/products/noveltech_character.html",4.6,267),
    _p("Noveltech Vocal Enhancer","noveltech-vocal-enhancer","Noveltech","vocal","$99","paid","Adaptive vocal clarity plugin using intelligent harmonic analysis.","https://www.plugin-alliance.com/en/products/noveltech_vocal_enhancer.html",4.5,234),
    _p("Elysia Karacter","elysia-karacter","Elysia","effects","$99","paid","Character saturation plugin with positive and negative feedback distortion.","https://www.plugin-alliance.com/en/products/elysia_karacter.html",4.6,312),
    _p("Acustica Tan 2","acustica-tan-2","Acustica Audio","effects","$149","paid","Classic British Trident-style console channel strip with vintage character.","https://www.acustica-audio.com/store/products/tan",4.6,245),
    _p("Acustica Titanium 3","acustica-titanium-3","Acustica Audio","mastering","$299","paid","Mastering-grade signal chain with legendary hardware emulation quality.","https://www.acustica-audio.com/store/products/titanium",4.7,312),
    _p("Acustica Emerald","acustica-emerald","Acustica Audio","effects","$149","paid","Neve 8078-inspired console channel strip with lush transformer saturation.","https://www.acustica-audio.com/store/products/emerald",4.7,289),
    _p("Acustica Diamond","acustica-diamond","Acustica Audio","mastering","$249","paid","SSL-inspired mastering chain with transparent processing and high resolution.","https://www.acustica-audio.com/store/products/diamond",4.6,267),

    # ─── IOS MUSIC APPS ───────────────────────────────────────────────────────
    _p("GarageBand iOS","garageband-ios","Apple","daw","Free","free","Full-featured DAW for iPhone and iPad with Touch Instruments and Live Loops.","https://apps.apple.com/us/app/garageband/id408709785",4.6,2000),
    _p("Cubasis 3","cubasis-3","Steinberg","daw","$49","paid","Professional iOS DAW with full MIDI editing, audio recording, and mixer.","https://www.steinberg.net/cubasis/",4.7,712),
    _p("Auria Pro","auria-pro","WaveMachine Labs","daw","$49","paid","Professional iPad DAW with 48 tracks, AAX/VST plugin support, and Dropbox sync.","https://apps.apple.com/us/app/auria-pro/id974947172",4.6,312),
    _p("NanoStudio 2","nanostudio-2","Blip Interactive","daw","$19","paid","Full-featured iOS DAW with synthesizers, sampling, and MIDI sequencing.","https://www.blipinteractive.co.uk/nanostudio2/",4.7,456),
    _p("Korg iMS-20","korg-ims-20","Korg","synth","$19","paid","iOS version of the classic Korg MS-20 semi-modular synthesizer.","https://www.korg.com/us/products/software/korg_ims-20/",4.7,534),
    _p("Korg iElectribe","korg-ielectribe","Korg","drums","$9","paid","iOS version of the classic Korg Electribe drum machine and step sequencer.","https://www.korg.com/us/products/software/korg_ielectribe/",4.5,423),
    _p("Korg iMono/Poly","korg-imono-poly","Korg","synth","$19","paid","iOS emulation of the Korg Mono/Poly 4-VCO polyphonic synthesizer.","https://www.korg.com/us/products/software/korg_imono-poly/",4.6,312),
    _p("Moog Model D App","moog-model-d-app","Moog","synth","$14","paid","Official Moog Model D Minimoog synthesizer app for iOS.","https://apps.apple.com/us/app/model-d-synthesizer/id1200671890",4.8,712),
    _p("Moog Animoog Z","moog-animoog-z","Moog","synth","$14","paid","Anisotropic wavetable synthesizer for iPad with expressive MPE support.","https://apps.apple.com/us/app/animoog-z-synthesizer/id1586979584",4.7,456),
    _p("Thor for iOS","thor-ios","Reason Studios","synth","$14","paid","Thor polyphonic synthesizer for iPad and iPhone.","https://apps.apple.com/us/app/thor-synthesizer/id549762339",4.7,345),
    _p("Patterning 3","patterning-3","Olympia Noise Co","drums","$19","paid","Circular drum machine for iPhone and iPad with unique pattern sequencer.","https://olympianoiseco.com/apps/patterning/",4.7,456),
    _p("Steppolyarp","steppolyarp","Laurent Colson","midi","$7","paid","Advanced polyphonic step arpeggiator for iOS with MIDI output.","https://apps.apple.com/app/steppolyarp/id556387081",4.5,234),
    _p("Audiobus 3","audiobus-3","Audiobus Pty Ltd","utility","$9","paid","iOS audio routing app connecting multiple music apps in a signal chain.","https://audiob.us/",4.6,523),
    _p("AUM - Audio Mixer","aum-audio-mixer","Kymatica","utility","$19","paid","Flexible iOS audio mixer with signal routing for any combination of apps.","https://kymatica.com/apps/aum",4.8,634),
    _p("Drambo","drambo-ios","Beepstreet","daw","$19","paid","Modular synthesizer and groovebox for iPad with live performance workflow.","https://www.beepstreet.com/ios/drambo",4.8,534),
    _p("Xequence 2","xequence-2-ios","Audio Damage","midi","$19","paid","Full-featured piano roll and MIDI sequencer for iPhone and iPad.","https://audiodamage.com/pages/ios-apps",4.7,312),
    _p("Loopy Pro","loopy-pro","A Tasty Pixel","utility","$19","paid","Live looping performance tool for iOS with flexible routing and MIDI control.","https://loopypro.com/",4.8,534),
    _p("Samplr","samplr-ios","Marcos Alonso","sampler","$10","paid","Touch-based sample manipulation app for iPad with granular and loop modes.","https://apps.apple.com/us/app/samplr-touch-the-music/id576753482",4.7,423),
    _p("Borderlands Granular","borderlands-granular","Chris Carlson","experimental","$9","paid","Award-winning granular synthesizer app for iPad with touch interface.","https://apps.apple.com/us/app/borderlands-granular/id597317026",4.8,534),
    _p("iSEM","isem-ios","Arturia","synth","$9","paid","iOS version of Arturia's Oberheim SEM V synthesizer emulation.","https://www.arturia.com/products/ios/isem/overview",4.6,312),
    _p("iMini","imini-ios","Arturia","synth","$9","paid","iOS version of Arturia's Mini V Minimoog synthesizer emulation.","https://www.arturia.com/products/ios/imini/overview",4.7,367),
    _p("iSpark","ispark-ios","Arturia","drums","$9","paid","iOS version of Arturia's Spark drum machine with analog sounds.","https://www.arturia.com/products/ios/ispark/overview",4.5,267),
    _p("Bias Amp iOS","bias-amp-ios","Positive Grid","guitar","$49","paid","iOS guitar amp simulator with Amp Match technology for tone cloning.","https://www.positivegrid.com/bias-amp/",4.7,456),
    _p("JamUp Pro","jamup-pro","Positive Grid","guitar","$9","paid","Guitar amp and effects processor app for iOS with pro audio quality.","https://apps.apple.com/us/app/jamup-pro/id454225063",4.5,312),
    _p("Flux:FX","fluxfx-ios","Adrian Holovaty","experimental","$10","paid","Multi-effect iPad app designed for iPad Air with live performance workflow.","https://fluxfx.nl/",4.6,267),
    _p("Beatmaker 3","beatmaker-3","INTUA","daw","$24","paid","iOS DAW with sampling, synthesis, and full MPC-style workflow for iPad.","https://intua.net/beatmaker3/",4.7,523),
    _p("Koala Sampler","koala-sampler","Mackemist","sampler","$4","paid","Fun and accessible sampler app for quickly capturing and triggering sounds.","https://www.koalasampler.com/",4.7,712),

    # ─── DJ SOFTWARE ──────────────────────────────────────────────────────────
    _p("Serato DJ Pro","serato-dj-pro","Serato","daw","$99","paid","Professional DJ software with DVS support, 4 decks, and video mixing.","https://serato.com/dj/pro",4.7,923),
    _p("Traktor Pro 3","traktor-pro-3","Native Instruments","daw","$99","paid","Professional DJ software with Stem Deck technology and 4-deck mixing.","https://www.native-instruments.com/en/products/traktor/dj-software/traktor-pro-3/",4.7,834),
    _p("Rekordbox DJ","rekordbox-dj","Pioneer DJ","daw","Subscription","subscription","Professional DJ performance and library management software from Pioneer.","https://rekordbox.com/",4.7,712),
    _p("Virtual DJ 2023","virtual-dj-2023","Atomix Productions","daw","$29","paid","Popular DJ software with beatmatch AI, stem separation, and video mixing.","https://www.virtualdj.com/",4.5,834),
    _p("Mixxx","mixxx","Mixxx Team","daw","Free","free","Free open-source DJ software with beat detection and live remixing.","https://mixxx.org/",4.4,712),
    _p("djay Pro AI","djay-pro-ai","algoriddim","daw","Subscription","subscription","AI-powered DJ app for Mac, PC, iOS, and Android with stem separation.","https://www.algoriddim.com/djay-pro-ai",4.6,634),

    # ─── GAME AUDIO / MIDDLEWARE ──────────────────────────────────────────────
    _p("FMOD Studio","fmod-studio","Firelight Technologies","utility","Free","free","Professional game audio middleware used in thousands of shipped titles.","https://www.fmod.com/studio",4.8,534),
    _p("Wwise","audiokinetic-wwise","Audiokinetic","utility","Free","free","Industry-leading adaptive audio middleware for games and interactive media.","https://www.audiokinetic.com/products/wwise/",4.8,489),
    _p("Reaper for Game Audio","reaper-game-audio","Cockos","daw","$60","paid","REAPER DAW configured for game audio pipeline integration and SFX editing.","https://www.reaper.fm/",4.7,312),
    _p("Sonniss Game Audio Bundle","sonniss-game-audio","Sonniss","sampler","Free","free","Annual free game audio sample bundle with 10GB+ of royalty-free sounds.","https://sonniss.com/gameaudiogdc/",4.7,534),
    _p("SoundQ","soundq","Pro Sound Effects","utility","Free","free","Professional sound effects search and audition tool for sound designers.","https://www.prosoundeffects.com/soundq/",4.5,267),
    _p("AudioGaming AudioWeather","audiogaming-audioweather","AudioGaming","sampler","$299","paid","Procedural weather sound design engine for games and installations.","https://audiogaming.net/",4.6,156),
    _p("Krotos Igniter","krotos-igniter","Krotos","sampler","$399","paid","Vehicle sound design engine for video game and film sound design.","https://www.krotosaudio.com/igniter",4.7,234),

    # ─── RECORDING / RESTORATION ──────────────────────────────────────────────
    _p("iZotope RX 10 De-noise","izotope-rx-denoise","iZotope","utility","$99","paid","AI-powered dialogue and music de-noise module from the RX suite.","https://www.izotope.com/en/products/rx.html",4.7,534),
    _p("iZotope RX 10 De-reverb","izotope-rx-dereverb","iZotope","utility","$99","paid","Intelligent reverb removal module for cleaning up recorded audio.","https://www.izotope.com/en/products/rx.html",4.7,489),
    _p("iZotope RX 10 Dialogue Isolation","izotope-rx-dialogue-isolation","iZotope","utility","$199","paid","AI dialogue stem separation module for post-production cleanup.","https://www.izotope.com/en/products/rx.html",4.8,423),
    _p("Cedar Audio DNS One","cedar-dns-one","Cedar Audio","utility","$999","paid","Professional dialogue noise suppressor used in broadcast and post-production.","https://www.cedar-audio.com/products/dns_one.shtml",4.8,156),
    _p("SpectraLayers","spectralayers-elements","Steinberg","utility","$99","paid","Spectral audio editing tool for audio repair and stem separation.","https://www.steinberg.net/spectralayers/",4.6,345),
    _p("Audionamix XTRAX STEMS 3","audionamix-xtrax-stems","Audionamix","utility","$99","paid","AI-powered stem separation tool for isolating vocals, drums, and music.","https://audionamix.com/xtrax-stems/",4.5,345),
    _p("PhonicMind","phonicmind","PhonicMind","utility","Subscription","subscription","AI-powered vocal remover and stem separation service.","https://phonicmind.com/",4.3,312),

    # ─── LOUDNESS / BROADCAST ─────────────────────────────────────────────────
    _p("TC Electronic LM6 Mk2","tc-electronic-lm6","TC Electronic","utility","$249","paid","True-peak and loudness meter for broadcast, streaming, and mastering.","https://www.tcelectronic.com/",4.7,267),
    _p("Waves WLM Plus Loudness Meter","waves-wlm-plus","Waves","utility","$49","paid","Comprehensive loudness metering plugin following broadcast delivery standards.","https://www.waves.com/plugins/wlm-plus-loudness-meter",4.6,423),
    _p("Insight 2","izotope-insight-2","iZotope","utility","$99","paid","Multi-display audio analysis plugin with loudness, spectrum, and spatial views.","https://www.izotope.com/en/products/insight.html",4.7,534),
    _p("TC Electronic Clarity M","tc-clarity-m","TC Electronic","utility","$149","paid","Stereo loudness meter with EBU R128, ATSC A/85, and streaming standards.","https://www.tcelectronic.com/product/clarity-m/",4.6,312),
    _p("Youlean Loudness Meter 2","youlean-loudness-meter-2","Youlean","utility","Free","free","Free professional loudness meter with multiple standards and timeline view.","https://youlean.co/youlean-loudness-meter/",4.8,1234),

    # ─── PERFORMANCE / LIVE ───────────────────────────────────────────────────
    _p("Ableton Live 11 Standard","ableton-live-11-standard","Ableton","daw","$449","paid","Award-winning DAW for studio and live performance with clips and session view.","https://www.ableton.com/en/shop/live/",4.9,2000),
    _p("Ableton Live 11 Suite","ableton-live-11-suite","Ableton","daw","$749","paid","Complete Ableton bundle with Max for Live and all built-in instruments.","https://www.ableton.com/en/shop/live/",4.9,1789),
    _p("Ableton Live 11 Intro","ableton-live-11-intro","Ableton","daw","$99","paid","Entry-level version of Ableton Live with 16 tracks and essential instruments.","https://www.ableton.com/en/shop/live/",4.7,923),
    _p("Ableton Push 3","ableton-push-3","Ableton","utility","$799","paid","Standalone production instrument with MPE pads and integrated screen.","https://www.ableton.com/en/push/",4.8,834),
    _p("Mainstage 3","mainstage-3","Apple","daw","$29","paid","Live performance software for Mac with 100+ instruments and 400+ effects.","https://www.apple.com/mainstage/",4.7,712),
    _p("Gig Performer 4","gig-performer-4","Deskew Technologies","utility","$179","paid","Plugin host for live performance with low-latency and reliable failover.","https://gigperformer.com/",4.8,534),
    _p("Cantabile 4","cantabile-4","Topten Software","utility","$139","paid","VST host for live keyboard performance with song-based workflow.","https://www.cantabilesoftware.com/",4.7,345),
    _p("Camelot Pro","camelot-pro","Audio Modeling","utility","$99","paid","Performance rig manager for live keyboardists with virtual pedal boards.","https://audiomodeling.com/camelot-pro",4.6,267),
    _p("Setlist Helper","setlist-helper","iGigBook","utility","$12","paid","iOS setlist management app for live musicians with auto-scroll and MIDI.","https://www.isetlisthelper.com/",4.4,345),

    # ─── SYNTHESIS HARDWARE EMULATIONS ───────────────────────────────────────
    _p("Elektron Digitone Plugin","elektron-digitone","Elektron","synth","$399","paid","4-voice digital FM synthesizer with Elektron sequencer and MIDI track.","https://www.elektron.se/en/digitone-explorer",4.8,712),
    _p("Elektron Analog Four MKII","elektron-analog-four","Elektron","synth","$1499","paid","4-voice analog synthesizer with Elektron's powerful step sequencer.","https://www.elektron.se/en/analog-four-mkii-explorer",4.8,534),
    _p("Elektron Model:Cycles","elektron-model-cycles","Elektron","drums","$399","paid","FM drum synthesizer with 6 parts, dedicated sequencer, and effects.","https://www.elektron.se/en/modelcycles-explorer",4.7,456),
    _p("Moog Matriarch","moog-matriarch","Moog","synth","$1999","paid","4-voice semi-modular analog synthesizer with patch bay and arpeggiator.","https://www.moogmusic.com/products/matriarch",4.9,523),
    _p("Moog Subsequent 37","moog-subsequent-37","Moog","synth","$1799","paid","37-key semi-modular analog synthesizer with Sub Oscillator and expression inputs.","https://www.moogmusic.com/products/subsequent-37",4.9,634),
    _p("Sequential Prophet-6","sequential-prophet-6","Sequential","synth","$2999","paid","6-voice analog polyphonic synthesizer with vintage Prophet character.","https://www.sequential.com/product/prophet-6/",4.9,634),
    _p("Sequential OB-6","sequential-ob-6","Sequential","synth","$2999","paid","6-voice poly synth co-designed with Tom Oberheim with iconic OB sound.","https://www.sequential.com/product/ob-6/",4.9,567),
    _p("Sequential Prophet-X","sequential-prophet-x","Sequential","synth","$3999","paid","8-voice bi-timbral synth combining samples, synthesis, and analog filters.","https://www.sequential.com/product/prophet-x/",4.8,345),
    _p("Yamaha MONTAGE M8X","yamaha-montage-m8x","Yamaha","synth","$3999","paid","Flagship 88-key workstation with AWM2, FM-X, and AN-X synthesis engines.","https://usa.yamaha.com/products/music_production/synthesizers/montage_m/",4.8,423),
    _p("Yamaha MODX8+","yamaha-modx8-plus","Yamaha","synth","$1999","paid","88-key synthesizer with AWM2 and FM-X engines at an affordable price point.","https://usa.yamaha.com/products/music_production/synthesizers/modx/",4.7,456),
    _p("Nord Stage 4","nord-stage-4","Nord","synth","$4999","paid","Professional stage keyboard with Piano, Organ, and Synth sections.","https://www.nordkeyboards.com/products/nord-stage-4",4.9,567),
    _p("Nord Lead A1","nord-lead-a1","Nord","synth","$1699","paid","Analog modeling synthesizer with 4 morphable sound slots.","https://www.nordkeyboards.com/products/nord-lead-a1",4.8,489),
    _p("Access Virus TI2 Desktop","access-virus-ti2","Access Music","synth","$2499","paid","Powerful virtual analog synthesizer with Total Integration USB technology.","https://www.virus.info/",4.8,445),

    # ─── MASTERING EXTENDED ───────────────────────────────────────────────────
    _p("Ozone 9 Advanced (Legacy)","izotope-ozone-9-advanced","iZotope","mastering","$499","paid","Previous generation AI mastering suite — still widely used in the industry.","https://www.izotope.com/en/products/ozone.html",4.8,712),
    _p("Weiss Compressor Limiter","weiss-compressor-limiter","Softube","mastering","$299","paid","Emulation of the Weiss DS1 hardware compressor/limiter for mastering.","https://www.softube.com/weiss-ds1-mk3",4.8,423),
    _p("Sonnox Oxford Limiter V3 GE","sonnox-oxford-limiter-v3-ge","Sonnox","mastering","$399","paid","Gold Edition Oxford Limiter with Enhance algorithms for extra loudness.","https://www.sonnox.com/plugin/oxford-limiter",4.8,345),
    _p("MAAT thEQblue","maat-theqblue","MAAT Inc","mastering","$249","paid","High-resolution mastering EQ based on Sontec/Fokker algorithm.","https://maat.digital/theqblue/",4.7,234),
    _p("MAAT SantaCruzEQ","maat-santacruzeq","MAAT Inc","mastering","$199","paid","Mastering equalizer with minimum, linear, and analog phase modes.","https://maat.digital/santacruzeq/",4.6,189),
    _p("DMG Audio Limitless","dmg-audio-limitless","DMG Audio","mastering","$299","paid","True stereo multi-band limiter with 5-band processing for mastering.","https://dmgaudio.com/limitless",4.7,312),
    _p("DMG Audio TrackLimit","dmg-audio-tracklimit","DMG Audio","effects","$79","paid","Single-band peak limiter with high fidelity for individual tracks.","https://dmgaudio.com/tracklimit",4.6,234),
    _p("DMG Audio Equality","dmg-audio-equality","DMG Audio","effects","$149","paid","Flexible parametric EQ with analog modeling and linear phase modes.","https://dmgaudio.com/equality",4.7,312),
    _p("DMG Audio Compassion","dmg-audio-compassion","DMG Audio","effects","$149","paid","Comprehensive dynamics processor covering compression, expansion, and gating.","https://dmgaudio.com/compassion",4.7,289),
    _p("DMG Audio EQuilibrium","dmg-audio-equilibrium","DMG Audio","mastering","$249","paid","Advanced mastering EQ with mid-side processing and 5-band parametric control.","https://dmgaudio.com/equilibrium",4.7,267),

    # ─── SYNTHESIS (additional companies) ─────────────────────────────────────
    _p("Phaseplant","kilohearts-phaseplant-2","Kilohearts","synth","$199","paid","Comprehensive modular synthesizer update with new generators and Snap Heap integration.","https://kilohearts.com/products/phase_plant",4.8,712),
    _p("Slate + Ash Cycles","slate-ash-cycles","Slate + Ash","sampler","$99","paid","Organic, evolving pads and textures for contemporary composition and scoring.","https://www.slateandash.com/cycles",4.7,345),
    _p("Slate + Ash Choreographs","slate-ash-choreographs","Slate + Ash","sampler","$99","paid","Abstract rhythm and texture instrument exploring unusual timbres and patterns.","https://www.slateandash.com/choreographs",4.6,267),
    _p("Slate + Ash Obsidia","slate-ash-obsidia","Slate + Ash","sampler","$99","paid","Dark orchestral textures and hybrid sounds for film and media composition.","https://www.slateandash.com/obsidia",4.7,312),
    _p("Sample Logic Cinematic Keys","sample-logic-cinematic-keys","Sample Logic","sampler","$99","paid","Hybrid instrument combining piano samples with cinematic synthesis engines.","https://www.samplelogic.com/products/cinematic-keys/",4.6,289),
    _p("Sample Logic Rhythmology","sample-logic-rhythmology","Sample Logic","drums","$99","paid","Rhythm-focused instrument with tempo-sync loops and performance tools.","https://www.samplelogic.com/products/rhythmology/",4.6,234),
    _p("Waves Nx Virtual Mix Room","waves-nx-virtual-mix-room","Waves","utility","$49","paid","Headphone monitoring plugin that simulates a mixing room acoustic environment.","https://www.waves.com/plugins/nx#nx-virtual-mix-room-over-headphones",4.6,423),
    _p("Abbey Road Studio One","abbey-road-studio-one","Waves","effects","$49","paid","Reverb and room simulation of Studio One at Abbey Road Studios.","https://www.waves.com/plugins/abbey-road-studio-one",4.6,312),
    _p("Orchestral Tools Berlin Inspire 2","ot-berlin-inspire-2","Orchestral Tools","sampler","$199","paid","Expanded orchestral toolkit with additional articulations for the Berlin series.","https://www.orchestraltools.com/store/collections/inspire-2",4.7,445),
    _p("Orchestral Tools Nocturne Strings","ot-nocturne-strings","Orchestral Tools","sampler","$249","paid","Intimate night-time string library with muted and natural articulations.","https://www.orchestraltools.com/store/collections/nocturne",4.7,345),
    _p("Orchestral Tools Miroire","ot-miroire","Orchestral Tools","sampler","$149","paid","Delicate string harmonics library with natural sul ponticello and harmonic tones.","https://www.orchestraltools.com/store/collections/miroire",4.7,312),
    _p("Orchestral Tools Metropolis Ark 4","ot-metropolis-ark-4","Orchestral Tools","sampler","$499","paid","Monumental epic orchestral action featuring the full Berlin ensemble at full force.","https://www.orchestraltools.com/store/collections/metropolis-ark-4",4.8,456),
    _p("Native Instruments Komplete 14 Ultimate","ni-komplete-14-ultimate","Native Instruments","sampler","$1199","paid","The ultimate production toolkit with 135+ instruments and effects.","https://www.native-instruments.com/en/products/komplete/bundles/komplete-14-ultimate/",4.9,923),
    _p("Native Instruments Komplete 14 Collector's Edition","ni-komplete-14-collectors","Native Instruments","sampler","$1999","paid","Ultimate premium bundle with 160+ plugins, 120,000+ sounds, and exclusive content.","https://www.native-instruments.com/en/products/komplete/bundles/komplete-14-collectors-edition/",4.9,712),
    _p("Native Instruments Komplete 14","ni-komplete-14","Native Instruments","sampler","$599","paid","Core production bundle with 130+ instruments and over 13,000 sounds.","https://www.native-instruments.com/en/products/komplete/bundles/komplete-14/",4.9,1123),
    _p("Sonuscore Origins Vol.5 Native American Flute","sonuscore-origins-native-flute","Sonuscore","sampler","$79","paid","Authentic Native American flute with expressive playing techniques.","https://sonuscore.com/shop/origins-vol-5-native-american-flute/",4.7,245),
    _p("Sonuscore Origins Vol.6 African Kalimba","sonuscore-origins-kalimba","Sonuscore","sampler","$79","paid","Traditional African kalimba thumb piano with natural resonance and expression.","https://sonuscore.com/shop/origins-vol-6-african-kalimba/",4.7,234),
    _p("Sonuscore AEON Chamber Strings","sonuscore-aeon-chamber-strings","Sonuscore","sampler","$149","paid","Intimate chamber string ensemble with legato engine and phrase tools.","https://sonuscore.com/shop/aeon-chamber-strings/",4.7,312),
    _p("Soundiron Voices of Rapture","soundiron-voices-of-rapture","Soundiron","sampler","$149","paid","Angelic solo female voice with multi-dynamic and expressive legato.","https://soundiron.com/products/voices-of-rapture",4.6,267),
    _p("Soundiron Emotional Piano","soundiron-emotional-piano","Soundiron","sampler","$99","paid","Intimate upright piano with delicate felt dampers and emotional character.","https://soundiron.com/products/emotional-piano",4.7,312),
    _p("Soundiron Apocalypse Percussion Ensemble","soundiron-apocalypse-percussion","Soundiron","drums","$99","paid","Massive ensemble percussion library with epic taiko and war drums.","https://soundiron.com/products/apocalypse-percussion-ensemble",4.7,289),
    _p("Heavyocity DAMAGE 2 Expansion: Foundations","heavyocity-damage-foundations","Heavyocity","drums","$79","paid","Orchestral and hybrid percussion expansion for Damage 2.","https://www.heavyocity.com/product/damage-2/",4.7,234),
    _p("Impact Soundworks Shreddage 3 Legacy","impact-shreddage-3-legacy","Impact Soundworks","sampler","$99","paid","Rhythm guitar engine for rock, metal, and acoustic rhythm performances.","https://impactsoundworks.com/product/shreddage-3-legacy/",4.6,267),
    _p("Impact Soundworks Archtop","impact-archtop","Impact Soundworks","sampler","$79","paid","Hollow body jazz guitar with authentic chord voicings and improvised phrasing.","https://impactsoundworks.com/product/archtop/",4.6,245),
    _p("Impact Soundworks Felt Piano","impact-felt-piano","Impact Soundworks","sampler","$49","paid","Deeply sampled upright piano with felt dampers and intimate character.","https://impactsoundworks.com/product/felt-piano/",4.6,267),
    _p("Sampleson Collider","sampleson-collider","Sampleson","synth","$49","paid","Sample-based synthesizer with multi-engine design and unique oscillators.","https://sampleson.com/collider",4.5,234),
    _p("Sampleson Organteq","sampleson-organteq","Sampleson","synth","$79","paid","Physical modeling pipe organ with authentic pipe simulation.","https://sampleson.com/organteq",4.6,312),

    # ─── EDUCATIONAL / UTILITIES ──────────────────────────────────────────────
    _p("TriTone Digital Scale Workshop","tritone-scale-workshop","TriTone Digital","midi","$29","paid","Music theory tool for exploring scales, modes, and tuning systems.","https://www.tritonedigital.com/",4.4,189),
    _p("Captain Chords Epic","captain-chords-epic","Mixed In Key","midi","$149","paid","Advanced chord progression designer with midi export and key detection.","https://mixedinkey.com/captain-plugins/",4.5,345),
    _p("Mixed In Key 10","mixed-in-key-10","Mixed In Key","utility","$58","paid","Key analysis software for DJs and producers with Camelot wheel display.","https://mixedinkey.com/",4.7,712),
    _p("Platinum Notes 5","platinum-notes-5","Mixed In Key","utility","$99","paid","Audio mastering tool for DJs that normalizes and sweetens tracks.","https://mixedinkey.com/platinum-notes",4.4,345),
    _p("Soundbase","soundbase-plugin","Mixed In Key","utility","$29","paid","Sample organization and tagging tool with key and BPM detection.","https://mixedinkey.com/",4.4,267),
    _p("AudioSearch by Audiokinetic","audiokineic-audiosearch","Audiokinetic","utility","$49","paid","AI-powered sound effects search engine using audio similarity detection.","https://www.audiokinetic.com/products/audiosearch/",4.5,189),
    _p("iZotope Ozone 10 Music Production Suite 6","izotope-mps-6","iZotope","mastering","$999","paid","Complete creative and technical plugin suite from iZotope for all productions.","https://www.izotope.com/en/products/music-production-suite.html",4.8,534),

    # ─── BUDGET PLUGINS ───────────────────────────────────────────────────────
    _p("Ignite Amps PTEq-X","ignite-ptef-x","Ignite Amps","effects","Free","free","Free passive Pultec-style equalizer emulation with transformer saturation.","https://www.igniteamps.com/en/audio-plug-ins",4.6,712),
    _p("Ignite Amps Pro-F","ignite-pro-f","Ignite Amps","effects","Free","free","Free professional desk-style multi-band equalizer plugin.","https://www.igniteamps.com/en/audio-plug-ins",4.5,534),
    _p("Analog Obsession LALA","analog-obsession-lala","Analog Obsession","effects","Free","free","Free LA-2A optical tube compressor emulation with authentic circuit response.","https://www.patreon.com/analogobsession",4.7,712),
    _p("Analog Obsession BUSTERse","analog-obsession-busterse","Analog Obsession","effects","Free","free","Free SSL G-style stereo bus compressor emulation.","https://www.patreon.com/analogobsession",4.7,634),
    _p("Analog Obsession FETISH","analog-obsession-fetish","Analog Obsession","effects","Free","free","Free 1176-style FET compressor emulation with four ratio modes.","https://www.patreon.com/analogobsession",4.7,712),
    _p("Analog Obsession RARE","analog-obsession-rare","Analog Obsession","effects","Free","free","Free Neve 2254-style compressor/limiter emulation.","https://www.patreon.com/analogobsession",4.7,567),
    _p("Analog Obsession LIND78","analog-obsession-lind78","Analog Obsession","effects","Free","free","Free Neve 1073-style preamplifier and EQ emulation.","https://www.patreon.com/analogobsession",4.7,634),
    _p("Analog Obsession TUBEOP2","analog-obsession-tubeop2","Analog Obsession","effects","Free","free","Free tube compressor emulation with warm vintage character.","https://www.patreon.com/analogobsession",4.6,489),
    _p("Analog Obsession PREDD","analog-obsession-predd","Analog Obsession","effects","Free","free","Free discrete preamplifier emulation with harmonic saturation.","https://www.patreon.com/analogobsession",4.6,423),
    _p("Analog Obsession TREQ","analog-obsession-treq","Analog Obsession","effects","Free","free","Free transformer equalizer emulation with musical resonant character.","https://www.patreon.com/analogobsession",4.6,389),
    _p("Chow Matrix","chow-matrix","Chowdhury DSP","effects","Free","free","Free infinite complexity delay plugin with node-based delay routing.","https://chowdsp.com/products.html",4.7,534),
    _p("ChowPhaser","chow-phaser","Chowdhury DSP","effects","Free","free","Free phaser plugin with feedback and modulation inspired by classic units.","https://chowdsp.com/products.html",4.5,345),
    _p("ChowTapeModel","chow-tape-model","Chowdhury DSP","effects","Free","free","Free open-source tape machine emulation with wow, flutter, and saturation.","https://chowdsp.com/products.html",4.7,712),
    _p("Molot GE","molot-ge","Tokyo Dawn Records","effects","$29","paid","Russian-style compressor with a wild, colorful character for drums and bass.","https://www.tokyodawn.net/molot-ge/",4.6,345),
    _p("Loudmax","loudmax","Thomas Mundt","mastering","Free","free","Free look-ahead brick-wall loudness maximizer with transparent processing.","https://loudmax.blogspot.com/",4.5,712),

    # ─── MIXING TOOLS ─────────────────────────────────────────────────────────
    _p("Duet Capture","apogee-duet","Apogee","utility","$299","paid","Professional 2-in/4-out USB audio interface with studio-quality preamps.","https://apogeedigital.com/products/duet",4.7,534),
    _p("Focusrite Scarlett 2i2 4th Gen","focusrite-scarlett-2i2","Focusrite","utility","$179","paid","Compact 2-in/2-out USB audio interface with studio-quality converters.","https://focusrite.com/downloads/scarlett-2i2-studio-4th-gen/",4.8,1567),
    _p("iZotope Everything Bundle","izotope-everything-bundle","iZotope","effects","Subscription","subscription","Complete iZotope plugin catalog including Ozone, RX, Neutron, and more.","https://www.izotope.com/en/products/everything-bundle.html",4.9,712),
    _p("FabFilter Total Bundle","fabfilter-total-bundle","FabFilter","effects","$899","paid","All FabFilter plugins including Pro-Q 3, Pro-L 2, Saturn 2, and more.","https://www.fabfilter.com/shop/fabfilter-total-bundle",4.9,1234),
    _p("Waves Gold Bundle","waves-gold","Waves","effects","$599","paid","Classic bundle of 50+ Waves plugins covering dynamics, EQ, reverb, and spatial.","https://www.waves.com/bundles/gold",4.7,834),
    _p("Waves Platinum Bundle","waves-platinum","Waves","effects","$799","paid","Expanded bundle with 70+ Waves plugins including CLA and abbey road series.","https://www.waves.com/bundles/platinum",4.7,712),
    _p("Waves Mercury Bundle","waves-mercury","Waves","effects","Subscription","subscription","The complete Waves catalog including all plugins and updates.","https://www.waves.com/bundles/mercury",4.8,534),
    _p("Plugin Alliance Mix & Master Bundle","pa-mix-master-bundle","Plugin Alliance","effects","Subscription","subscription","Curated mixing and mastering bundle with 30 essential plugins.","https://www.plugin-alliance.com/en/products/bundles.html",4.7,423),
    _p("Native Instruments Guitar Rig 6 Elements","ni-guitar-rig-6-elements","Native Instruments","guitar","Free","free","Free version of Guitar Rig 6 with 13 components and 50 presets.","https://www.native-instruments.com/en/products/komplete/guitar/guitar-rig-6-pro/",4.5,712),
    _p("Positive Grid Spark Amp","positive-grid-spark","Positive Grid","guitar","$299","paid","40W smart guitar amp with AI Jam, Auto Chords, and app integration.","https://www.positivegrid.com/spark/",4.7,923),
    _p("Line 6 POD Go","line-6-pod-go","Line 6","guitar","$499","paid","Guitar processor with HX modeling and convenient board form factor.","https://line6.com/podgo/",4.7,712),
    _p("Kemper Profiler Plugin","kemper-profiler-plugin","Kemper","guitar","$99","paid","Software companion for Kemper Profiler hardware for offline editing.","https://www.kemper-amps.com/",4.7,345),
    _p("Two Notes Torpedo Studio","two-notes-torpedo-studio","Two Notes","guitar","$499","paid","Hardware DI box with speaker simulation and microphone placement software.","https://www.two-notes.com/torpedo-studio/",4.7,423),

    # ─── NOISE / SOUND DESIGN TOOLS ──────────────────────────────────────────
    _p("Zynaptiq PITCHMAP","zynaptiq-pitchmap","Zynaptiq","effects","$499","paid","Real-time polyphonic pitch correction and creative pitch mapping for any audio.","https://www.zynaptiq.com/pitchmap/",4.7,267),
    _p("Zynaptiq UNMIX:DRUMS","zynaptiq-unmix-drums","Zynaptiq","utility","$199","paid","Separates drums from mixed audio for re-mixing or removing drum sounds.","https://www.zynaptiq.com/unmixdrums/",4.6,267),
    _p("Zynaptiq MORPH 2","zynaptiq-morph-2","Zynaptiq","experimental","$299","paid","Real-time audio morphing plugin blending two audio signals spectrally.","https://www.zynaptiq.com/morph/",4.6,234),
    _p("Zynaptiq INTENSITY","zynaptiq-intensity","Zynaptiq","effects","$99","paid","Spectral clarity enhancer for making mixes sound louder without limiting.","https://www.zynaptiq.com/intensity/",4.6,289),
    _p("Sinevibes Fraction","sinevibes-fraction","Sinevibes","effects","$29","paid","Integer and non-integer bit crusher with sample rate reduction control.","https://www.sinevibes.com/fraction/",4.4,234),
    _p("Twisted Tools Ultraloop","twisted-tools-ultraloop","Twisted Tools","experimental","$49","paid","Loop slicer and rearrangement tool for creative beat and rhythm manipulation.","https://twistedtools.com/shop/reaktor/ultra-loop/",4.5,267),
    _p("Twisted Tools Buffeater","twisted-tools-buffeater","Twisted Tools","experimental","$49","paid","Buffer-based stutter and glitch effect inspired by hardware granulars.","https://twistedtools.com/",4.5,245),
    _p("Sublab XL","sublab-xl","Future Audio Workshop","drums","$79","paid","808 and sub bass synthesizer with layer system and distortion rack.","https://futureaudioworkshop.com/sublab-xl/",4.7,634),
    _p("Sublab","sublab","Future Audio Workshop","drums","$49","paid","Focused 808 and sub bass synthesizer for hip-hop and trap production.","https://futureaudioworkshop.com/sublab/",4.7,712),
    _p("Circle 2","circle-2","Future Audio Workshop","synth","$79","paid","Advanced wavetable synthesizer with 3-oscillator architecture.","https://futureaudioworkshop.com/circle-2/",4.6,345),
]
